import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../../data/database/app_database.dart';
import '../../../../data/models/sales/cashier_session_entity.dart';
import '../../../../data/models/sales/payment_entity.dart';

part 'waiter_settlement_service.freezed.dart';
part 'waiter_settlement_service.g.dart';

class OpenTablesPendingException implements Exception {
  final List<String> openTableNames;
  OpenTablesPendingException(this.openTableNames);

  @override
  String toString() =>
      'OpenTablesPendingException: No se puede cerrar el turno de mesero porque las siguientes mesas continúan abiertas: ${openTableNames.join(", ")}';
}

@freezed
class WaiterSettlementReport with _$WaiterSettlementReport {
  const WaiterSettlementReport._();

  const factory WaiterSettlementReport({
    required String shiftId,
    required String waiterUserId,
    required double totalSalesNio,
    required double totalCashCollectedNio,
    required double totalCardCollectedNio,
    required double totalTransferCollectedNio,
    required double totalTipsCollectedNio,
    required int invoicesCount,
    required int openTablesCount,
    @Default(<String>[]) List<String> openTableNames,
  }) = _WaiterSettlementReport;

  factory WaiterSettlementReport.fromJson(Map<String, dynamic> json) =>
      _$WaiterSettlementReportFromJson(json);

  bool get hasOpenTables => openTablesCount > 0;
  bool get canCloseShift => !hasOpenTables;
}

/// Service for calculating waiter / server shift settlements (carteraMesero) in restaurant environments.
class WaiterSettlementService {
  final AppDatabase _database;

  WaiterSettlementService(this._database);

  /// Calculates the settlement report for a waiter shift.
  Future<WaiterSettlementReport> calculateSettlement({
    required String shiftId,
    required String waiterUserId,
  }) async {
    final session = await _database.cashierSessionDao.getSessionById(shiftId);
    final startTime = session?.openedAt ?? 0;

    // 1. Get all invoices generated by this waiter during shift
    final invoices = await _database.invoiceDao.getInvoicesByUserId(waiterUserId);
    final shiftInvoices = invoices
        .where((inv) => !inv.isCanceled && inv.createdAt >= startTime)
        .toList();

    double totalSales = 0.0;
    double cashCollected = 0.0;
    double cardCollected = 0.0;
    double transferCollected = 0.0;
    double tipsCollected = 0.0;

    for (final inv in shiftInvoices) {
      totalSales += inv.total;

      final payments = await _database.paymentDao.getPaymentsByInvoiceId(inv.id);
      for (final pay in payments) {
        if (pay.method == 'cash') {
          cashCollected += (pay.amountNio - pay.changeGiven);
        } else if (pay.method == 'card') {
          cardCollected += pay.amountNio;
        } else {
          transferCollected += pay.amountNio;
        }
      }
    }

    // 2. Check open hold tickets for this waiter
    final allHoldTickets = await _database.holdTicketDao.getAllHoldTickets();
    final waiterHoldTickets = allHoldTickets
        .where((ht) => ht.waiterId == waiterUserId)
        .toList();

    final openTableNames = waiterHoldTickets.map((ht) => ht.name).toList();

    return WaiterSettlementReport(
      shiftId: shiftId,
      waiterUserId: waiterUserId,
      totalSalesNio: double.parse(totalSales.toStringAsFixed(2)),
      totalCashCollectedNio: double.parse(cashCollected.toStringAsFixed(2)),
      totalCardCollectedNio: double.parse(cardCollected.toStringAsFixed(2)),
      totalTransferCollectedNio: double.parse(transferCollected.toStringAsFixed(2)),
      totalTipsCollectedNio: double.parse(tipsCollected.toStringAsFixed(2)),
      invoicesCount: shiftInvoices.length,
      openTablesCount: waiterHoldTickets.length,
      openTableNames: openTableNames,
    );
  }

  /// Closes the waiter shift if all tables have been liquidated or transferred (INV-16.5).
  Future<CashierSessionEntity> closeWaiterShift({
    required String shiftId,
    required String waiterUserId,
    required double declaredCashNio,
    String? notes,
  }) async {
    final report = await calculateSettlement(
      shiftId: shiftId,
      waiterUserId: waiterUserId,
    );

    if (report.hasOpenTables) {
      throw OpenTablesPendingException(report.openTableNames);
    }

    final session = await _database.cashierSessionDao.getSessionById(shiftId);
    if (session == null) {
      throw StateError('El turno $shiftId no existe.');
    }

    final now = DateTime.now().millisecondsSinceEpoch;
    final closedSession = CashierSessionEntity(
      id: session.id,
      userId: session.userId,
      terminalId: session.terminalId,
      openedAt: session.openedAt,
      closedAt: now,
      openingBalanceNio: session.openingBalanceNio,
      openingBalanceUsd: session.openingBalanceUsd,
      closingCountedNio: declaredCashNio,
      closingCountedUsd: session.closingCountedUsd,
      expectedNio: report.totalCashCollectedNio + session.openingBalanceNio,
      isClosed: true,
      tipoModelo: session.tipoModelo,
      notes: notes ?? session.notes,
      syncStatus: 'pending',
    );

    await _database.cashierSessionDao.insertSession(closedSession);

    return closedSession;
  }
}
