/**
 * Stable OHAC contract error codes.
 *
 * Framework-free on purpose: domain and application layers import these
 * without depending on NestJS, TypeORM, Floor or bcrypt.
 */
export const OHAC_ERROR_CODE = {
  INVALID_UTF8: 'OHAC_INVALID_UTF8',
  INVALID_JSON: 'OHAC_INVALID_JSON',
  INVALID_UNICODE: 'OHAC_INVALID_UNICODE',
  DUPLICATE_KEY: 'OHAC_DUPLICATE_KEY',
  NUMBER_FORBIDDEN: 'OHAC_NUMBER_FORBIDDEN',
  NULL_FORBIDDEN: 'OHAC_NULL_FORBIDDEN',
  LIMIT_EXCEEDED: 'OHAC_LIMIT_EXCEEDED',
  UNKNOWN_FIELD: 'OHAC_UNKNOWN_FIELD',
  MISSING_FIELD: 'OHAC_MISSING_FIELD',
  INVALID_FIELD: 'OHAC_INVALID_FIELD',
  UNSUPPORTED_SCHEMA: 'OHAC_UNSUPPORTED_SCHEMA',
  DIGEST_MISMATCH: 'OHAC_DIGEST_MISMATCH',
  TENANT_SCOPE_MISMATCH: 'OHAC_TENANT_SCOPE_MISMATCH',
  SEQUENCE_NOT_NEWER: 'OHAC_SEQUENCE_NOT_NEWER',
  UNSUPPORTED_BUILD_PAIR: 'OHAC_UNSUPPORTED_BUILD_PAIR',
  CREDENTIAL_BINDING_MISMATCH: 'OHAC_CREDENTIAL_BINDING_MISMATCH',
  TENANT_TERMINAL_MISMATCH: 'OHAC_TENANT_TERMINAL_MISMATCH',

  // §10 API failure vocabulary (design §10). Recovery codes share the
  // OHAC_RECOVERY_ prefix so a terminal can branch on the family.
  TEMPORARY_UNAVAILABLE: 'OHAC_TEMPORARY_UNAVAILABLE',
  ACK_RESPONSE_LOST: 'OHAC_ACK_RESPONSE_LOST',
  ACK_DEFERRED_OUTBOX: 'OHAC_ACK_DEFERRED_OUTBOX',
  SEQUENCE_GAP: 'OHAC_SEQUENCE_GAP',
  ORIGIN_PENDING: 'OHAC_ORIGIN_PENDING',
  COHORT_DISABLED: 'OHAC_COHORT_DISABLED',
  UNSUPPORTED_BUILD: 'OHAC_UNSUPPORTED_BUILD',
  MALFORMED_ASSERTION: 'OHAC_MALFORMED_ASSERTION',
  STALE_EPOCH: 'OHAC_STALE_EPOCH',
  ACK_INCONSISTENT: 'OHAC_ACK_INCONSISTENT',
  INELIGIBLE_AUTHORIZER: 'OHAC_INELIGIBLE_AUTHORIZER',
  ASSERTION_REPLAY: 'OHAC_ASSERTION_REPLAY',
  IDEMPOTENCY_CONFLICT: 'OHAC_IDEMPOTENCY_CONFLICT',
  RECOVERY_EXPIRED: 'OHAC_RECOVERY_EXPIRED',
  RECOVERY_REVOKED: 'OHAC_RECOVERY_REVOKED',
  RECOVERY_USED: 'OHAC_RECOVERY_USED',
  RECOVERY_BINDING_MISMATCH: 'OHAC_RECOVERY_BINDING_MISMATCH',
  TRANSPORT_RECOVERY_REQUIRED: 'OHAC_TRANSPORT_RECOVERY_REQUIRED',
} as const;

export type OhacErrorCode =
  (typeof OHAC_ERROR_CODE)[keyof typeof OHAC_ERROR_CODE];

/**
 * HTTP mapping for OHAC codes (design §10): malformed 400, unauthenticated
 * transport 401, policy/binding/cohort 403, replay/idempotency/sequence
 * conflict 409, unsupported contract 422, transient 503. A Record over the
 * full code set makes adding a code without a status a compile error.
 */
export const OHAC_ERROR_HTTP_STATUS: Readonly<Record<OhacErrorCode, number>> = {
  // Canonicalization / contract framing: malformed input.
  OHAC_INVALID_UTF8: 400,
  OHAC_INVALID_JSON: 400,
  OHAC_INVALID_UNICODE: 400,
  OHAC_DUPLICATE_KEY: 409,
  OHAC_NUMBER_FORBIDDEN: 400,
  OHAC_NULL_FORBIDDEN: 400,
  OHAC_LIMIT_EXCEEDED: 400,
  OHAC_UNKNOWN_FIELD: 400,
  OHAC_MISSING_FIELD: 400,
  OHAC_INVALID_FIELD: 400,
  OHAC_UNSUPPORTED_SCHEMA: 422,
  OHAC_DIGEST_MISMATCH: 400,
  OHAC_TENANT_SCOPE_MISMATCH: 403,
  OHAC_SEQUENCE_NOT_NEWER: 409,
  OHAC_UNSUPPORTED_BUILD_PAIR: 422,
  // Authority / binding / cohort policy.
  OHAC_CREDENTIAL_BINDING_MISMATCH: 403,
  OHAC_TENANT_TERMINAL_MISMATCH: 403,
  OHAC_COHORT_DISABLED: 403,
  OHAC_UNSUPPORTED_BUILD: 422,
  OHAC_INELIGIBLE_AUTHORIZER: 403,
  // Replay / sequence / idempotency conflicts.
  OHAC_SEQUENCE_GAP: 409,
  OHAC_STALE_EPOCH: 409,
  OHAC_ACK_INCONSISTENT: 409,
  OHAC_ASSERTION_REPLAY: 409,
  OHAC_IDEMPOTENCY_CONFLICT: 409,
  OHAC_ORIGIN_PENDING: 409,
  OHAC_ACK_DEFERRED_OUTBOX: 409,
  // Assertion framing.
  OHAC_MALFORMED_ASSERTION: 400,
  // Recovery lifecycle.
  OHAC_RECOVERY_EXPIRED: 409,
  OHAC_RECOVERY_REVOKED: 403,
  OHAC_RECOVERY_USED: 409,
  OHAC_RECOVERY_BINDING_MISMATCH: 403,
  OHAC_TRANSPORT_RECOVERY_REQUIRED: 409,
  // Transient.
  OHAC_TEMPORARY_UNAVAILABLE: 503,
  OHAC_ACK_RESPONSE_LOST: 503,
};

export interface OhacError {
  readonly code: OhacErrorCode;
  /** Optional, non-secret context such as a field name. Never PIN or verifier material. */
  readonly field?: string;
}

export type OhacResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: OhacError };

export const ohacOk = <T>(value: T): OhacResult<T> => ({ ok: true, value });

export const ohacFail = <T>(
  code: OhacErrorCode,
  field?: string,
): OhacResult<T> => ({
  ok: false,
  error: field === undefined ? { code } : { code, field },
});
