// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/presentation/features/sales/sale_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i38;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_app/data/daos/audit_log_dao.dart' as _i5;
import 'package:pos_app/data/daos/catalog/catalog_value_dao.dart' as _i25;
import 'package:pos_app/data/daos/inventory/batch_dao.dart' as _i24;
import 'package:pos_app/data/daos/inventory/count_line_dao.dart' as _i11;
import 'package:pos_app/data/daos/inventory/count_session_dao.dart' as _i10;
import 'package:pos_app/data/daos/inventory/forensic_alert_dao.dart' as _i12;
import 'package:pos_app/data/daos/inventory/insumo_dao.dart' as _i7;
import 'package:pos_app/data/daos/inventory/inventory_dao.dart' as _i17;
import 'package:pos_app/data/daos/inventory/kardex_correction_dao.dart' as _i16;
import 'package:pos_app/data/daos/inventory/kardex_recalculate_queue_dao.dart'
    as _i15;
import 'package:pos_app/data/daos/inventory/movement_dao.dart' as _i13;
import 'package:pos_app/data/daos/inventory/movement_sync_state_dao.dart'
    as _i14;
import 'package:pos_app/data/daos/inventory/production_order_document_dao.dart'
    as _i21;
import 'package:pos_app/data/daos/inventory/production_transaction_dao.dart'
    as _i22;
import 'package:pos_app/data/daos/inventory/purchase_dao.dart' as _i20;
import 'package:pos_app/data/daos/inventory/recipe_dao.dart' as _i8;
import 'package:pos_app/data/daos/inventory/recipe_version_document_dao.dart'
    as _i9;
import 'package:pos_app/data/daos/inventory/supplier_dao.dart' as _i18;
import 'package:pos_app/data/daos/inventory/uom_conversion_dao.dart' as _i23;
import 'package:pos_app/data/daos/inventory/warehouse_dao.dart' as _i19;
import 'package:pos_app/data/daos/kitchen/kitchen_order_dao.dart' as _i37;
import 'package:pos_app/data/daos/local_config_dao.dart' as _i6;
import 'package:pos_app/data/daos/sales/cash_movement_dao.dart' as _i32;
import 'package:pos_app/data/daos/sales/cashier_session_dao.dart' as _i31;
import 'package:pos_app/data/daos/sales/hold_ticket_dao.dart' as _i33;
import 'package:pos_app/data/daos/sales/invoice_dao.dart' as _i26;
import 'package:pos_app/data/daos/sales/invoice_item_dao.dart' as _i27;
import 'package:pos_app/data/daos/sales/payment_dao.dart' as _i28;
import 'package:pos_app/data/daos/sales/promotion_dao.dart' as _i34;
import 'package:pos_app/data/daos/sales/restaurant_area_dao.dart' as _i35;
import 'package:pos_app/data/daos/sales/restaurant_table_dao.dart' as _i36;
import 'package:pos_app/data/daos/sales/sales_transaction_dao.dart' as _i30;
import 'package:pos_app/data/daos/sales/tax_config_dao.dart' as _i29;
import 'package:pos_app/data/daos/security_profile_dao.dart' as _i4;
import 'package:pos_app/data/daos/user_dao.dart' as _i3;
import 'package:pos_app/data/database/app_database.dart' as _i2;
import 'package:pos_app/data/models/inventory/kardex_correction_entity.dart'
    as _i61;
import 'package:pos_app/data/models/inventory/kardex_recalculate_queue_entity.dart'
    as _i62;
import 'package:pos_app/data/models/sales/cashier_session_entity.dart' as _i64;
import 'package:pos_app/data/models/sales/hold_ticket_entity.dart' as _i65;
import 'package:pos_app/data/models/sales/promotion_entity.dart' as _i66;
import 'package:pos_app/domain/models/catalog/catalog_type.dart' as _i57;
import 'package:pos_app/domain/models/catalog/catalog_value.dart' as _i56;
import 'package:pos_app/domain/models/inventory/batch.dart' as _i54;
import 'package:pos_app/domain/models/inventory/count_session_document.dart'
    as _i50;
import 'package:pos_app/domain/models/inventory/forensic_alert.dart' as _i59;
import 'package:pos_app/domain/models/inventory/insumo.dart' as _i46;
import 'package:pos_app/domain/models/inventory/inventory_movement.dart'
    as _i51;
import 'package:pos_app/domain/models/inventory/product.dart' as _i47;
import 'package:pos_app/domain/models/inventory/production_order_document.dart'
    as _i60;
import 'package:pos_app/domain/models/inventory/purchase.dart' as _i58;
import 'package:pos_app/domain/models/inventory/recipe.dart' as _i48;
import 'package:pos_app/domain/models/inventory/recipe_version_document.dart'
    as _i49;
import 'package:pos_app/domain/models/inventory/supplier.dart' as _i52;
import 'package:pos_app/domain/models/inventory/uom_conversion.dart' as _i55;
import 'package:pos_app/domain/models/inventory/warehouse.dart' as _i53;
import 'package:pos_app/domain/models/sales/invoice.dart' as _i41;
import 'package:pos_app/domain/models/sales/invoice_item.dart' as _i42;
import 'package:pos_app/domain/models/sales/payment.dart' as _i43;
import 'package:pos_app/domain/models/user.dart' as _i44;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i63;
import 'package:pos_app/domain/repositories/inventory/inventory_repository.dart'
    as _i45;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart'
    as _i40;
import 'package:sqflite/sqflite.dart' as _i39;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDao_1 extends _i1.SmartFake implements _i3.UserDao {
  _FakeUserDao_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityProfileDao_2 extends _i1.SmartFake
    implements _i4.SecurityProfileDao {
  _FakeSecurityProfileDao_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditDao_3 extends _i1.SmartFake implements _i5.AuditDao {
  _FakeAuditDao_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalConfigDao_4 extends _i1.SmartFake
    implements _i6.LocalConfigDao {
  _FakeLocalConfigDao_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsumoDao_5 extends _i1.SmartFake implements _i7.InsumoDao {
  _FakeInsumoDao_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductDao_6 extends _i1.SmartFake implements _i8.ProductDao {
  _FakeProductDao_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeDao_7 extends _i1.SmartFake implements _i8.RecipeDao {
  _FakeRecipeDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeVersionDocumentDao_8 extends _i1.SmartFake
    implements _i9.RecipeVersionDocumentDao {
  _FakeRecipeVersionDocumentDao_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountSessionDao_9 extends _i1.SmartFake
    implements _i10.CountSessionDao {
  _FakeCountSessionDao_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountLineDao_10 extends _i1.SmartFake implements _i11.CountLineDao {
  _FakeCountLineDao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForensicAlertDao_11 extends _i1.SmartFake
    implements _i12.ForensicAlertDao {
  _FakeForensicAlertDao_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementDao_12 extends _i1.SmartFake implements _i13.MovementDao {
  _FakeMovementDao_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementSyncStateDao_13 extends _i1.SmartFake
    implements _i14.MovementSyncStateDao {
  _FakeMovementSyncStateDao_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKardexRecalculateQueueDao_14 extends _i1.SmartFake
    implements _i15.KardexRecalculateQueueDao {
  _FakeKardexRecalculateQueueDao_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKardexCorrectionDao_15 extends _i1.SmartFake
    implements _i16.KardexCorrectionDao {
  _FakeKardexCorrectionDao_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventoryDao_16 extends _i1.SmartFake implements _i17.InventoryDao {
  _FakeInventoryDao_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplierDao_17 extends _i1.SmartFake implements _i18.SupplierDao {
  _FakeSupplierDao_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWarehouseDao_18 extends _i1.SmartFake implements _i19.WarehouseDao {
  _FakeWarehouseDao_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseDao_19 extends _i1.SmartFake implements _i20.PurchaseDao {
  _FakePurchaseDao_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionOrderDocumentDao_20 extends _i1.SmartFake
    implements _i21.ProductionOrderDocumentDao {
  _FakeProductionOrderDocumentDao_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionTransactionDao_21 extends _i1.SmartFake
    implements _i22.ProductionTransactionDao {
  _FakeProductionTransactionDao_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUomConversionDao_22 extends _i1.SmartFake
    implements _i23.UomConversionDao {
  _FakeUomConversionDao_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchDao_23 extends _i1.SmartFake implements _i24.BatchDao {
  _FakeBatchDao_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalogValueDao_24 extends _i1.SmartFake
    implements _i25.CatalogValueDao {
  _FakeCatalogValueDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDao_25 extends _i1.SmartFake implements _i26.InvoiceDao {
  _FakeInvoiceDao_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceItemDao_26 extends _i1.SmartFake
    implements _i27.InvoiceItemDao {
  _FakeInvoiceItemDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentDao_27 extends _i1.SmartFake implements _i28.PaymentDao {
  _FakePaymentDao_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaxConfigDao_28 extends _i1.SmartFake implements _i29.TaxConfigDao {
  _FakeTaxConfigDao_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesTransactionDao_29 extends _i1.SmartFake
    implements _i30.SalesTransactionDao {
  _FakeSalesTransactionDao_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashierSessionDao_30 extends _i1.SmartFake
    implements _i31.CashierSessionDao {
  _FakeCashierSessionDao_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashMovementDao_31 extends _i1.SmartFake
    implements _i32.CashMovementDao {
  _FakeCashMovementDao_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHoldTicketDao_32 extends _i1.SmartFake
    implements _i33.HoldTicketDao {
  _FakeHoldTicketDao_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromotionDao_33 extends _i1.SmartFake implements _i34.PromotionDao {
  _FakePromotionDao_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantAreaDao_34 extends _i1.SmartFake
    implements _i35.RestaurantAreaDao {
  _FakeRestaurantAreaDao_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantTableDao_35 extends _i1.SmartFake
    implements _i36.RestaurantTableDao {
  _FakeRestaurantTableDao_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenOrderDao_36 extends _i1.SmartFake
    implements _i37.KitchenOrderDao {
  _FakeKitchenOrderDao_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_37<T> extends _i1.SmartFake
    implements _i38.StreamController<T> {
  _FakeStreamController_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseExecutor_38 extends _i1.SmartFake
    implements _i39.DatabaseExecutor {
  _FakeDatabaseExecutor_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SalesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesRepository extends _i1.Mock implements _i40.SalesRepository {
  MockSalesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i38.Future<void> saveSale({
    required _i41.Invoice? invoice,
    required List<_i42.InvoiceItem>? items,
    required List<_i43.Payment>? payments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSale,
          [],
          {
            #invoice: invoice,
            #items: items,
            #payments: payments,
          },
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<_i41.Invoice?> getInvoiceById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i38.Future<_i41.Invoice?>.value(),
      ) as _i38.Future<_i41.Invoice?>);

  @override
  _i38.Future<_i41.Invoice?> getInvoiceByNumber(String? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceByNumber,
          [number],
        ),
        returnValue: _i38.Future<_i41.Invoice?>.value(),
      ) as _i38.Future<_i41.Invoice?>);

  @override
  _i38.Future<List<_i41.Invoice>> getUnsyncedInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedInvoices,
          [],
        ),
        returnValue: _i38.Future<List<_i41.Invoice>>.value(<_i41.Invoice>[]),
      ) as _i38.Future<List<_i41.Invoice>>);

  @override
  _i38.Future<List<Map<String, dynamic>>> getUnsyncedAggregates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedAggregates,
          [],
        ),
        returnValue: _i38.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i38.Future<List<Map<String, dynamic>>>);

  @override
  _i38.Future<void> markAsSynced(List<String>? invoiceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [invoiceIds],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> voidInvoice(
    String? invoiceId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reason,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> createCreditNote({
    required String? originalInvoiceId,
    required String? reason,
    required String? authorizedByUserId,
    required _i44.UserRole? authorizedByRole,
    _i40.RefundReasonPolicy? refundReasonPolicy =
        _i40.RefundReasonPolicy.restockOriginalBom,
    List<_i40.CreditNoteRefundLine>? lines,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCreditNote,
          [],
          {
            #originalInvoiceId: originalInvoiceId,
            #reason: reason,
            #authorizedByUserId: authorizedByUserId,
            #authorizedByRole: authorizedByRole,
            #refundReasonPolicy: refundReasonPolicy,
            #lines: lines,
          },
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i41.Invoice>> getInvoicesBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesBySessionId,
          [sessionId],
        ),
        returnValue: _i38.Future<List<_i41.Invoice>>.value(<_i41.Invoice>[]),
      ) as _i38.Future<List<_i41.Invoice>>);

  @override
  _i38.Future<List<_i43.Payment>> getPaymentsBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsBySessionId,
          [sessionId],
        ),
        returnValue: _i38.Future<List<_i43.Payment>>.value(<_i43.Payment>[]),
      ) as _i38.Future<List<_i43.Payment>>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i45.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.AppDatabase);

  @override
  _i38.Future<List<_i46.Insumo>> getActiveInsumos() => (super.noSuchMethod(
        Invocation.method(
          #getActiveInsumos,
          [],
        ),
        returnValue: _i38.Future<List<_i46.Insumo>>.value(<_i46.Insumo>[]),
      ) as _i38.Future<List<_i46.Insumo>>);

  @override
  _i38.Future<_i46.Insumo?> getInsumoById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsumoById,
          [id],
        ),
        returnValue: _i38.Future<_i46.Insumo?>.value(),
      ) as _i38.Future<_i46.Insumo?>);

  @override
  _i38.Future<List<_i46.Insumo>> getInsumosByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsumosByIds,
          [ids],
        ),
        returnValue: _i38.Future<List<_i46.Insumo>>.value(<_i46.Insumo>[]),
      ) as _i38.Future<List<_i46.Insumo>>);

  @override
  _i38.Future<void> updateInsumoStock(
    String? id,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoStock,
          [
            id,
            newStock,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> updateInsumoCost(
    String? id,
    double? newCost,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoCost,
          [
            id,
            newCost,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> saveInsumo(_i46.Insumo? insumo) => (super.noSuchMethod(
        Invocation.method(
          #saveInsumo,
          [insumo],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i47.Product>> getActiveProducts() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProducts,
          [],
        ),
        returnValue: _i38.Future<List<_i47.Product>>.value(<_i47.Product>[]),
      ) as _i38.Future<List<_i47.Product>>);

  @override
  _i38.Future<_i47.Product?> getProductById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i38.Future<_i47.Product?>.value(),
      ) as _i38.Future<_i47.Product?>);

  @override
  _i38.Future<void> saveProduct(_i47.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #saveProduct,
          [product],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> saveProductOptions({
    required String? productId,
    required List<_i47.ProductVariant>? variants,
    required List<_i47.Modifier>? modifiers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductOptions,
          [],
          {
            #productId: productId,
            #variants: variants,
            #modifiers: modifiers,
          },
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i48.Recipe>> getRecipeByProductId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeByProductId,
          [productId],
        ),
        returnValue: _i38.Future<List<_i48.Recipe>>.value(<_i48.Recipe>[]),
      ) as _i38.Future<List<_i48.Recipe>>);

  @override
  _i38.Future<void> saveRecipe(_i48.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [recipe],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> replaceRecipesForProduct(
    String? productId,
    List<_i48.Recipe>? recipes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceRecipesForProduct,
          [
            productId,
            recipes,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i49.RecipeVersionDocument>> getRecipeVersionDocuments(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocuments,
          [productId],
        ),
        returnValue: _i38.Future<List<_i49.RecipeVersionDocument>>.value(
            <_i49.RecipeVersionDocument>[]),
      ) as _i38.Future<List<_i49.RecipeVersionDocument>>);

  @override
  _i38.Future<String?> getActiveRecipeVersionId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecipeVersionId,
          [productId],
        ),
        returnValue: _i38.Future<String?>.value(),
      ) as _i38.Future<String?>);

  @override
  _i38.Future<_i49.RecipeVersionDocument?> getRecipeVersionDocumentById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocumentById,
          [id],
        ),
        returnValue: _i38.Future<_i49.RecipeVersionDocument?>.value(),
      ) as _i38.Future<_i49.RecipeVersionDocument?>);

  @override
  _i38.Future<void> saveRecipeVersionDocument(
          _i49.RecipeVersionDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipeVersionDocument,
          [document],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i49.RecipeVersionDocument>>
      getUnsyncedRecipeVersionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedRecipeVersionDocuments,
              [],
            ),
            returnValue: _i38.Future<List<_i49.RecipeVersionDocument>>.value(
                <_i49.RecipeVersionDocument>[]),
          ) as _i38.Future<List<_i49.RecipeVersionDocument>>);

  @override
  _i38.Future<void> markRecipeVersionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecipeVersionDocumentAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i50.CountSessionDocument>> getCountSessionDocuments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountSessionDocuments,
          [],
        ),
        returnValue: _i38.Future<List<_i50.CountSessionDocument>>.value(
            <_i50.CountSessionDocument>[]),
      ) as _i38.Future<List<_i50.CountSessionDocument>>);

  @override
  _i38.Future<void> saveCountSessionDocument(
          _i50.CountSessionDocument? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCountSessionDocument,
          [session],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i50.CountSessionDocument>>
      getUnsyncedCountSessionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedCountSessionDocuments,
              [],
            ),
            returnValue: _i38.Future<List<_i50.CountSessionDocument>>.value(
                <_i50.CountSessionDocument>[]),
          ) as _i38.Future<List<_i50.CountSessionDocument>>);

  @override
  _i38.Future<void> markCountSessionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markCountSessionDocumentAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> saveMovement(_i51.InventoryMovement? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMovement,
          [movement],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i51.InventoryMovement>> getAllMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMovements,
          [],
        ),
        returnValue: _i38.Future<List<_i51.InventoryMovement>>.value(
            <_i51.InventoryMovement>[]),
      ) as _i38.Future<List<_i51.InventoryMovement>>);

  @override
  _i38.Future<List<_i51.InventoryMovement>> getUnsyncedMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMovements,
          [],
        ),
        returnValue: _i38.Future<List<_i51.InventoryMovement>>.value(
            <_i51.InventoryMovement>[]),
      ) as _i38.Future<List<_i51.InventoryMovement>>);

  @override
  _i38.Future<void> markMovementAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMovementAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> markMovementAsFailed(
    String? id, {
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMovementAsFailed,
          [id],
          {#error: error},
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i52.Supplier>> getActiveSuppliers() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSuppliers,
          [],
        ),
        returnValue: _i38.Future<List<_i52.Supplier>>.value(<_i52.Supplier>[]),
      ) as _i38.Future<List<_i52.Supplier>>);

  @override
  _i38.Future<void> saveSupplier(_i52.Supplier? supplier) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSupplier,
          [supplier],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i53.Warehouse>> getActiveWarehouses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWarehouses,
          [],
        ),
        returnValue:
            _i38.Future<List<_i53.Warehouse>>.value(<_i53.Warehouse>[]),
      ) as _i38.Future<List<_i53.Warehouse>>);

  @override
  _i38.Future<void> saveWarehouse(_i53.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWarehouse,
          [warehouse],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i54.Batch>> getBatchesByInsumoId(String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchesByInsumoId,
          [insumoId],
        ),
        returnValue: _i38.Future<List<_i54.Batch>>.value(<_i54.Batch>[]),
      ) as _i38.Future<List<_i54.Batch>>);

  @override
  _i38.Future<void> saveBatch(_i54.Batch? batch) => (super.noSuchMethod(
        Invocation.method(
          #saveBatch,
          [batch],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i55.UomConversion>> getConversionsByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversionsByInsumoId,
          [insumoId],
        ),
        returnValue:
            _i38.Future<List<_i55.UomConversion>>.value(<_i55.UomConversion>[]),
      ) as _i38.Future<List<_i55.UomConversion>>);

  @override
  _i38.Future<void> saveConversion(_i55.UomConversion? conversion) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversion,
          [conversion],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> deleteConversion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConversion,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i56.CatalogValue>> getActiveCatalog(
          _i57.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCatalog,
          [type],
        ),
        returnValue:
            _i38.Future<List<_i56.CatalogValue>>.value(<_i56.CatalogValue>[]),
      ) as _i38.Future<List<_i56.CatalogValue>>);

  @override
  _i38.Future<List<_i56.CatalogValue>> getAllCatalog(_i57.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCatalog,
          [type],
        ),
        returnValue:
            _i38.Future<List<_i56.CatalogValue>>.value(<_i56.CatalogValue>[]),
      ) as _i38.Future<List<_i56.CatalogValue>>);

  @override
  _i38.Future<_i56.CatalogValue?> findCatalogByCode(
    _i57.CatalogType? type,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCatalogByCode,
          [
            type,
            code,
          ],
        ),
        returnValue: _i38.Future<_i56.CatalogValue?>.value(),
      ) as _i38.Future<_i56.CatalogValue?>);

  @override
  _i38.Future<void> upsertCatalogValues(List<_i56.CatalogValue>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertCatalogValues,
          [values],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> setCatalogActive(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCatalogActive,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<int> countCatalogValues() => (super.noSuchMethod(
        Invocation.method(
          #countCatalogValues,
          [],
        ),
        returnValue: _i38.Future<int>.value(0),
      ) as _i38.Future<int>);

  @override
  _i38.Future<void> savePurchase(_i58.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePurchase,
          [purchase],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> queuePurchaseSync(_i58.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #queuePurchaseSync,
          [purchase],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i58.Purchase>> getPurchaseHistory() => (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
        ),
        returnValue: _i38.Future<List<_i58.Purchase>>.value(<_i58.Purchase>[]),
      ) as _i38.Future<List<_i58.Purchase>>);

  @override
  _i38.Future<List<_i58.Purchase>> getUnsyncedPurchases() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPurchases,
          [],
        ),
        returnValue: _i38.Future<List<_i58.Purchase>>.value(<_i58.Purchase>[]),
      ) as _i38.Future<List<_i58.Purchase>>);

  @override
  _i38.Future<void> markPurchaseAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markPurchaseAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<double> fetchOfficialBcnRateByInvoiceDate(
          DateTime? invoiceDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOfficialBcnRateByInvoiceDate,
          [invoiceDate],
        ),
        returnValue: _i38.Future<double>.value(0.0),
      ) as _i38.Future<double>);

  @override
  _i38.Future<List<_i59.ForensicAlert>> getForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getForensicAlerts,
          [],
        ),
        returnValue:
            _i38.Future<List<_i59.ForensicAlert>>.value(<_i59.ForensicAlert>[]),
      ) as _i38.Future<List<_i59.ForensicAlert>>);

  @override
  _i38.Future<void> saveForensicAlert(_i59.ForensicAlert? alert) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveForensicAlert,
          [alert],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i59.ForensicAlert>> getUnsyncedForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedForensicAlerts,
          [],
        ),
        returnValue:
            _i38.Future<List<_i59.ForensicAlert>>.value(<_i59.ForensicAlert>[]),
      ) as _i38.Future<List<_i59.ForensicAlert>>);

  @override
  _i38.Future<void> markForensicAlertAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markForensicAlertAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i60.ProductionOrderDocument>>
      getProductionOrderDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getProductionOrderDocuments,
              [],
            ),
            returnValue: _i38.Future<List<_i60.ProductionOrderDocument>>.value(
                <_i60.ProductionOrderDocument>[]),
          ) as _i38.Future<List<_i60.ProductionOrderDocument>>);

  @override
  _i38.Future<int> reserveProductionSourceSequence(String? terminalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reserveProductionSourceSequence,
          [terminalId],
        ),
        returnValue: _i38.Future<int>.value(0),
      ) as _i38.Future<int>);

  @override
  _i38.Future<void> saveProductionOrderDocument(
          _i60.ProductionOrderDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionOrderDocument,
          [document],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> saveProductionCloseTransaction(
    _i60.ProductionOrderDocument? document,
    List<_i51.InventoryMovement>? movements, {
    bool? debugFailAfterWrites = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionCloseTransaction,
          [
            document,
            movements,
          ],
          {#debugFailAfterWrites: debugFailAfterWrites},
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i60.ProductionOrderDocument>>
      getUnsyncedProductionOrders() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedProductionOrders,
              [],
            ),
            returnValue: _i38.Future<List<_i60.ProductionOrderDocument>>.value(
                <_i60.ProductionOrderDocument>[]),
          ) as _i38.Future<List<_i60.ProductionOrderDocument>>);

  @override
  _i38.Future<void> markProductionOrderDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markProductionOrderDocumentAsSynced,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i61.KardexCorrectionEntity>> getKardexCorrections() =>
      (super.noSuchMethod(
        Invocation.method(
          #getKardexCorrections,
          [],
        ),
        returnValue: _i38.Future<List<_i61.KardexCorrectionEntity>>.value(
            <_i61.KardexCorrectionEntity>[]),
      ) as _i38.Future<List<_i61.KardexCorrectionEntity>>);

  @override
  _i38.Future<List<_i62.KardexRecalculateQueueEntity>>
      getPendingKardexQueue() => (super.noSuchMethod(
            Invocation.method(
              #getPendingKardexQueue,
              [],
            ),
            returnValue:
                _i38.Future<List<_i62.KardexRecalculateQueueEntity>>.value(
                    <_i62.KardexRecalculateQueueEntity>[]),
          ) as _i38.Future<List<_i62.KardexRecalculateQueueEntity>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i63.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
      ) as bool);

  @override
  _i38.Future<_i44.User?> loginOnline(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
        ),
        returnValue: _i38.Future<_i44.User?>.value(),
      ) as _i38.Future<_i44.User?>);

  @override
  _i38.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<_i44.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i38.Future<_i44.User?>.value(),
      ) as _i38.Future<_i44.User?>);

  @override
  _i38.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i38.Future<bool>.value(false),
      ) as _i38.Future<bool>);

  @override
  _i38.Future<_i44.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i38.Future<_i44.User?>.value(),
      ) as _i38.Future<_i44.User?>);

  @override
  _i38.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i38.Future<String?>.value(),
      ) as _i38.Future<String?>);

  @override
  _i38.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i44.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i38.Future<List<_i44.User>>.value(<_i44.User>[]),
      ) as _i38.Future<List<_i44.User>>);

  @override
  _i38.Future<void> saveUser(
    _i44.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserDao get userDao => (super.noSuchMethod(
        Invocation.getter(#userDao),
        returnValue: _FakeUserDao_1(
          this,
          Invocation.getter(#userDao),
        ),
      ) as _i3.UserDao);

  @override
  _i4.SecurityProfileDao get securityProfileDao => (super.noSuchMethod(
        Invocation.getter(#securityProfileDao),
        returnValue: _FakeSecurityProfileDao_2(
          this,
          Invocation.getter(#securityProfileDao),
        ),
      ) as _i4.SecurityProfileDao);

  @override
  _i5.AuditDao get auditDao => (super.noSuchMethod(
        Invocation.getter(#auditDao),
        returnValue: _FakeAuditDao_3(
          this,
          Invocation.getter(#auditDao),
        ),
      ) as _i5.AuditDao);

  @override
  _i6.LocalConfigDao get localConfigDao => (super.noSuchMethod(
        Invocation.getter(#localConfigDao),
        returnValue: _FakeLocalConfigDao_4(
          this,
          Invocation.getter(#localConfigDao),
        ),
      ) as _i6.LocalConfigDao);

  @override
  _i7.InsumoDao get insumoDao => (super.noSuchMethod(
        Invocation.getter(#insumoDao),
        returnValue: _FakeInsumoDao_5(
          this,
          Invocation.getter(#insumoDao),
        ),
      ) as _i7.InsumoDao);

  @override
  _i8.ProductDao get productDao => (super.noSuchMethod(
        Invocation.getter(#productDao),
        returnValue: _FakeProductDao_6(
          this,
          Invocation.getter(#productDao),
        ),
      ) as _i8.ProductDao);

  @override
  _i8.RecipeDao get recipeDao => (super.noSuchMethod(
        Invocation.getter(#recipeDao),
        returnValue: _FakeRecipeDao_7(
          this,
          Invocation.getter(#recipeDao),
        ),
      ) as _i8.RecipeDao);

  @override
  _i9.RecipeVersionDocumentDao get recipeVersionDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#recipeVersionDocumentDao),
        returnValue: _FakeRecipeVersionDocumentDao_8(
          this,
          Invocation.getter(#recipeVersionDocumentDao),
        ),
      ) as _i9.RecipeVersionDocumentDao);

  @override
  _i10.CountSessionDao get countSessionDao => (super.noSuchMethod(
        Invocation.getter(#countSessionDao),
        returnValue: _FakeCountSessionDao_9(
          this,
          Invocation.getter(#countSessionDao),
        ),
      ) as _i10.CountSessionDao);

  @override
  _i11.CountLineDao get countLineDao => (super.noSuchMethod(
        Invocation.getter(#countLineDao),
        returnValue: _FakeCountLineDao_10(
          this,
          Invocation.getter(#countLineDao),
        ),
      ) as _i11.CountLineDao);

  @override
  _i12.ForensicAlertDao get forensicAlertDao => (super.noSuchMethod(
        Invocation.getter(#forensicAlertDao),
        returnValue: _FakeForensicAlertDao_11(
          this,
          Invocation.getter(#forensicAlertDao),
        ),
      ) as _i12.ForensicAlertDao);

  @override
  _i13.MovementDao get movementDao => (super.noSuchMethod(
        Invocation.getter(#movementDao),
        returnValue: _FakeMovementDao_12(
          this,
          Invocation.getter(#movementDao),
        ),
      ) as _i13.MovementDao);

  @override
  _i14.MovementSyncStateDao get movementSyncStateDao => (super.noSuchMethod(
        Invocation.getter(#movementSyncStateDao),
        returnValue: _FakeMovementSyncStateDao_13(
          this,
          Invocation.getter(#movementSyncStateDao),
        ),
      ) as _i14.MovementSyncStateDao);

  @override
  _i15.KardexRecalculateQueueDao get kardexRecalculateQueueDao =>
      (super.noSuchMethod(
        Invocation.getter(#kardexRecalculateQueueDao),
        returnValue: _FakeKardexRecalculateQueueDao_14(
          this,
          Invocation.getter(#kardexRecalculateQueueDao),
        ),
      ) as _i15.KardexRecalculateQueueDao);

  @override
  _i16.KardexCorrectionDao get kardexCorrectionDao => (super.noSuchMethod(
        Invocation.getter(#kardexCorrectionDao),
        returnValue: _FakeKardexCorrectionDao_15(
          this,
          Invocation.getter(#kardexCorrectionDao),
        ),
      ) as _i16.KardexCorrectionDao);

  @override
  _i17.InventoryDao get inventoryDao => (super.noSuchMethod(
        Invocation.getter(#inventoryDao),
        returnValue: _FakeInventoryDao_16(
          this,
          Invocation.getter(#inventoryDao),
        ),
      ) as _i17.InventoryDao);

  @override
  _i18.SupplierDao get supplierDao => (super.noSuchMethod(
        Invocation.getter(#supplierDao),
        returnValue: _FakeSupplierDao_17(
          this,
          Invocation.getter(#supplierDao),
        ),
      ) as _i18.SupplierDao);

  @override
  _i19.WarehouseDao get warehouseDao => (super.noSuchMethod(
        Invocation.getter(#warehouseDao),
        returnValue: _FakeWarehouseDao_18(
          this,
          Invocation.getter(#warehouseDao),
        ),
      ) as _i19.WarehouseDao);

  @override
  _i20.PurchaseDao get purchaseDao => (super.noSuchMethod(
        Invocation.getter(#purchaseDao),
        returnValue: _FakePurchaseDao_19(
          this,
          Invocation.getter(#purchaseDao),
        ),
      ) as _i20.PurchaseDao);

  @override
  _i21.ProductionOrderDocumentDao get productionOrderDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#productionOrderDocumentDao),
        returnValue: _FakeProductionOrderDocumentDao_20(
          this,
          Invocation.getter(#productionOrderDocumentDao),
        ),
      ) as _i21.ProductionOrderDocumentDao);

  @override
  _i22.ProductionTransactionDao get productionTransactionDao =>
      (super.noSuchMethod(
        Invocation.getter(#productionTransactionDao),
        returnValue: _FakeProductionTransactionDao_21(
          this,
          Invocation.getter(#productionTransactionDao),
        ),
      ) as _i22.ProductionTransactionDao);

  @override
  _i23.UomConversionDao get uomConversionDao => (super.noSuchMethod(
        Invocation.getter(#uomConversionDao),
        returnValue: _FakeUomConversionDao_22(
          this,
          Invocation.getter(#uomConversionDao),
        ),
      ) as _i23.UomConversionDao);

  @override
  _i24.BatchDao get batchDao => (super.noSuchMethod(
        Invocation.getter(#batchDao),
        returnValue: _FakeBatchDao_23(
          this,
          Invocation.getter(#batchDao),
        ),
      ) as _i24.BatchDao);

  @override
  _i25.CatalogValueDao get catalogValueDao => (super.noSuchMethod(
        Invocation.getter(#catalogValueDao),
        returnValue: _FakeCatalogValueDao_24(
          this,
          Invocation.getter(#catalogValueDao),
        ),
      ) as _i25.CatalogValueDao);

  @override
  _i26.InvoiceDao get invoiceDao => (super.noSuchMethod(
        Invocation.getter(#invoiceDao),
        returnValue: _FakeInvoiceDao_25(
          this,
          Invocation.getter(#invoiceDao),
        ),
      ) as _i26.InvoiceDao);

  @override
  _i27.InvoiceItemDao get invoiceItemDao => (super.noSuchMethod(
        Invocation.getter(#invoiceItemDao),
        returnValue: _FakeInvoiceItemDao_26(
          this,
          Invocation.getter(#invoiceItemDao),
        ),
      ) as _i27.InvoiceItemDao);

  @override
  _i28.PaymentDao get paymentDao => (super.noSuchMethod(
        Invocation.getter(#paymentDao),
        returnValue: _FakePaymentDao_27(
          this,
          Invocation.getter(#paymentDao),
        ),
      ) as _i28.PaymentDao);

  @override
  _i29.TaxConfigDao get taxConfigDao => (super.noSuchMethod(
        Invocation.getter(#taxConfigDao),
        returnValue: _FakeTaxConfigDao_28(
          this,
          Invocation.getter(#taxConfigDao),
        ),
      ) as _i29.TaxConfigDao);

  @override
  _i30.SalesTransactionDao get salesTransactionDao => (super.noSuchMethod(
        Invocation.getter(#salesTransactionDao),
        returnValue: _FakeSalesTransactionDao_29(
          this,
          Invocation.getter(#salesTransactionDao),
        ),
      ) as _i30.SalesTransactionDao);

  @override
  _i31.CashierSessionDao get cashierSessionDao => (super.noSuchMethod(
        Invocation.getter(#cashierSessionDao),
        returnValue: _FakeCashierSessionDao_30(
          this,
          Invocation.getter(#cashierSessionDao),
        ),
      ) as _i31.CashierSessionDao);

  @override
  _i32.CashMovementDao get cashMovementDao => (super.noSuchMethod(
        Invocation.getter(#cashMovementDao),
        returnValue: _FakeCashMovementDao_31(
          this,
          Invocation.getter(#cashMovementDao),
        ),
      ) as _i32.CashMovementDao);

  @override
  _i33.HoldTicketDao get holdTicketDao => (super.noSuchMethod(
        Invocation.getter(#holdTicketDao),
        returnValue: _FakeHoldTicketDao_32(
          this,
          Invocation.getter(#holdTicketDao),
        ),
      ) as _i33.HoldTicketDao);

  @override
  _i34.PromotionDao get promotionDao => (super.noSuchMethod(
        Invocation.getter(#promotionDao),
        returnValue: _FakePromotionDao_33(
          this,
          Invocation.getter(#promotionDao),
        ),
      ) as _i34.PromotionDao);

  @override
  _i35.RestaurantAreaDao get restaurantAreaDao => (super.noSuchMethod(
        Invocation.getter(#restaurantAreaDao),
        returnValue: _FakeRestaurantAreaDao_34(
          this,
          Invocation.getter(#restaurantAreaDao),
        ),
      ) as _i35.RestaurantAreaDao);

  @override
  _i36.RestaurantTableDao get restaurantTableDao => (super.noSuchMethod(
        Invocation.getter(#restaurantTableDao),
        returnValue: _FakeRestaurantTableDao_35(
          this,
          Invocation.getter(#restaurantTableDao),
        ),
      ) as _i36.RestaurantTableDao);

  @override
  _i37.KitchenOrderDao get kitchenOrderDao => (super.noSuchMethod(
        Invocation.getter(#kitchenOrderDao),
        returnValue: _FakeKitchenOrderDao_36(
          this,
          Invocation.getter(#kitchenOrderDao),
        ),
      ) as _i37.KitchenOrderDao);

  @override
  _i38.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_37<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i38.StreamController<String>);

  @override
  set changeListener(_i38.StreamController<String>? _changeListener) =>
      super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          _changeListener,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i39.DatabaseExecutor get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseExecutor_38(
          this,
          Invocation.getter(#database),
        ),
      ) as _i39.DatabaseExecutor);

  @override
  set database(_i39.DatabaseExecutor? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i38.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);
}

/// A class which mocks [CashierSessionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashierSessionDao extends _i1.Mock implements _i31.CashierSessionDao {
  MockCashierSessionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i38.Future<_i64.CashierSessionEntity?> getSessionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [id],
        ),
        returnValue: _i38.Future<_i64.CashierSessionEntity?>.value(),
      ) as _i38.Future<_i64.CashierSessionEntity?>);

  @override
  _i38.Future<_i64.CashierSessionEntity?> getActiveSession() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i38.Future<_i64.CashierSessionEntity?>.value(),
      ) as _i38.Future<_i64.CashierSessionEntity?>);

  @override
  _i38.Future<void> insertSession(_i64.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSession,
          [session],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> updateSession(_i64.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [session],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i64.CashierSessionEntity>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i38.Future<List<_i64.CashierSessionEntity>>.value(
            <_i64.CashierSessionEntity>[]),
      ) as _i38.Future<List<_i64.CashierSessionEntity>>);

  @override
  _i38.Future<int?> countClosedSessions() => (super.noSuchMethod(
        Invocation.method(
          #countClosedSessions,
          [],
        ),
        returnValue: _i38.Future<int?>.value(),
      ) as _i38.Future<int?>);
}

/// A class which mocks [HoldTicketDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockHoldTicketDao extends _i1.Mock implements _i33.HoldTicketDao {
  MockHoldTicketDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i38.Future<List<_i65.HoldTicketEntity>> getAllHoldTickets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHoldTickets,
          [],
        ),
        returnValue: _i38.Future<List<_i65.HoldTicketEntity>>.value(
            <_i65.HoldTicketEntity>[]),
      ) as _i38.Future<List<_i65.HoldTicketEntity>>);

  @override
  _i38.Future<_i65.HoldTicketEntity?> getHoldTicketById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHoldTicketById,
          [id],
        ),
        returnValue: _i38.Future<_i65.HoldTicketEntity?>.value(),
      ) as _i38.Future<_i65.HoldTicketEntity?>);

  @override
  _i38.Future<_i65.HoldTicketEntity?> getHoldTicketByTableId(String? tableId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHoldTicketByTableId,
          [tableId],
        ),
        returnValue: _i38.Future<_i65.HoldTicketEntity?>.value(),
      ) as _i38.Future<_i65.HoldTicketEntity?>);

  @override
  _i38.Future<List<_i65.HoldTicketItemEntity>> getItemsByHoldTicketId(
          String? holdTicketId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByHoldTicketId,
          [holdTicketId],
        ),
        returnValue: _i38.Future<List<_i65.HoldTicketItemEntity>>.value(
            <_i65.HoldTicketItemEntity>[]),
      ) as _i38.Future<List<_i65.HoldTicketItemEntity>>);

  @override
  _i38.Future<void> insertHoldTicket(_i65.HoldTicketEntity? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicket,
          [ticket],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> insertHoldTicketItems(
          List<_i65.HoldTicketItemEntity>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicketItems,
          [items],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<int> updateHoldTicket(_i65.HoldTicketEntity? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHoldTicket,
          [ticket],
        ),
        returnValue: _i38.Future<int>.value(0),
      ) as _i38.Future<int>);

  @override
  _i38.Future<void> deleteHoldTicketItems(String? holdTicketId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicketItems,
          [holdTicketId],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> deleteHoldTicket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicket,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> saveHoldTicket(
    _i65.HoldTicketEntity? ticket,
    List<_i65.HoldTicketItemEntity>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHoldTicket,
          [
            ticket,
            items,
          ],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> deleteHoldTicketWithItems(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicketWithItems,
          [id],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);
}

/// A class which mocks [PromotionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromotionDao extends _i1.Mock implements _i34.PromotionDao {
  MockPromotionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i38.Future<List<_i66.PromotionEntity>> getActivePromotions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePromotions,
          [],
        ),
        returnValue: _i38.Future<List<_i66.PromotionEntity>>.value(
            <_i66.PromotionEntity>[]),
      ) as _i38.Future<List<_i66.PromotionEntity>>);

  @override
  _i38.Future<void> savePromotion(_i66.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePromotion,
          [promotion],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<void> updatePromotion(_i66.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePromotion,
          [promotion],
        ),
        returnValue: _i38.Future<void>.value(),
        returnValueForMissingStub: _i38.Future<void>.value(),
      ) as _i38.Future<void>);

  @override
  _i38.Future<List<_i66.PromotionEntity>> getPromotionsByProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromotionsByProduct,
          [productId],
        ),
        returnValue: _i38.Future<List<_i66.PromotionEntity>>.value(
            <_i66.PromotionEntity>[]),
      ) as _i38.Future<List<_i66.PromotionEntity>>);
}
