// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/presentation/features/sales/sale_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i31;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_app/data/daos/audit_log_dao.dart' as _i5;
import 'package:pos_app/data/daos/catalog/catalog_value_dao.dart' as _i22;
import 'package:pos_app/data/daos/inventory/batch_dao.dart' as _i21;
import 'package:pos_app/data/daos/inventory/count_line_dao.dart' as _i11;
import 'package:pos_app/data/daos/inventory/count_session_dao.dart' as _i10;
import 'package:pos_app/data/daos/inventory/forensic_alert_dao.dart' as _i12;
import 'package:pos_app/data/daos/inventory/insumo_dao.dart' as _i7;
import 'package:pos_app/data/daos/inventory/inventory_dao.dart' as _i15;
import 'package:pos_app/data/daos/inventory/movement_dao.dart' as _i13;
import 'package:pos_app/data/daos/inventory/movement_sync_state_dao.dart'
    as _i14;
import 'package:pos_app/data/daos/inventory/production_order_document_dao.dart'
    as _i19;
import 'package:pos_app/data/daos/inventory/purchase_dao.dart' as _i18;
import 'package:pos_app/data/daos/inventory/recipe_dao.dart' as _i8;
import 'package:pos_app/data/daos/inventory/recipe_version_document_dao.dart'
    as _i9;
import 'package:pos_app/data/daos/inventory/supplier_dao.dart' as _i16;
import 'package:pos_app/data/daos/inventory/uom_conversion_dao.dart' as _i20;
import 'package:pos_app/data/daos/inventory/warehouse_dao.dart' as _i17;
import 'package:pos_app/data/daos/local_config_dao.dart' as _i6;
import 'package:pos_app/data/daos/sales/cashier_session_dao.dart' as _i28;
import 'package:pos_app/data/daos/sales/hold_ticket_dao.dart' as _i29;
import 'package:pos_app/data/daos/sales/invoice_dao.dart' as _i23;
import 'package:pos_app/data/daos/sales/invoice_item_dao.dart' as _i24;
import 'package:pos_app/data/daos/sales/payment_dao.dart' as _i25;
import 'package:pos_app/data/daos/sales/promotion_dao.dart' as _i30;
import 'package:pos_app/data/daos/sales/sales_transaction_dao.dart' as _i27;
import 'package:pos_app/data/daos/sales/tax_config_dao.dart' as _i26;
import 'package:pos_app/data/daos/security_profile_dao.dart' as _i4;
import 'package:pos_app/data/daos/user_dao.dart' as _i3;
import 'package:pos_app/data/database/app_database.dart' as _i2;
import 'package:pos_app/data/models/sales/cashier_session_entity.dart' as _i55;
import 'package:pos_app/data/models/sales/hold_ticket_entity.dart' as _i56;
import 'package:pos_app/data/models/sales/promotion_entity.dart' as _i57;
import 'package:pos_app/domain/models/catalog/catalog_type.dart' as _i49;
import 'package:pos_app/domain/models/catalog/catalog_value.dart' as _i48;
import 'package:pos_app/domain/models/inventory/batch.dart' as _i46;
import 'package:pos_app/domain/models/inventory/count_session_document.dart'
    as _i42;
import 'package:pos_app/domain/models/inventory/forensic_alert.dart' as _i51;
import 'package:pos_app/domain/models/inventory/insumo.dart' as _i38;
import 'package:pos_app/domain/models/inventory/inventory_movement.dart'
    as _i43;
import 'package:pos_app/domain/models/inventory/product.dart' as _i39;
import 'package:pos_app/domain/models/inventory/production_order_document.dart'
    as _i52;
import 'package:pos_app/domain/models/inventory/purchase.dart' as _i50;
import 'package:pos_app/domain/models/inventory/recipe.dart' as _i40;
import 'package:pos_app/domain/models/inventory/recipe_version_document.dart'
    as _i41;
import 'package:pos_app/domain/models/inventory/supplier.dart' as _i44;
import 'package:pos_app/domain/models/inventory/uom_conversion.dart' as _i47;
import 'package:pos_app/domain/models/inventory/warehouse.dart' as _i45;
import 'package:pos_app/domain/models/sales/invoice.dart' as _i34;
import 'package:pos_app/domain/models/sales/invoice_item.dart' as _i35;
import 'package:pos_app/domain/models/sales/payment.dart' as _i36;
import 'package:pos_app/domain/models/user.dart' as _i54;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i53;
import 'package:pos_app/domain/repositories/inventory/inventory_repository.dart'
    as _i37;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart'
    as _i33;
import 'package:sqflite/sqflite.dart' as _i32;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDao_1 extends _i1.SmartFake implements _i3.UserDao {
  _FakeUserDao_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityProfileDao_2 extends _i1.SmartFake
    implements _i4.SecurityProfileDao {
  _FakeSecurityProfileDao_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditDao_3 extends _i1.SmartFake implements _i5.AuditDao {
  _FakeAuditDao_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalConfigDao_4 extends _i1.SmartFake
    implements _i6.LocalConfigDao {
  _FakeLocalConfigDao_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsumoDao_5 extends _i1.SmartFake implements _i7.InsumoDao {
  _FakeInsumoDao_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductDao_6 extends _i1.SmartFake implements _i8.ProductDao {
  _FakeProductDao_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeDao_7 extends _i1.SmartFake implements _i8.RecipeDao {
  _FakeRecipeDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeVersionDocumentDao_8 extends _i1.SmartFake
    implements _i9.RecipeVersionDocumentDao {
  _FakeRecipeVersionDocumentDao_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountSessionDao_9 extends _i1.SmartFake
    implements _i10.CountSessionDao {
  _FakeCountSessionDao_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountLineDao_10 extends _i1.SmartFake implements _i11.CountLineDao {
  _FakeCountLineDao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForensicAlertDao_11 extends _i1.SmartFake
    implements _i12.ForensicAlertDao {
  _FakeForensicAlertDao_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementDao_12 extends _i1.SmartFake implements _i13.MovementDao {
  _FakeMovementDao_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementSyncStateDao_13 extends _i1.SmartFake
    implements _i14.MovementSyncStateDao {
  _FakeMovementSyncStateDao_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventoryDao_14 extends _i1.SmartFake implements _i15.InventoryDao {
  _FakeInventoryDao_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplierDao_15 extends _i1.SmartFake implements _i16.SupplierDao {
  _FakeSupplierDao_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWarehouseDao_16 extends _i1.SmartFake implements _i17.WarehouseDao {
  _FakeWarehouseDao_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseDao_17 extends _i1.SmartFake implements _i18.PurchaseDao {
  _FakePurchaseDao_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionOrderDocumentDao_18 extends _i1.SmartFake
    implements _i19.ProductionOrderDocumentDao {
  _FakeProductionOrderDocumentDao_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUomConversionDao_19 extends _i1.SmartFake
    implements _i20.UomConversionDao {
  _FakeUomConversionDao_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchDao_20 extends _i1.SmartFake implements _i21.BatchDao {
  _FakeBatchDao_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalogValueDao_21 extends _i1.SmartFake
    implements _i22.CatalogValueDao {
  _FakeCatalogValueDao_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDao_22 extends _i1.SmartFake implements _i23.InvoiceDao {
  _FakeInvoiceDao_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceItemDao_23 extends _i1.SmartFake
    implements _i24.InvoiceItemDao {
  _FakeInvoiceItemDao_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentDao_24 extends _i1.SmartFake implements _i25.PaymentDao {
  _FakePaymentDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaxConfigDao_25 extends _i1.SmartFake implements _i26.TaxConfigDao {
  _FakeTaxConfigDao_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesTransactionDao_26 extends _i1.SmartFake
    implements _i27.SalesTransactionDao {
  _FakeSalesTransactionDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashierSessionDao_27 extends _i1.SmartFake
    implements _i28.CashierSessionDao {
  _FakeCashierSessionDao_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHoldTicketDao_28 extends _i1.SmartFake
    implements _i29.HoldTicketDao {
  _FakeHoldTicketDao_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromotionDao_29 extends _i1.SmartFake implements _i30.PromotionDao {
  _FakePromotionDao_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_30<T> extends _i1.SmartFake
    implements _i31.StreamController<T> {
  _FakeStreamController_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseExecutor_31 extends _i1.SmartFake
    implements _i32.DatabaseExecutor {
  _FakeDatabaseExecutor_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SalesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesRepository extends _i1.Mock implements _i33.SalesRepository {
  MockSalesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.Future<void> saveSale({
    required _i34.Invoice? invoice,
    required List<_i35.InvoiceItem>? items,
    required List<_i36.Payment>? payments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSale,
          [],
          {
            #invoice: invoice,
            #items: items,
            #payments: payments,
          },
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<_i34.Invoice?> getInvoiceById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i31.Future<_i34.Invoice?>.value(),
      ) as _i31.Future<_i34.Invoice?>);

  @override
  _i31.Future<_i34.Invoice?> getInvoiceByNumber(String? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceByNumber,
          [number],
        ),
        returnValue: _i31.Future<_i34.Invoice?>.value(),
      ) as _i31.Future<_i34.Invoice?>);

  @override
  _i31.Future<List<_i34.Invoice>> getUnsyncedInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedInvoices,
          [],
        ),
        returnValue: _i31.Future<List<_i34.Invoice>>.value(<_i34.Invoice>[]),
      ) as _i31.Future<List<_i34.Invoice>>);

  @override
  _i31.Future<List<Map<String, dynamic>>> getUnsyncedAggregates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedAggregates,
          [],
        ),
        returnValue: _i31.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i31.Future<List<Map<String, dynamic>>>);

  @override
  _i31.Future<void> markAsSynced(List<String>? invoiceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [invoiceIds],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> voidInvoice(
    String? invoiceId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reason,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> createCreditNote({
    required String? originalInvoiceId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCreditNote,
          [],
          {
            #originalInvoiceId: originalInvoiceId,
            #reason: reason,
          },
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i34.Invoice>> getInvoicesBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesBySessionId,
          [sessionId],
        ),
        returnValue: _i31.Future<List<_i34.Invoice>>.value(<_i34.Invoice>[]),
      ) as _i31.Future<List<_i34.Invoice>>);

  @override
  _i31.Future<List<_i36.Payment>> getPaymentsBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsBySessionId,
          [sessionId],
        ),
        returnValue: _i31.Future<List<_i36.Payment>>.value(<_i36.Payment>[]),
      ) as _i31.Future<List<_i36.Payment>>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i37.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.AppDatabase);

  @override
  _i31.Future<List<_i38.Insumo>> getActiveInsumos() => (super.noSuchMethod(
        Invocation.method(
          #getActiveInsumos,
          [],
        ),
        returnValue: _i31.Future<List<_i38.Insumo>>.value(<_i38.Insumo>[]),
      ) as _i31.Future<List<_i38.Insumo>>);

  @override
  _i31.Future<_i38.Insumo?> getInsumoById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsumoById,
          [id],
        ),
        returnValue: _i31.Future<_i38.Insumo?>.value(),
      ) as _i31.Future<_i38.Insumo?>);

  @override
  _i31.Future<List<_i38.Insumo>> getInsumosByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsumosByIds,
          [ids],
        ),
        returnValue: _i31.Future<List<_i38.Insumo>>.value(<_i38.Insumo>[]),
      ) as _i31.Future<List<_i38.Insumo>>);

  @override
  _i31.Future<void> updateInsumoStock(
    String? id,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoStock,
          [
            id,
            newStock,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> updateInsumoCost(
    String? id,
    double? newCost,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoCost,
          [
            id,
            newCost,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> saveInsumo(_i38.Insumo? insumo) => (super.noSuchMethod(
        Invocation.method(
          #saveInsumo,
          [insumo],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i39.Product>> getActiveProducts() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProducts,
          [],
        ),
        returnValue: _i31.Future<List<_i39.Product>>.value(<_i39.Product>[]),
      ) as _i31.Future<List<_i39.Product>>);

  @override
  _i31.Future<_i39.Product?> getProductById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i31.Future<_i39.Product?>.value(),
      ) as _i31.Future<_i39.Product?>);

  @override
  _i31.Future<void> saveProduct(_i39.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #saveProduct,
          [product],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> saveProductOptions({
    required String? productId,
    required List<_i39.ProductVariant>? variants,
    required List<_i39.Modifier>? modifiers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductOptions,
          [],
          {
            #productId: productId,
            #variants: variants,
            #modifiers: modifiers,
          },
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i40.Recipe>> getRecipeByProductId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeByProductId,
          [productId],
        ),
        returnValue: _i31.Future<List<_i40.Recipe>>.value(<_i40.Recipe>[]),
      ) as _i31.Future<List<_i40.Recipe>>);

  @override
  _i31.Future<void> saveRecipe(_i40.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [recipe],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> replaceRecipesForProduct(
    String? productId,
    List<_i40.Recipe>? recipes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceRecipesForProduct,
          [
            productId,
            recipes,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i41.RecipeVersionDocument>> getRecipeVersionDocuments(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocuments,
          [productId],
        ),
        returnValue: _i31.Future<List<_i41.RecipeVersionDocument>>.value(
            <_i41.RecipeVersionDocument>[]),
      ) as _i31.Future<List<_i41.RecipeVersionDocument>>);

  @override
  _i31.Future<String?> getActiveRecipeVersionId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecipeVersionId,
          [productId],
        ),
        returnValue: _i31.Future<String?>.value(),
      ) as _i31.Future<String?>);

  @override
  _i31.Future<_i41.RecipeVersionDocument?> getRecipeVersionDocumentById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocumentById,
          [id],
        ),
        returnValue: _i31.Future<_i41.RecipeVersionDocument?>.value(),
      ) as _i31.Future<_i41.RecipeVersionDocument?>);

  @override
  _i31.Future<void> saveRecipeVersionDocument(
          _i41.RecipeVersionDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipeVersionDocument,
          [document],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i41.RecipeVersionDocument>>
      getUnsyncedRecipeVersionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedRecipeVersionDocuments,
              [],
            ),
            returnValue: _i31.Future<List<_i41.RecipeVersionDocument>>.value(
                <_i41.RecipeVersionDocument>[]),
          ) as _i31.Future<List<_i41.RecipeVersionDocument>>);

  @override
  _i31.Future<void> markRecipeVersionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecipeVersionDocumentAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i42.CountSessionDocument>> getCountSessionDocuments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountSessionDocuments,
          [],
        ),
        returnValue: _i31.Future<List<_i42.CountSessionDocument>>.value(
            <_i42.CountSessionDocument>[]),
      ) as _i31.Future<List<_i42.CountSessionDocument>>);

  @override
  _i31.Future<void> saveCountSessionDocument(
          _i42.CountSessionDocument? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCountSessionDocument,
          [session],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i42.CountSessionDocument>>
      getUnsyncedCountSessionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedCountSessionDocuments,
              [],
            ),
            returnValue: _i31.Future<List<_i42.CountSessionDocument>>.value(
                <_i42.CountSessionDocument>[]),
          ) as _i31.Future<List<_i42.CountSessionDocument>>);

  @override
  _i31.Future<void> markCountSessionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markCountSessionDocumentAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> saveMovement(_i43.InventoryMovement? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMovement,
          [movement],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i43.InventoryMovement>> getAllMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMovements,
          [],
        ),
        returnValue: _i31.Future<List<_i43.InventoryMovement>>.value(
            <_i43.InventoryMovement>[]),
      ) as _i31.Future<List<_i43.InventoryMovement>>);

  @override
  _i31.Future<List<_i43.InventoryMovement>> getUnsyncedMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMovements,
          [],
        ),
        returnValue: _i31.Future<List<_i43.InventoryMovement>>.value(
            <_i43.InventoryMovement>[]),
      ) as _i31.Future<List<_i43.InventoryMovement>>);

  @override
  _i31.Future<void> markMovementAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMovementAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> markMovementAsFailed(
    String? id, {
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMovementAsFailed,
          [id],
          {#error: error},
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i44.Supplier>> getActiveSuppliers() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSuppliers,
          [],
        ),
        returnValue: _i31.Future<List<_i44.Supplier>>.value(<_i44.Supplier>[]),
      ) as _i31.Future<List<_i44.Supplier>>);

  @override
  _i31.Future<void> saveSupplier(_i44.Supplier? supplier) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSupplier,
          [supplier],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i45.Warehouse>> getActiveWarehouses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWarehouses,
          [],
        ),
        returnValue:
            _i31.Future<List<_i45.Warehouse>>.value(<_i45.Warehouse>[]),
      ) as _i31.Future<List<_i45.Warehouse>>);

  @override
  _i31.Future<void> saveWarehouse(_i45.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWarehouse,
          [warehouse],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i46.Batch>> getBatchesByInsumoId(String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchesByInsumoId,
          [insumoId],
        ),
        returnValue: _i31.Future<List<_i46.Batch>>.value(<_i46.Batch>[]),
      ) as _i31.Future<List<_i46.Batch>>);

  @override
  _i31.Future<void> saveBatch(_i46.Batch? batch) => (super.noSuchMethod(
        Invocation.method(
          #saveBatch,
          [batch],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i47.UomConversion>> getConversionsByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversionsByInsumoId,
          [insumoId],
        ),
        returnValue:
            _i31.Future<List<_i47.UomConversion>>.value(<_i47.UomConversion>[]),
      ) as _i31.Future<List<_i47.UomConversion>>);

  @override
  _i31.Future<void> saveConversion(_i47.UomConversion? conversion) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversion,
          [conversion],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> deleteConversion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConversion,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i48.CatalogValue>> getActiveCatalog(
          _i49.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCatalog,
          [type],
        ),
        returnValue:
            _i31.Future<List<_i48.CatalogValue>>.value(<_i48.CatalogValue>[]),
      ) as _i31.Future<List<_i48.CatalogValue>>);

  @override
  _i31.Future<List<_i48.CatalogValue>> getAllCatalog(_i49.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCatalog,
          [type],
        ),
        returnValue:
            _i31.Future<List<_i48.CatalogValue>>.value(<_i48.CatalogValue>[]),
      ) as _i31.Future<List<_i48.CatalogValue>>);

  @override
  _i31.Future<_i48.CatalogValue?> findCatalogByCode(
    _i49.CatalogType? type,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCatalogByCode,
          [
            type,
            code,
          ],
        ),
        returnValue: _i31.Future<_i48.CatalogValue?>.value(),
      ) as _i31.Future<_i48.CatalogValue?>);

  @override
  _i31.Future<void> upsertCatalogValues(List<_i48.CatalogValue>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertCatalogValues,
          [values],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> setCatalogActive(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCatalogActive,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<int> countCatalogValues() => (super.noSuchMethod(
        Invocation.method(
          #countCatalogValues,
          [],
        ),
        returnValue: _i31.Future<int>.value(0),
      ) as _i31.Future<int>);

  @override
  _i31.Future<void> savePurchase(_i50.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePurchase,
          [purchase],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> queuePurchaseSync(_i50.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #queuePurchaseSync,
          [purchase],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i50.Purchase>> getPurchaseHistory() => (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
        ),
        returnValue: _i31.Future<List<_i50.Purchase>>.value(<_i50.Purchase>[]),
      ) as _i31.Future<List<_i50.Purchase>>);

  @override
  _i31.Future<List<_i50.Purchase>> getUnsyncedPurchases() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPurchases,
          [],
        ),
        returnValue: _i31.Future<List<_i50.Purchase>>.value(<_i50.Purchase>[]),
      ) as _i31.Future<List<_i50.Purchase>>);

  @override
  _i31.Future<void> markPurchaseAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markPurchaseAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i51.ForensicAlert>> getForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getForensicAlerts,
          [],
        ),
        returnValue:
            _i31.Future<List<_i51.ForensicAlert>>.value(<_i51.ForensicAlert>[]),
      ) as _i31.Future<List<_i51.ForensicAlert>>);

  @override
  _i31.Future<void> saveForensicAlert(_i51.ForensicAlert? alert) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveForensicAlert,
          [alert],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i51.ForensicAlert>> getUnsyncedForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedForensicAlerts,
          [],
        ),
        returnValue:
            _i31.Future<List<_i51.ForensicAlert>>.value(<_i51.ForensicAlert>[]),
      ) as _i31.Future<List<_i51.ForensicAlert>>);

  @override
  _i31.Future<void> markForensicAlertAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markForensicAlertAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i52.ProductionOrderDocument>>
      getProductionOrderDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getProductionOrderDocuments,
              [],
            ),
            returnValue: _i31.Future<List<_i52.ProductionOrderDocument>>.value(
                <_i52.ProductionOrderDocument>[]),
          ) as _i31.Future<List<_i52.ProductionOrderDocument>>);

  @override
  _i31.Future<void> saveProductionOrderDocument(
          _i52.ProductionOrderDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionOrderDocument,
          [document],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i52.ProductionOrderDocument>>
      getUnsyncedProductionOrders() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedProductionOrders,
              [],
            ),
            returnValue: _i31.Future<List<_i52.ProductionOrderDocument>>.value(
                <_i52.ProductionOrderDocument>[]),
          ) as _i31.Future<List<_i52.ProductionOrderDocument>>);

  @override
  _i31.Future<void> markProductionOrderDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markProductionOrderDocumentAsSynced,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i53.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
      ) as bool);

  @override
  _i31.Future<_i54.User?> loginOnline(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
        ),
        returnValue: _i31.Future<_i54.User?>.value(),
      ) as _i31.Future<_i54.User?>);

  @override
  _i31.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<_i54.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i31.Future<_i54.User?>.value(),
      ) as _i31.Future<_i54.User?>);

  @override
  _i31.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i31.Future<bool>.value(false),
      ) as _i31.Future<bool>);

  @override
  _i31.Future<_i54.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i31.Future<_i54.User?>.value(),
      ) as _i31.Future<_i54.User?>);

  @override
  _i31.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i31.Future<String?>.value(),
      ) as _i31.Future<String?>);

  @override
  _i31.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i54.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i31.Future<List<_i54.User>>.value(<_i54.User>[]),
      ) as _i31.Future<List<_i54.User>>);

  @override
  _i31.Future<void> saveUser(
    _i54.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserDao get userDao => (super.noSuchMethod(
        Invocation.getter(#userDao),
        returnValue: _FakeUserDao_1(
          this,
          Invocation.getter(#userDao),
        ),
      ) as _i3.UserDao);

  @override
  _i4.SecurityProfileDao get securityProfileDao => (super.noSuchMethod(
        Invocation.getter(#securityProfileDao),
        returnValue: _FakeSecurityProfileDao_2(
          this,
          Invocation.getter(#securityProfileDao),
        ),
      ) as _i4.SecurityProfileDao);

  @override
  _i5.AuditDao get auditDao => (super.noSuchMethod(
        Invocation.getter(#auditDao),
        returnValue: _FakeAuditDao_3(
          this,
          Invocation.getter(#auditDao),
        ),
      ) as _i5.AuditDao);

  @override
  _i6.LocalConfigDao get localConfigDao => (super.noSuchMethod(
        Invocation.getter(#localConfigDao),
        returnValue: _FakeLocalConfigDao_4(
          this,
          Invocation.getter(#localConfigDao),
        ),
      ) as _i6.LocalConfigDao);

  @override
  _i7.InsumoDao get insumoDao => (super.noSuchMethod(
        Invocation.getter(#insumoDao),
        returnValue: _FakeInsumoDao_5(
          this,
          Invocation.getter(#insumoDao),
        ),
      ) as _i7.InsumoDao);

  @override
  _i8.ProductDao get productDao => (super.noSuchMethod(
        Invocation.getter(#productDao),
        returnValue: _FakeProductDao_6(
          this,
          Invocation.getter(#productDao),
        ),
      ) as _i8.ProductDao);

  @override
  _i8.RecipeDao get recipeDao => (super.noSuchMethod(
        Invocation.getter(#recipeDao),
        returnValue: _FakeRecipeDao_7(
          this,
          Invocation.getter(#recipeDao),
        ),
      ) as _i8.RecipeDao);

  @override
  _i9.RecipeVersionDocumentDao get recipeVersionDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#recipeVersionDocumentDao),
        returnValue: _FakeRecipeVersionDocumentDao_8(
          this,
          Invocation.getter(#recipeVersionDocumentDao),
        ),
      ) as _i9.RecipeVersionDocumentDao);

  @override
  _i10.CountSessionDao get countSessionDao => (super.noSuchMethod(
        Invocation.getter(#countSessionDao),
        returnValue: _FakeCountSessionDao_9(
          this,
          Invocation.getter(#countSessionDao),
        ),
      ) as _i10.CountSessionDao);

  @override
  _i11.CountLineDao get countLineDao => (super.noSuchMethod(
        Invocation.getter(#countLineDao),
        returnValue: _FakeCountLineDao_10(
          this,
          Invocation.getter(#countLineDao),
        ),
      ) as _i11.CountLineDao);

  @override
  _i12.ForensicAlertDao get forensicAlertDao => (super.noSuchMethod(
        Invocation.getter(#forensicAlertDao),
        returnValue: _FakeForensicAlertDao_11(
          this,
          Invocation.getter(#forensicAlertDao),
        ),
      ) as _i12.ForensicAlertDao);

  @override
  _i13.MovementDao get movementDao => (super.noSuchMethod(
        Invocation.getter(#movementDao),
        returnValue: _FakeMovementDao_12(
          this,
          Invocation.getter(#movementDao),
        ),
      ) as _i13.MovementDao);

  @override
  _i14.MovementSyncStateDao get movementSyncStateDao => (super.noSuchMethod(
        Invocation.getter(#movementSyncStateDao),
        returnValue: _FakeMovementSyncStateDao_13(
          this,
          Invocation.getter(#movementSyncStateDao),
        ),
      ) as _i14.MovementSyncStateDao);

  @override
  _i15.InventoryDao get inventoryDao => (super.noSuchMethod(
        Invocation.getter(#inventoryDao),
        returnValue: _FakeInventoryDao_14(
          this,
          Invocation.getter(#inventoryDao),
        ),
      ) as _i15.InventoryDao);

  @override
  _i16.SupplierDao get supplierDao => (super.noSuchMethod(
        Invocation.getter(#supplierDao),
        returnValue: _FakeSupplierDao_15(
          this,
          Invocation.getter(#supplierDao),
        ),
      ) as _i16.SupplierDao);

  @override
  _i17.WarehouseDao get warehouseDao => (super.noSuchMethod(
        Invocation.getter(#warehouseDao),
        returnValue: _FakeWarehouseDao_16(
          this,
          Invocation.getter(#warehouseDao),
        ),
      ) as _i17.WarehouseDao);

  @override
  _i18.PurchaseDao get purchaseDao => (super.noSuchMethod(
        Invocation.getter(#purchaseDao),
        returnValue: _FakePurchaseDao_17(
          this,
          Invocation.getter(#purchaseDao),
        ),
      ) as _i18.PurchaseDao);

  @override
  _i19.ProductionOrderDocumentDao get productionOrderDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#productionOrderDocumentDao),
        returnValue: _FakeProductionOrderDocumentDao_18(
          this,
          Invocation.getter(#productionOrderDocumentDao),
        ),
      ) as _i19.ProductionOrderDocumentDao);

  @override
  _i20.UomConversionDao get uomConversionDao => (super.noSuchMethod(
        Invocation.getter(#uomConversionDao),
        returnValue: _FakeUomConversionDao_19(
          this,
          Invocation.getter(#uomConversionDao),
        ),
      ) as _i20.UomConversionDao);

  @override
  _i21.BatchDao get batchDao => (super.noSuchMethod(
        Invocation.getter(#batchDao),
        returnValue: _FakeBatchDao_20(
          this,
          Invocation.getter(#batchDao),
        ),
      ) as _i21.BatchDao);

  @override
  _i22.CatalogValueDao get catalogValueDao => (super.noSuchMethod(
        Invocation.getter(#catalogValueDao),
        returnValue: _FakeCatalogValueDao_21(
          this,
          Invocation.getter(#catalogValueDao),
        ),
      ) as _i22.CatalogValueDao);

  @override
  _i23.InvoiceDao get invoiceDao => (super.noSuchMethod(
        Invocation.getter(#invoiceDao),
        returnValue: _FakeInvoiceDao_22(
          this,
          Invocation.getter(#invoiceDao),
        ),
      ) as _i23.InvoiceDao);

  @override
  _i24.InvoiceItemDao get invoiceItemDao => (super.noSuchMethod(
        Invocation.getter(#invoiceItemDao),
        returnValue: _FakeInvoiceItemDao_23(
          this,
          Invocation.getter(#invoiceItemDao),
        ),
      ) as _i24.InvoiceItemDao);

  @override
  _i25.PaymentDao get paymentDao => (super.noSuchMethod(
        Invocation.getter(#paymentDao),
        returnValue: _FakePaymentDao_24(
          this,
          Invocation.getter(#paymentDao),
        ),
      ) as _i25.PaymentDao);

  @override
  _i26.TaxConfigDao get taxConfigDao => (super.noSuchMethod(
        Invocation.getter(#taxConfigDao),
        returnValue: _FakeTaxConfigDao_25(
          this,
          Invocation.getter(#taxConfigDao),
        ),
      ) as _i26.TaxConfigDao);

  @override
  _i27.SalesTransactionDao get salesTransactionDao => (super.noSuchMethod(
        Invocation.getter(#salesTransactionDao),
        returnValue: _FakeSalesTransactionDao_26(
          this,
          Invocation.getter(#salesTransactionDao),
        ),
      ) as _i27.SalesTransactionDao);

  @override
  _i28.CashierSessionDao get cashierSessionDao => (super.noSuchMethod(
        Invocation.getter(#cashierSessionDao),
        returnValue: _FakeCashierSessionDao_27(
          this,
          Invocation.getter(#cashierSessionDao),
        ),
      ) as _i28.CashierSessionDao);

  @override
  _i29.HoldTicketDao get holdTicketDao => (super.noSuchMethod(
        Invocation.getter(#holdTicketDao),
        returnValue: _FakeHoldTicketDao_28(
          this,
          Invocation.getter(#holdTicketDao),
        ),
      ) as _i29.HoldTicketDao);

  @override
  _i30.PromotionDao get promotionDao => (super.noSuchMethod(
        Invocation.getter(#promotionDao),
        returnValue: _FakePromotionDao_29(
          this,
          Invocation.getter(#promotionDao),
        ),
      ) as _i30.PromotionDao);

  @override
  _i31.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_30<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i31.StreamController<String>);

  @override
  set changeListener(_i31.StreamController<String>? _changeListener) =>
      super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          _changeListener,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i32.DatabaseExecutor get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseExecutor_31(
          this,
          Invocation.getter(#database),
        ),
      ) as _i32.DatabaseExecutor);

  @override
  set database(_i32.DatabaseExecutor? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i31.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);
}

/// A class which mocks [CashierSessionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashierSessionDao extends _i1.Mock implements _i28.CashierSessionDao {
  MockCashierSessionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.Future<_i55.CashierSessionEntity?> getSessionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [id],
        ),
        returnValue: _i31.Future<_i55.CashierSessionEntity?>.value(),
      ) as _i31.Future<_i55.CashierSessionEntity?>);

  @override
  _i31.Future<_i55.CashierSessionEntity?> getActiveSession() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i31.Future<_i55.CashierSessionEntity?>.value(),
      ) as _i31.Future<_i55.CashierSessionEntity?>);

  @override
  _i31.Future<void> insertSession(_i55.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSession,
          [session],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> updateSession(_i55.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [session],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i55.CashierSessionEntity>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i31.Future<List<_i55.CashierSessionEntity>>.value(
            <_i55.CashierSessionEntity>[]),
      ) as _i31.Future<List<_i55.CashierSessionEntity>>);
}

/// A class which mocks [HoldTicketDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockHoldTicketDao extends _i1.Mock implements _i29.HoldTicketDao {
  MockHoldTicketDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.Future<List<_i56.HoldTicketEntity>> getAllHoldTickets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHoldTickets,
          [],
        ),
        returnValue: _i31.Future<List<_i56.HoldTicketEntity>>.value(
            <_i56.HoldTicketEntity>[]),
      ) as _i31.Future<List<_i56.HoldTicketEntity>>);

  @override
  _i31.Future<List<_i56.HoldTicketItemEntity>> getItemsByHoldTicketId(
          String? holdTicketId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByHoldTicketId,
          [holdTicketId],
        ),
        returnValue: _i31.Future<List<_i56.HoldTicketItemEntity>>.value(
            <_i56.HoldTicketItemEntity>[]),
      ) as _i31.Future<List<_i56.HoldTicketItemEntity>>);

  @override
  _i31.Future<void> insertHoldTicket(_i56.HoldTicketEntity? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicket,
          [ticket],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> insertHoldTicketItems(
          List<_i56.HoldTicketItemEntity>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicketItems,
          [items],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> deleteHoldTicket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicket,
          [id],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> saveHoldTicket(
    _i56.HoldTicketEntity? ticket,
    List<_i56.HoldTicketItemEntity>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHoldTicket,
          [
            ticket,
            items,
          ],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);
}

/// A class which mocks [PromotionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromotionDao extends _i1.Mock implements _i30.PromotionDao {
  MockPromotionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.Future<List<_i57.PromotionEntity>> getActivePromotions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePromotions,
          [],
        ),
        returnValue: _i31.Future<List<_i57.PromotionEntity>>.value(
            <_i57.PromotionEntity>[]),
      ) as _i31.Future<List<_i57.PromotionEntity>>);

  @override
  _i31.Future<void> savePromotion(_i57.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePromotion,
          [promotion],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<void> updatePromotion(_i57.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePromotion,
          [promotion],
        ),
        returnValue: _i31.Future<void>.value(),
        returnValueForMissingStub: _i31.Future<void>.value(),
      ) as _i31.Future<void>);

  @override
  _i31.Future<List<_i57.PromotionEntity>> getPromotionsByProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromotionsByProduct,
          [productId],
        ),
        returnValue: _i31.Future<List<_i57.PromotionEntity>>.value(
            <_i57.PromotionEntity>[]),
      ) as _i31.Future<List<_i57.PromotionEntity>>);
}
