// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/domain/services/config/printer_config_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_app/data/daos/local_config_dao.dart' as _i2;
import 'package:pos_app/data/models/local_config_entity.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalConfigDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalConfigDao extends _i1.Mock implements _i2.LocalConfigDao {
  @override
  _i3.Future<_i4.LocalConfigEntity?> getConfigByKey(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfigByKey,
          [key],
        ),
        returnValue: _i3.Future<_i4.LocalConfigEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.LocalConfigEntity?>.value(),
      ) as _i3.Future<_i4.LocalConfigEntity?>);

  @override
  _i3.Future<void> saveConfig(_i4.LocalConfigEntity? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteConfig(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteConfig,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
