// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/data/repositories/inventory/inventory_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i29;

import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i39;
import 'package:dio/src/dio.dart' as _i7;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_app/data/daos/audit_log_dao.dart' as _i10;
import 'package:pos_app/data/daos/inventory/batch_dao.dart' as _i20;
import 'package:pos_app/data/daos/inventory/insumo_dao.dart' as _i12;
import 'package:pos_app/data/daos/inventory/inventory_dao.dart' as _i15;
import 'package:pos_app/data/daos/inventory/movement_dao.dart' as _i14;
import 'package:pos_app/data/daos/inventory/purchase_dao.dart' as _i18;
import 'package:pos_app/data/daos/inventory/recipe_dao.dart' as _i13;
import 'package:pos_app/data/daos/inventory/supplier_dao.dart' as _i16;
import 'package:pos_app/data/daos/inventory/uom_conversion_dao.dart' as _i19;
import 'package:pos_app/data/daos/inventory/warehouse_dao.dart' as _i17;
import 'package:pos_app/data/daos/local_config_dao.dart' as _i11;
import 'package:pos_app/data/daos/sales/cashier_session_dao.dart' as _i26;
import 'package:pos_app/data/daos/sales/hold_ticket_dao.dart' as _i27;
import 'package:pos_app/data/daos/sales/invoice_dao.dart' as _i21;
import 'package:pos_app/data/daos/sales/invoice_item_dao.dart' as _i22;
import 'package:pos_app/data/daos/sales/payment_dao.dart' as _i23;
import 'package:pos_app/data/daos/sales/promotion_dao.dart' as _i28;
import 'package:pos_app/data/daos/sales/sales_transaction_dao.dart' as _i25;
import 'package:pos_app/data/daos/sales/tax_config_dao.dart' as _i24;
import 'package:pos_app/data/daos/security_profile_dao.dart' as _i9;
import 'package:pos_app/data/daos/user_dao.dart' as _i8;
import 'package:pos_app/data/database/app_database.dart' as _i40;
import 'package:pos_app/data/models/inventory/batch_entity.dart' as _i37;
import 'package:pos_app/data/models/inventory/insumo_entity.dart' as _i31;
import 'package:pos_app/data/models/inventory/movement_entity.dart' as _i33;
import 'package:pos_app/data/models/inventory/purchase_entity.dart' as _i38;
import 'package:pos_app/data/models/inventory/recipe_entity.dart' as _i32;
import 'package:pos_app/data/models/inventory/supplier_entity.dart' as _i34;
import 'package:pos_app/data/models/inventory/uom_conversion_entity.dart'
    as _i36;
import 'package:pos_app/data/models/inventory/warehouse_entity.dart' as _i35;
import 'package:sqflite/sqflite.dart' as _i30;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDao_6 extends _i1.SmartFake implements _i8.UserDao {
  _FakeUserDao_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityProfileDao_7 extends _i1.SmartFake
    implements _i9.SecurityProfileDao {
  _FakeSecurityProfileDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditDao_8 extends _i1.SmartFake implements _i10.AuditDao {
  _FakeAuditDao_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalConfigDao_9 extends _i1.SmartFake
    implements _i11.LocalConfigDao {
  _FakeLocalConfigDao_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsumoDao_10 extends _i1.SmartFake implements _i12.InsumoDao {
  _FakeInsumoDao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductDao_11 extends _i1.SmartFake implements _i13.ProductDao {
  _FakeProductDao_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeDao_12 extends _i1.SmartFake implements _i13.RecipeDao {
  _FakeRecipeDao_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementDao_13 extends _i1.SmartFake implements _i14.MovementDao {
  _FakeMovementDao_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventoryDao_14 extends _i1.SmartFake implements _i15.InventoryDao {
  _FakeInventoryDao_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplierDao_15 extends _i1.SmartFake implements _i16.SupplierDao {
  _FakeSupplierDao_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWarehouseDao_16 extends _i1.SmartFake implements _i17.WarehouseDao {
  _FakeWarehouseDao_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseDao_17 extends _i1.SmartFake implements _i18.PurchaseDao {
  _FakePurchaseDao_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUomConversionDao_18 extends _i1.SmartFake
    implements _i19.UomConversionDao {
  _FakeUomConversionDao_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchDao_19 extends _i1.SmartFake implements _i20.BatchDao {
  _FakeBatchDao_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDao_20 extends _i1.SmartFake implements _i21.InvoiceDao {
  _FakeInvoiceDao_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceItemDao_21 extends _i1.SmartFake
    implements _i22.InvoiceItemDao {
  _FakeInvoiceItemDao_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentDao_22 extends _i1.SmartFake implements _i23.PaymentDao {
  _FakePaymentDao_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaxConfigDao_23 extends _i1.SmartFake implements _i24.TaxConfigDao {
  _FakeTaxConfigDao_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesTransactionDao_24 extends _i1.SmartFake
    implements _i25.SalesTransactionDao {
  _FakeSalesTransactionDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashierSessionDao_25 extends _i1.SmartFake
    implements _i26.CashierSessionDao {
  _FakeCashierSessionDao_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHoldTicketDao_26 extends _i1.SmartFake
    implements _i27.HoldTicketDao {
  _FakeHoldTicketDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromotionDao_27 extends _i1.SmartFake implements _i28.PromotionDao {
  _FakePromotionDao_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_28<T> extends _i1.SmartFake
    implements _i29.StreamController<T> {
  _FakeStreamController_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseExecutor_29 extends _i1.SmartFake
    implements _i30.DatabaseExecutor {
  _FakeDatabaseExecutor_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InsumoDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsumoDao extends _i1.Mock implements _i12.InsumoDao {
  MockInsumoDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i31.InsumoEntity>> findAllActiveInsumos() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllActiveInsumos,
          [],
        ),
        returnValue:
            _i29.Future<List<_i31.InsumoEntity>>.value(<_i31.InsumoEntity>[]),
      ) as _i29.Future<List<_i31.InsumoEntity>>);

  @override
  _i29.Future<_i31.InsumoEntity?> findInsumoById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInsumoById,
          [id],
        ),
        returnValue: _i29.Future<_i31.InsumoEntity?>.value(),
      ) as _i29.Future<_i31.InsumoEntity?>);

  @override
  _i29.Future<List<_i31.InsumoEntity>> findInsumosByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInsumosByIds,
          [ids],
        ),
        returnValue:
            _i29.Future<List<_i31.InsumoEntity>>.value(<_i31.InsumoEntity>[]),
      ) as _i29.Future<List<_i31.InsumoEntity>>);

  @override
  _i29.Future<void> insertInsumos(List<_i31.InsumoEntity>? insumos) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInsumos,
          [insumos],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateInsumo(_i31.InsumoEntity? insumo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumo,
          [insumo],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateStock(
    String? id,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            id,
            newStock,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [RecipeDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeDao extends _i1.Mock implements _i13.RecipeDao {
  MockRecipeDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i32.RecipeEntity>> findRecipeByProductId(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findRecipeByProductId,
          [productId],
        ),
        returnValue:
            _i29.Future<List<_i32.RecipeEntity>>.value(<_i32.RecipeEntity>[]),
      ) as _i29.Future<List<_i32.RecipeEntity>>);

  @override
  _i29.Future<void> insertRecipes(List<_i32.RecipeEntity>? recipes) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertRecipes,
          [recipes],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> deleteRecipeById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipeById,
          [id],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [MovementDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovementDao extends _i1.Mock implements _i14.MovementDao {
  MockMovementDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i33.MovementEntity>> findAllMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllMovements,
          [],
        ),
        returnValue: _i29.Future<List<_i33.MovementEntity>>.value(
            <_i33.MovementEntity>[]),
      ) as _i29.Future<List<_i33.MovementEntity>>);

  @override
  _i29.Future<List<_i33.MovementEntity>> findUnsyncedMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #findUnsyncedMovements,
          [],
        ),
        returnValue: _i29.Future<List<_i33.MovementEntity>>.value(
            <_i33.MovementEntity>[]),
      ) as _i29.Future<List<_i33.MovementEntity>>);

  @override
  _i29.Future<void> insertMovement(_i33.MovementEntity? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMovement,
          [movement],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<_i33.MovementEntity>> findMovementsByType(
    String? type,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMovementsByType,
          [
            type,
            limit,
          ],
        ),
        returnValue: _i29.Future<List<_i33.MovementEntity>>.value(
            <_i33.MovementEntity>[]),
      ) as _i29.Future<List<_i33.MovementEntity>>);

  @override
  _i29.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> markAsFailed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsFailed,
          [id],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [SupplierDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplierDao extends _i1.Mock implements _i16.SupplierDao {
  MockSupplierDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i34.SupplierEntity>> findAllActiveSuppliers() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllActiveSuppliers,
          [],
        ),
        returnValue: _i29.Future<List<_i34.SupplierEntity>>.value(
            <_i34.SupplierEntity>[]),
      ) as _i29.Future<List<_i34.SupplierEntity>>);

  @override
  _i29.Future<_i34.SupplierEntity?> findSupplierById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findSupplierById,
          [id],
        ),
        returnValue: _i29.Future<_i34.SupplierEntity?>.value(),
      ) as _i29.Future<_i34.SupplierEntity?>);

  @override
  _i29.Future<void> insertSuppliers(List<_i34.SupplierEntity>? suppliers) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSuppliers,
          [suppliers],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateSupplier(_i34.SupplierEntity? supplier) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSupplier,
          [supplier],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [WarehouseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWarehouseDao extends _i1.Mock implements _i17.WarehouseDao {
  MockWarehouseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i35.WarehouseEntity>> findAllActiveWarehouses() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllActiveWarehouses,
          [],
        ),
        returnValue: _i29.Future<List<_i35.WarehouseEntity>>.value(
            <_i35.WarehouseEntity>[]),
      ) as _i29.Future<List<_i35.WarehouseEntity>>);

  @override
  _i29.Future<_i35.WarehouseEntity?> findWarehouseById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWarehouseById,
          [id],
        ),
        returnValue: _i29.Future<_i35.WarehouseEntity?>.value(),
      ) as _i29.Future<_i35.WarehouseEntity?>);

  @override
  _i29.Future<void> insertWarehouses(List<_i35.WarehouseEntity>? warehouses) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWarehouses,
          [warehouses],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateWarehouse(_i35.WarehouseEntity? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWarehouse,
          [warehouse],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [UomConversionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUomConversionDao extends _i1.Mock implements _i19.UomConversionDao {
  MockUomConversionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i36.UomConversionEntity>> findConversionsByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findConversionsByInsumoId,
          [insumoId],
        ),
        returnValue: _i29.Future<List<_i36.UomConversionEntity>>.value(
            <_i36.UomConversionEntity>[]),
      ) as _i29.Future<List<_i36.UomConversionEntity>>);

  @override
  _i29.Future<void> insertConversions(
          List<_i36.UomConversionEntity>? conversions) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertConversions,
          [conversions],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [BatchDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatchDao extends _i1.Mock implements _i20.BatchDao {
  MockBatchDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<List<_i37.BatchEntity>> findActiveBatchesByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findActiveBatchesByInsumoId,
          [insumoId],
        ),
        returnValue:
            _i29.Future<List<_i37.BatchEntity>>.value(<_i37.BatchEntity>[]),
      ) as _i29.Future<List<_i37.BatchEntity>>);

  @override
  _i29.Future<void> insertBatch(_i37.BatchEntity? batch) => (super.noSuchMethod(
        Invocation.method(
          #insertBatch,
          [batch],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateBatch(_i37.BatchEntity? batch) => (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [batch],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [PurchaseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseDao extends _i1.Mock implements _i18.PurchaseDao {
  MockPurchaseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.Future<void> insertPurchase(_i38.PurchaseEntity? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPurchase,
          [purchase],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<_i38.PurchaseEntity>> findUnsyncedPurchases() =>
      (super.noSuchMethod(
        Invocation.method(
          #findUnsyncedPurchases,
          [],
        ),
        returnValue: _i29.Future<List<_i38.PurchaseEntity>>.value(
            <_i38.PurchaseEntity>[]),
      ) as _i29.Future<List<_i38.PurchaseEntity>>);

  @override
  _i29.Future<List<_i38.PurchaseEntity>> findAllPurchases() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllPurchases,
          [],
        ),
        returnValue: _i29.Future<List<_i38.PurchaseEntity>>.value(
            <_i38.PurchaseEntity>[]),
      ) as _i29.Future<List<_i38.PurchaseEntity>>);

  @override
  _i29.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i4.Transformer);

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i39.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i39.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i29.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<dynamic>>);

  @override
  _i29.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i39.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i29.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<dynamic>>);

  @override
  _i29.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i39.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i39.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i29.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i29.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i29.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_5(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i7.Dio);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i40.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.UserDao get userDao => (super.noSuchMethod(
        Invocation.getter(#userDao),
        returnValue: _FakeUserDao_6(
          this,
          Invocation.getter(#userDao),
        ),
      ) as _i8.UserDao);

  @override
  _i9.SecurityProfileDao get securityProfileDao => (super.noSuchMethod(
        Invocation.getter(#securityProfileDao),
        returnValue: _FakeSecurityProfileDao_7(
          this,
          Invocation.getter(#securityProfileDao),
        ),
      ) as _i9.SecurityProfileDao);

  @override
  _i10.AuditDao get auditDao => (super.noSuchMethod(
        Invocation.getter(#auditDao),
        returnValue: _FakeAuditDao_8(
          this,
          Invocation.getter(#auditDao),
        ),
      ) as _i10.AuditDao);

  @override
  _i11.LocalConfigDao get localConfigDao => (super.noSuchMethod(
        Invocation.getter(#localConfigDao),
        returnValue: _FakeLocalConfigDao_9(
          this,
          Invocation.getter(#localConfigDao),
        ),
      ) as _i11.LocalConfigDao);

  @override
  _i12.InsumoDao get insumoDao => (super.noSuchMethod(
        Invocation.getter(#insumoDao),
        returnValue: _FakeInsumoDao_10(
          this,
          Invocation.getter(#insumoDao),
        ),
      ) as _i12.InsumoDao);

  @override
  _i13.ProductDao get productDao => (super.noSuchMethod(
        Invocation.getter(#productDao),
        returnValue: _FakeProductDao_11(
          this,
          Invocation.getter(#productDao),
        ),
      ) as _i13.ProductDao);

  @override
  _i13.RecipeDao get recipeDao => (super.noSuchMethod(
        Invocation.getter(#recipeDao),
        returnValue: _FakeRecipeDao_12(
          this,
          Invocation.getter(#recipeDao),
        ),
      ) as _i13.RecipeDao);

  @override
  _i14.MovementDao get movementDao => (super.noSuchMethod(
        Invocation.getter(#movementDao),
        returnValue: _FakeMovementDao_13(
          this,
          Invocation.getter(#movementDao),
        ),
      ) as _i14.MovementDao);

  @override
  _i15.InventoryDao get inventoryDao => (super.noSuchMethod(
        Invocation.getter(#inventoryDao),
        returnValue: _FakeInventoryDao_14(
          this,
          Invocation.getter(#inventoryDao),
        ),
      ) as _i15.InventoryDao);

  @override
  _i16.SupplierDao get supplierDao => (super.noSuchMethod(
        Invocation.getter(#supplierDao),
        returnValue: _FakeSupplierDao_15(
          this,
          Invocation.getter(#supplierDao),
        ),
      ) as _i16.SupplierDao);

  @override
  _i17.WarehouseDao get warehouseDao => (super.noSuchMethod(
        Invocation.getter(#warehouseDao),
        returnValue: _FakeWarehouseDao_16(
          this,
          Invocation.getter(#warehouseDao),
        ),
      ) as _i17.WarehouseDao);

  @override
  _i18.PurchaseDao get purchaseDao => (super.noSuchMethod(
        Invocation.getter(#purchaseDao),
        returnValue: _FakePurchaseDao_17(
          this,
          Invocation.getter(#purchaseDao),
        ),
      ) as _i18.PurchaseDao);

  @override
  _i19.UomConversionDao get uomConversionDao => (super.noSuchMethod(
        Invocation.getter(#uomConversionDao),
        returnValue: _FakeUomConversionDao_18(
          this,
          Invocation.getter(#uomConversionDao),
        ),
      ) as _i19.UomConversionDao);

  @override
  _i20.BatchDao get batchDao => (super.noSuchMethod(
        Invocation.getter(#batchDao),
        returnValue: _FakeBatchDao_19(
          this,
          Invocation.getter(#batchDao),
        ),
      ) as _i20.BatchDao);

  @override
  _i21.InvoiceDao get invoiceDao => (super.noSuchMethod(
        Invocation.getter(#invoiceDao),
        returnValue: _FakeInvoiceDao_20(
          this,
          Invocation.getter(#invoiceDao),
        ),
      ) as _i21.InvoiceDao);

  @override
  _i22.InvoiceItemDao get invoiceItemDao => (super.noSuchMethod(
        Invocation.getter(#invoiceItemDao),
        returnValue: _FakeInvoiceItemDao_21(
          this,
          Invocation.getter(#invoiceItemDao),
        ),
      ) as _i22.InvoiceItemDao);

  @override
  _i23.PaymentDao get paymentDao => (super.noSuchMethod(
        Invocation.getter(#paymentDao),
        returnValue: _FakePaymentDao_22(
          this,
          Invocation.getter(#paymentDao),
        ),
      ) as _i23.PaymentDao);

  @override
  _i24.TaxConfigDao get taxConfigDao => (super.noSuchMethod(
        Invocation.getter(#taxConfigDao),
        returnValue: _FakeTaxConfigDao_23(
          this,
          Invocation.getter(#taxConfigDao),
        ),
      ) as _i24.TaxConfigDao);

  @override
  _i25.SalesTransactionDao get salesTransactionDao => (super.noSuchMethod(
        Invocation.getter(#salesTransactionDao),
        returnValue: _FakeSalesTransactionDao_24(
          this,
          Invocation.getter(#salesTransactionDao),
        ),
      ) as _i25.SalesTransactionDao);

  @override
  _i26.CashierSessionDao get cashierSessionDao => (super.noSuchMethod(
        Invocation.getter(#cashierSessionDao),
        returnValue: _FakeCashierSessionDao_25(
          this,
          Invocation.getter(#cashierSessionDao),
        ),
      ) as _i26.CashierSessionDao);

  @override
  _i27.HoldTicketDao get holdTicketDao => (super.noSuchMethod(
        Invocation.getter(#holdTicketDao),
        returnValue: _FakeHoldTicketDao_26(
          this,
          Invocation.getter(#holdTicketDao),
        ),
      ) as _i27.HoldTicketDao);

  @override
  _i28.PromotionDao get promotionDao => (super.noSuchMethod(
        Invocation.getter(#promotionDao),
        returnValue: _FakePromotionDao_27(
          this,
          Invocation.getter(#promotionDao),
        ),
      ) as _i28.PromotionDao);

  @override
  _i29.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_28<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i29.StreamController<String>);

  @override
  set changeListener(_i29.StreamController<String>? _changeListener) =>
      super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          _changeListener,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i30.DatabaseExecutor get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseExecutor_29(
          this,
          Invocation.getter(#database),
        ),
      ) as _i30.DatabaseExecutor);

  @override
  set database(_i30.DatabaseExecutor? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}
