// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/ui/features/sales/multi_currency_checkout_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pos_app/data/daos/sales/sales_transaction_dao.dart' as _i29;
import 'package:pos_app/data/database/app_database.dart' as _i3;
import 'package:pos_app/data/models/audit_log_entity.dart' as _i36;
import 'package:pos_app/data/models/fulfillment/fulfillment_persistence_entities.dart'
    as _i37;
import 'package:pos_app/data/models/inventory/insumo_entity.dart' as _i34;
import 'package:pos_app/data/models/inventory/kardex_correction_entity.dart'
    as _i24;
import 'package:pos_app/data/models/inventory/kardex_recalculate_queue_entity.dart'
    as _i25;
import 'package:pos_app/data/models/inventory/movement_entity.dart' as _i35;
import 'package:pos_app/data/models/sales/invoice_entity.dart' as _i30;
import 'package:pos_app/data/models/sales/invoice_item_entity.dart' as _i31;
import 'package:pos_app/data/models/sales/invoice_item_modifier_entity.dart'
    as _i32;
import 'package:pos_app/data/models/sales/payment_entity.dart' as _i33;
import 'package:pos_app/domain/models/audit_log.dart' as _i7;
import 'package:pos_app/domain/models/catalog/catalog_type.dart' as _i20;
import 'package:pos_app/domain/models/catalog/catalog_value.dart' as _i19;
import 'package:pos_app/domain/models/inventory/batch.dart' as _i17;
import 'package:pos_app/domain/models/inventory/batch_deduction.dart' as _i39;
import 'package:pos_app/domain/models/inventory/count_session_document.dart'
    as _i13;
import 'package:pos_app/domain/models/inventory/forensic_alert.dart' as _i22;
import 'package:pos_app/domain/models/inventory/insumo.dart' as _i9;
import 'package:pos_app/domain/models/inventory/inventory_movement.dart'
    as _i14;
import 'package:pos_app/domain/models/inventory/product.dart' as _i10;
import 'package:pos_app/domain/models/inventory/production_order_document.dart'
    as _i23;
import 'package:pos_app/domain/models/inventory/purchase.dart' as _i21;
import 'package:pos_app/domain/models/inventory/recipe.dart' as _i11;
import 'package:pos_app/domain/models/inventory/recipe_version_document.dart'
    as _i12;
import 'package:pos_app/domain/models/inventory/supplier.dart' as _i15;
import 'package:pos_app/domain/models/inventory/uom_conversion.dart' as _i18;
import 'package:pos_app/domain/models/inventory/warehouse.dart' as _i16;
import 'package:pos_app/domain/models/sales/invoice_item.dart' as _i27;
import 'package:pos_app/domain/models/user.dart' as _i41;
import 'package:pos_app/domain/repositories/audit_repository.dart' as _i2;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i40;
import 'package:pos_app/domain/repositories/inventory/inventory_repository.dart'
    as _i8;
import 'package:pos_app/domain/services/inventory/movement_engine.dart' as _i4;
import 'package:pos_app/domain/services/sales/dgi_numbering_service.dart'
    as _i38;
import 'package:pos_app/domain/usecases/inventory/process_sale_inventory_use_case.dart'
    as _i26;
import 'package:pos_app/domain/usecases/inventory/reverse_sale_inventory_use_case.dart'
    as _i28;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuditSyncOutcome_0 extends _i1.SmartFake
    implements _i2.AuditSyncOutcome {
  _FakeAuditSyncOutcome_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDatabase_1 extends _i1.SmartFake implements _i3.AppDatabase {
  _FakeAppDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementEngine_2 extends _i1.SmartFake
    implements _i4.MovementEngine {
  _FakeMovementEngine_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionCloseResult_3 extends _i1.SmartFake
    implements _i4.ProductionCloseResult {
  _FakeProductionCloseResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuditRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditRepository extends _i1.Mock implements _i2.AuditRepository {
  MockAuditRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get deviceId => (super.noSuchMethod(
        Invocation.getter(#deviceId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#deviceId),
        ),
      ) as String);

  @override
  _i6.Future<void> log(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #log,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.AuditLog?> prepareLog(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareLog,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i6.Future<_i7.AuditLog?>.value(),
      ) as _i6.Future<_i7.AuditLog?>);

  @override
  _i6.Future<void> logForensic(
    String? action, {
    String? metadata,
    String? metodoAutorizacion,
    String? usuarioAutorizadorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logForensic,
          [action],
          {
            #metadata: metadata,
            #metodoAutorizacion: metodoAutorizacion,
            #usuarioAutorizadorId: usuarioAutorizadorId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.AuditSyncOutcome> syncLogs() => (super.noSuchMethod(
        Invocation.method(
          #syncLogs,
          [],
        ),
        returnValue:
            _i6.Future<_i2.AuditSyncOutcome>.value(_FakeAuditSyncOutcome_0(
          this,
          Invocation.method(
            #syncLogs,
            [],
          ),
        )),
      ) as _i6.Future<_i2.AuditSyncOutcome>);

  @override
  _i6.Future<List<_i7.AuditLog>> getLocalLogs({
    DateTime? start,
    DateTime? end,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalLogs,
          [],
          {
            #start: start,
            #end: end,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<List<_i7.AuditLog>>.value(<_i7.AuditLog>[]),
      ) as _i6.Future<List<_i7.AuditLog>>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i8.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_1(
          this,
          Invocation.getter(#database),
        ),
      ) as _i3.AppDatabase);

  @override
  _i6.Future<List<_i9.Insumo>> getActiveInsumos() => (super.noSuchMethod(
        Invocation.method(
          #getActiveInsumos,
          [],
        ),
        returnValue: _i6.Future<List<_i9.Insumo>>.value(<_i9.Insumo>[]),
      ) as _i6.Future<List<_i9.Insumo>>);

  @override
  _i6.Future<_i9.Insumo?> getInsumoById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsumoById,
          [id],
        ),
        returnValue: _i6.Future<_i9.Insumo?>.value(),
      ) as _i6.Future<_i9.Insumo?>);

  @override
  _i6.Future<List<_i9.Insumo>> getInsumosByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsumosByIds,
          [ids],
        ),
        returnValue: _i6.Future<List<_i9.Insumo>>.value(<_i9.Insumo>[]),
      ) as _i6.Future<List<_i9.Insumo>>);

  @override
  _i6.Future<void> updateInsumoStock(
    String? id,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoStock,
          [
            id,
            newStock,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateInsumoCost(
    String? id,
    double? newCost,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoCost,
          [
            id,
            newCost,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveInsumo(_i9.Insumo? insumo) => (super.noSuchMethod(
        Invocation.method(
          #saveInsumo,
          [insumo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.Product>> getActiveProducts() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProducts,
          [],
        ),
        returnValue: _i6.Future<List<_i10.Product>>.value(<_i10.Product>[]),
      ) as _i6.Future<List<_i10.Product>>);

  @override
  _i6.Future<_i10.Product?> getProductById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i6.Future<_i10.Product?>.value(),
      ) as _i6.Future<_i10.Product?>);

  @override
  _i6.Future<void> saveProduct(_i10.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #saveProduct,
          [product],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveProductOptions({
    required String? productId,
    required List<_i10.ProductVariant>? variants,
    required List<_i10.Modifier>? modifiers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductOptions,
          [],
          {
            #productId: productId,
            #variants: variants,
            #modifiers: modifiers,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.Recipe>> getRecipeByProductId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeByProductId,
          [productId],
        ),
        returnValue: _i6.Future<List<_i11.Recipe>>.value(<_i11.Recipe>[]),
      ) as _i6.Future<List<_i11.Recipe>>);

  @override
  _i6.Future<void> saveRecipe(_i11.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [recipe],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> replaceRecipesForProduct(
    String? productId,
    List<_i11.Recipe>? recipes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceRecipesForProduct,
          [
            productId,
            recipes,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.RecipeVersionDocument>> getRecipeVersionDocuments(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocuments,
          [productId],
        ),
        returnValue: _i6.Future<List<_i12.RecipeVersionDocument>>.value(
            <_i12.RecipeVersionDocument>[]),
      ) as _i6.Future<List<_i12.RecipeVersionDocument>>);

  @override
  _i6.Future<String?> getActiveRecipeVersionId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecipeVersionId,
          [productId],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i12.RecipeVersionDocument?> getRecipeVersionDocumentById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocumentById,
          [id],
        ),
        returnValue: _i6.Future<_i12.RecipeVersionDocument?>.value(),
      ) as _i6.Future<_i12.RecipeVersionDocument?>);

  @override
  _i6.Future<void> saveRecipeVersionDocument(
          _i12.RecipeVersionDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipeVersionDocument,
          [document],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.RecipeVersionDocument>>
      getUnsyncedRecipeVersionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedRecipeVersionDocuments,
              [],
            ),
            returnValue: _i6.Future<List<_i12.RecipeVersionDocument>>.value(
                <_i12.RecipeVersionDocument>[]),
          ) as _i6.Future<List<_i12.RecipeVersionDocument>>);

  @override
  _i6.Future<void> markRecipeVersionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecipeVersionDocumentAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.CountSessionDocument>> getCountSessionDocuments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountSessionDocuments,
          [],
        ),
        returnValue: _i6.Future<List<_i13.CountSessionDocument>>.value(
            <_i13.CountSessionDocument>[]),
      ) as _i6.Future<List<_i13.CountSessionDocument>>);

  @override
  _i6.Future<void> saveCountSessionDocument(
          _i13.CountSessionDocument? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCountSessionDocument,
          [session],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.CountSessionDocument>>
      getUnsyncedCountSessionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedCountSessionDocuments,
              [],
            ),
            returnValue: _i6.Future<List<_i13.CountSessionDocument>>.value(
                <_i13.CountSessionDocument>[]),
          ) as _i6.Future<List<_i13.CountSessionDocument>>);

  @override
  _i6.Future<void> markCountSessionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markCountSessionDocumentAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveMovement(_i14.InventoryMovement? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMovement,
          [movement],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.InventoryMovement>> getAllMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMovements,
          [],
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);

  @override
  _i6.Future<List<_i14.InventoryMovement>> getUnsyncedMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMovements,
          [],
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);

  @override
  _i6.Future<void> markMovementAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMovementAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markMovementAsFailed(
    String? id, {
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMovementAsFailed,
          [id],
          {#error: error},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i15.Supplier>> getActiveSuppliers() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSuppliers,
          [],
        ),
        returnValue: _i6.Future<List<_i15.Supplier>>.value(<_i15.Supplier>[]),
      ) as _i6.Future<List<_i15.Supplier>>);

  @override
  _i6.Future<void> saveSupplier(_i15.Supplier? supplier) => (super.noSuchMethod(
        Invocation.method(
          #saveSupplier,
          [supplier],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i16.Warehouse>> getActiveWarehouses() => (super.noSuchMethod(
        Invocation.method(
          #getActiveWarehouses,
          [],
        ),
        returnValue: _i6.Future<List<_i16.Warehouse>>.value(<_i16.Warehouse>[]),
      ) as _i6.Future<List<_i16.Warehouse>>);

  @override
  _i6.Future<void> saveWarehouse(_i16.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWarehouse,
          [warehouse],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i17.Batch>> getBatchesByInsumoId(String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchesByInsumoId,
          [insumoId],
        ),
        returnValue: _i6.Future<List<_i17.Batch>>.value(<_i17.Batch>[]),
      ) as _i6.Future<List<_i17.Batch>>);

  @override
  _i6.Future<void> saveBatch(_i17.Batch? batch) => (super.noSuchMethod(
        Invocation.method(
          #saveBatch,
          [batch],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i18.UomConversion>> getConversionsByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversionsByInsumoId,
          [insumoId],
        ),
        returnValue:
            _i6.Future<List<_i18.UomConversion>>.value(<_i18.UomConversion>[]),
      ) as _i6.Future<List<_i18.UomConversion>>);

  @override
  _i6.Future<void> saveConversion(_i18.UomConversion? conversion) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversion,
          [conversion],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConversion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConversion,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i19.CatalogValue>> getActiveCatalog(
          _i20.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCatalog,
          [type],
        ),
        returnValue:
            _i6.Future<List<_i19.CatalogValue>>.value(<_i19.CatalogValue>[]),
      ) as _i6.Future<List<_i19.CatalogValue>>);

  @override
  _i6.Future<List<_i19.CatalogValue>> getAllCatalog(_i20.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCatalog,
          [type],
        ),
        returnValue:
            _i6.Future<List<_i19.CatalogValue>>.value(<_i19.CatalogValue>[]),
      ) as _i6.Future<List<_i19.CatalogValue>>);

  @override
  _i6.Future<_i19.CatalogValue?> findCatalogByCode(
    _i20.CatalogType? type,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCatalogByCode,
          [
            type,
            code,
          ],
        ),
        returnValue: _i6.Future<_i19.CatalogValue?>.value(),
      ) as _i6.Future<_i19.CatalogValue?>);

  @override
  _i6.Future<void> upsertCatalogValues(List<_i19.CatalogValue>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertCatalogValues,
          [values],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setCatalogActive(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCatalogActive,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> countCatalogValues() => (super.noSuchMethod(
        Invocation.method(
          #countCatalogValues,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> savePurchase(_i21.Purchase? purchase) => (super.noSuchMethod(
        Invocation.method(
          #savePurchase,
          [purchase],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> queuePurchaseSync(_i21.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #queuePurchaseSync,
          [purchase],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i21.Purchase>> getPurchaseHistory() => (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
        ),
        returnValue: _i6.Future<List<_i21.Purchase>>.value(<_i21.Purchase>[]),
      ) as _i6.Future<List<_i21.Purchase>>);

  @override
  _i6.Future<List<_i21.Purchase>> getUnsyncedPurchases() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPurchases,
          [],
        ),
        returnValue: _i6.Future<List<_i21.Purchase>>.value(<_i21.Purchase>[]),
      ) as _i6.Future<List<_i21.Purchase>>);

  @override
  _i6.Future<void> markPurchaseAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markPurchaseAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<double> fetchOfficialBcnRateByInvoiceDate(DateTime? invoiceDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOfficialBcnRateByInvoiceDate,
          [invoiceDate],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<double> getCachedOfficialBcnRate() => (super.noSuchMethod(
        Invocation.method(
          #getCachedOfficialBcnRate,
          [],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<List<_i22.ForensicAlert>> getForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getForensicAlerts,
          [],
        ),
        returnValue:
            _i6.Future<List<_i22.ForensicAlert>>.value(<_i22.ForensicAlert>[]),
      ) as _i6.Future<List<_i22.ForensicAlert>>);

  @override
  _i6.Future<void> saveForensicAlert(_i22.ForensicAlert? alert) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveForensicAlert,
          [alert],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i22.ForensicAlert>> getUnsyncedForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedForensicAlerts,
          [],
        ),
        returnValue:
            _i6.Future<List<_i22.ForensicAlert>>.value(<_i22.ForensicAlert>[]),
      ) as _i6.Future<List<_i22.ForensicAlert>>);

  @override
  _i6.Future<void> markForensicAlertAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markForensicAlertAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i23.ProductionOrderDocument>>
      getProductionOrderDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getProductionOrderDocuments,
              [],
            ),
            returnValue: _i6.Future<List<_i23.ProductionOrderDocument>>.value(
                <_i23.ProductionOrderDocument>[]),
          ) as _i6.Future<List<_i23.ProductionOrderDocument>>);

  @override
  _i6.Future<int> reserveProductionSourceSequence(String? terminalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reserveProductionSourceSequence,
          [terminalId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> saveProductionOrderDocument(
          _i23.ProductionOrderDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionOrderDocument,
          [document],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveProductionCloseTransaction(
    _i23.ProductionOrderDocument? document,
    List<_i14.InventoryMovement>? movements, {
    bool? debugFailAfterWrites = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionCloseTransaction,
          [
            document,
            movements,
          ],
          {#debugFailAfterWrites: debugFailAfterWrites},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i23.ProductionOrderDocument>>
      getUnsyncedProductionOrders() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedProductionOrders,
              [],
            ),
            returnValue: _i6.Future<List<_i23.ProductionOrderDocument>>.value(
                <_i23.ProductionOrderDocument>[]),
          ) as _i6.Future<List<_i23.ProductionOrderDocument>>);

  @override
  _i6.Future<void> markProductionOrderDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markProductionOrderDocumentAsSynced,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i24.KardexCorrectionEntity>> getKardexCorrections() =>
      (super.noSuchMethod(
        Invocation.method(
          #getKardexCorrections,
          [],
        ),
        returnValue: _i6.Future<List<_i24.KardexCorrectionEntity>>.value(
            <_i24.KardexCorrectionEntity>[]),
      ) as _i6.Future<List<_i24.KardexCorrectionEntity>>);

  @override
  _i6.Future<List<_i25.KardexRecalculateQueueEntity>> getPendingKardexQueue() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingKardexQueue,
          [],
        ),
        returnValue: _i6.Future<List<_i25.KardexRecalculateQueueEntity>>.value(
            <_i25.KardexRecalculateQueueEntity>[]),
      ) as _i6.Future<List<_i25.KardexRecalculateQueueEntity>>);
}

/// A class which mocks [ProcessSaleInventoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessSaleInventoryUseCase extends _i1.Mock
    implements _i26.ProcessSaleInventoryUseCase {
  MockProcessSaleInventoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovementEngine get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeMovementEngine_2(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i4.MovementEngine);

  @override
  _i6.Future<List<_i14.InventoryMovement>> execute(
          List<_i27.InvoiceItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [items],
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);
}

/// A class which mocks [ReverseSaleInventoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReverseSaleInventoryUseCase extends _i1.Mock
    implements _i28.ReverseSaleInventoryUseCase {
  MockReverseSaleInventoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovementEngine get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeMovementEngine_2(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i4.MovementEngine);

  @override
  _i6.Future<List<_i14.InventoryMovement>> execute(
    List<_i27.InvoiceItem>? items,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            items,
            reason,
          ],
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);
}

/// A class which mocks [SalesTransactionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesTransactionDao extends _i1.Mock
    implements _i29.SalesTransactionDao {
  MockSalesTransactionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> insertInvoice(_i30.InvoiceEntity? invoice) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInvoice,
          [invoice],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateInvoice(_i30.InvoiceEntity? invoice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInvoice,
          [invoice],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertInvoiceItems(List<_i31.InvoiceItemEntity>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInvoiceItems,
          [items],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertInvoiceItemModifiers(
          List<_i32.InvoiceItemModifierEntity>? modifiers) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInvoiceItemModifiers,
          [modifiers],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertPayments(List<_i33.PaymentEntity>? payments) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPayments,
          [payments],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i34.InsumoEntity?> getInsumoById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsumoById,
          [id],
        ),
        returnValue: _i6.Future<_i34.InsumoEntity?>.value(),
      ) as _i6.Future<_i34.InsumoEntity?>);

  @override
  _i6.Future<void> updateInsumo(_i34.InsumoEntity? insumo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumo,
          [insumo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertMovement(_i35.MovementEntity? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMovement,
          [movement],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertAuditLog(_i36.AuditLogEntity? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditLog,
          [log],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i30.InvoiceEntity?> getInvoiceById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i6.Future<_i30.InvoiceEntity?>.value(),
      ) as _i6.Future<_i30.InvoiceEntity?>);

  @override
  _i6.Future<List<_i30.InvoiceEntity>> getCreditNotesByRelatedId(
          String? relatedId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCreditNotesByRelatedId,
          [relatedId],
        ),
        returnValue:
            _i6.Future<List<_i30.InvoiceEntity>>.value(<_i30.InvoiceEntity>[]),
      ) as _i6.Future<List<_i30.InvoiceEntity>>);

  @override
  _i6.Future<int?> getNextInvoiceSourceSequence(String? terminalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextInvoiceSourceSequence,
          [terminalId],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<void> advanceDgiCurrentNumber(String? nextSequence) =>
      (super.noSuchMethod(
        Invocation.method(
          #advanceDgiCurrentNumber,
          [nextSequence],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getDgiConfig(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDgiConfig,
          [key],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getOriginalMovementId(
    String? invoiceId,
    String? insumoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOriginalMovementId,
          [
            invoiceId,
            insumoId,
          ],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i37.OutboxEventEntity?> findReplay(
    String? tenantId,
    String? idempotencyKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findReplay,
          [
            tenantId,
            idempotencyKey,
          ],
        ),
        returnValue: _i6.Future<_i37.OutboxEventEntity?>.value(),
      ) as _i6.Future<_i37.OutboxEventEntity?>);

  @override
  _i6.Future<void> executeSaleTransaction(
    _i30.InvoiceEntity? invoice,
    List<_i31.InvoiceItemEntity>? items,
    List<_i32.InvoiceItemModifierEntity>? modifiers,
    List<_i33.PaymentEntity>? payments,
    List<_i35.MovementEntity>? movements,
    _i36.AuditLogEntity? auditLog,
    bool? shouldFail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeSaleTransaction,
          [
            invoice,
            items,
            modifiers,
            payments,
            movements,
            auditLog,
            shouldFail,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> executeSaleWithDgiTransaction(
    _i30.InvoiceEntity? invoice,
    List<_i31.InvoiceItemEntity>? items,
    List<_i32.InvoiceItemModifierEntity>? modifiers,
    List<_i33.PaymentEntity>? payments,
    List<_i35.MovementEntity>? movements,
    _i36.AuditLogEntity? auditLog,
    String? nextDgiSequence,
    bool? shouldFail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeSaleWithDgiTransaction,
          [
            invoice,
            items,
            modifiers,
            payments,
            movements,
            auditLog,
            nextDgiSequence,
            shouldFail,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> executeFulfillmentSaleTransaction(
    _i30.InvoiceEntity? invoice,
    List<_i31.InvoiceItemEntity>? items,
    List<_i32.InvoiceItemModifierEntity>? modifiers,
    List<_i33.PaymentEntity>? payments,
    List<_i35.MovementEntity>? movements,
    _i36.AuditLogEntity? auditLog,
    _i37.FulfillmentRecordEntity? fulfillment,
    List<_i37.PrintJobEntity>? printJobs,
    _i37.OutboxEventEntity? outbox,
    bool? shouldFail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeFulfillmentSaleTransaction,
          [
            invoice,
            items,
            modifiers,
            payments,
            movements,
            auditLog,
            fulfillment,
            printJobs,
            outbox,
            shouldFail,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertFulfillment(
          _i37.FulfillmentRecordEntity? fulfillment) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFulfillment,
          [fulfillment],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertPrintJob(_i37.PrintJobEntity? job) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPrintJob,
          [job],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertOutboxEvent(_i37.OutboxEventEntity? outbox) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOutboxEvent,
          [outbox],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> executeVoidTransaction(
    List<_i35.MovementEntity>? movements,
    _i30.InvoiceEntity? canceledInvoice,
    _i36.AuditLogEntity? auditLog,
    bool? shouldFail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeVoidTransaction,
          [
            movements,
            canceledInvoice,
            auditLog,
            shouldFail,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [DgiNumberingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDgiNumberingService extends _i1.Mock
    implements _i38.DgiNumberingService {
  MockDgiNumberingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initializeRange({
    required String? prefix,
    required int? start,
    required int? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeRange,
          [],
          {
            #prefix: prefix,
            #start: start,
            #end: end,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> getNextNumber() => (super.noSuchMethod(
        Invocation.method(
          #getNextNumber,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getNextNumber,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> incrementNumber() => (super.noSuchMethod(
        Invocation.method(
          #incrementNumber,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isRangeExhausted() => (super.noSuchMethod(
        Invocation.method(
          #isRangeExhausted,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [MovementEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovementEngine extends _i1.Mock implements _i4.MovementEngine {
  MockMovementEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> recordSale(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordSale,
          [
            productId,
            quantity,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordPurchase(
    String? insumoId,
    double? quantity,
    double? cost, {
    String? movementId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordPurchase,
          [
            insumoId,
            quantity,
            cost,
          ],
          {
            #movementId: movementId,
            #reason: reason,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordShrinkage(
    String? insumoId,
    double? quantity,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordShrinkage,
          [
            insumoId,
            quantity,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordProductShrinkage({
    required String? productId,
    required double? quantity,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductShrinkage,
          [],
          {
            #productId: productId,
            #quantity: quantity,
            #reason: reason,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.InventoryMovement>> recordProduction({
    required String? recipeProductId,
    required String? producedInsumoId,
    required double? quantity,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProduction,
          [],
          {
            #recipeProductId: recipeProductId,
            #producedInsumoId: producedInsumoId,
            #quantity: quantity,
            #reason: reason,
          },
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);

  @override
  _i6.Future<_i4.ProductionCloseResult> recordProductionClose({
    required String? recipeProductId,
    required String? producedInsumoId,
    required String? productionDocumentId,
    String? recipeVersionId,
    required double? plannedQuantity,
    required double? actualQuantity,
    required String? outcome,
    required String? reason,
    Map<String, double>? customIngredientConsumptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProductionClose,
          [],
          {
            #recipeProductId: recipeProductId,
            #producedInsumoId: producedInsumoId,
            #productionDocumentId: productionDocumentId,
            #recipeVersionId: recipeVersionId,
            #plannedQuantity: plannedQuantity,
            #actualQuantity: actualQuantity,
            #outcome: outcome,
            #reason: reason,
            #customIngredientConsumptions: customIngredientConsumptions,
          },
        ),
        returnValue: _i6.Future<_i4.ProductionCloseResult>.value(
            _FakeProductionCloseResult_3(
          this,
          Invocation.method(
            #recordProductionClose,
            [],
            {
              #recipeProductId: recipeProductId,
              #producedInsumoId: producedInsumoId,
              #productionDocumentId: productionDocumentId,
              #recipeVersionId: recipeVersionId,
              #plannedQuantity: plannedQuantity,
              #actualQuantity: actualQuantity,
              #outcome: outcome,
              #reason: reason,
              #customIngredientConsumptions: customIngredientConsumptions,
            },
          ),
        )),
      ) as _i6.Future<_i4.ProductionCloseResult>);

  @override
  _i6.Future<_i4.ProductionCloseResult> buildProductionClose({
    required String? recipeProductId,
    required String? producedInsumoId,
    required String? productionDocumentId,
    String? recipeVersionId,
    required double? plannedQuantity,
    required double? actualQuantity,
    required String? outcome,
    required String? reason,
    Map<String, double>? customIngredientConsumptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildProductionClose,
          [],
          {
            #recipeProductId: recipeProductId,
            #producedInsumoId: producedInsumoId,
            #productionDocumentId: productionDocumentId,
            #recipeVersionId: recipeVersionId,
            #plannedQuantity: plannedQuantity,
            #actualQuantity: actualQuantity,
            #outcome: outcome,
            #reason: reason,
            #customIngredientConsumptions: customIngredientConsumptions,
          },
        ),
        returnValue: _i6.Future<_i4.ProductionCloseResult>.value(
            _FakeProductionCloseResult_3(
          this,
          Invocation.method(
            #buildProductionClose,
            [],
            {
              #recipeProductId: recipeProductId,
              #producedInsumoId: producedInsumoId,
              #productionDocumentId: productionDocumentId,
              #recipeVersionId: recipeVersionId,
              #plannedQuantity: plannedQuantity,
              #actualQuantity: actualQuantity,
              #outcome: outcome,
              #reason: reason,
              #customIngredientConsumptions: customIngredientConsumptions,
            },
          ),
        )),
      ) as _i6.Future<_i4.ProductionCloseResult>);

  @override
  _i6.Future<void> recordAdjustment(
    String? insumoId,
    double? quantityDelta,
    String? reason, {
    String? movementId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordAdjustment,
          [
            insumoId,
            quantityDelta,
            reason,
          ],
          {#movementId: movementId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordReversal(
    String? productId,
    int? quantity,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordReversal,
          [
            productId,
            quantity,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.InventoryMovement>> getSaleMovements(
    String? productId,
    double? quantity, {
    String? recipeVersionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSaleMovements,
          [
            productId,
            quantity,
          ],
          {#recipeVersionId: recipeVersionId},
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);

  @override
  _i6.Future<List<_i14.InventoryMovement>> getReversalMovements(
    String? productId,
    double? quantity,
    String? reason, {
    String? recipeVersionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReversalMovements,
          [
            productId,
            quantity,
            reason,
          ],
          {#recipeVersionId: recipeVersionId},
        ),
        returnValue: _i6.Future<List<_i14.InventoryMovement>>.value(
            <_i14.InventoryMovement>[]),
      ) as _i6.Future<List<_i14.InventoryMovement>>);

  @override
  _i6.Future<List<_i39.BatchDeduction>> getBatchesForConsumption(
    String? insumoId,
    double? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchesForConsumption,
          [
            insumoId,
            quantity,
          ],
        ),
        returnValue: _i6.Future<List<_i39.BatchDeduction>>.value(
            <_i39.BatchDeduction>[]),
      ) as _i6.Future<List<_i39.BatchDeduction>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i40.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i41.User?> loginOnline(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i41.User?>.value(),
      ) as _i6.Future<_i41.User?>);

  @override
  _i6.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i41.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i6.Future<_i41.User?>.value(),
      ) as _i6.Future<_i41.User?>);

  @override
  _i6.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i41.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i41.User?>.value(),
      ) as _i6.Future<_i41.User?>);

  @override
  _i6.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i41.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i6.Future<List<_i41.User>>.value(<_i41.User>[]),
      ) as _i6.Future<List<_i41.User>>);

  @override
  _i6.Future<void> saveUser(
    _i41.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
