// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/ui/features/sales/multi_currency_checkout_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pos_app/domain/models/inventory/product.dart' as _i4;
import 'package:pos_app/domain/models/sales/cart_item.dart' as _i3;
import 'package:pos_app/domain/models/sales/cashier_session.dart' as _i10;
import 'package:pos_app/domain/models/sales/hold_ticket.dart' as _i6;
import 'package:pos_app/domain/models/sales/payment.dart' as _i7;
import 'package:pos_app/domain/models/sales/promotion.dart' as _i5;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart'
    as _i11;
import 'package:pos_app/presentation/features/sales/view_models/sale_view_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SaleViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaleViewModel extends _i1.Mock implements _i2.SaleViewModel {
  MockSaleViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get commercialRate => (super.noSuchMethod(
        Invocation.getter(#commercialRate),
        returnValue: 0.0,
      ) as double);

  @override
  double get bcnOfficialRate => (super.noSuchMethod(
        Invocation.getter(#bcnOfficialRate),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i3.CartItem> get cart => (super.noSuchMethod(
        Invocation.getter(#cart),
        returnValue: <_i3.CartItem>[],
      ) as List<_i3.CartItem>);

  @override
  List<_i4.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  List<_i5.Promotion> get promotions => (super.noSuchMethod(
        Invocation.getter(#promotions),
        returnValue: <_i5.Promotion>[],
      ) as List<_i5.Promotion>);

  @override
  List<_i6.HoldTicket> get holdTickets => (super.noSuchMethod(
        Invocation.getter(#holdTickets),
        returnValue: <_i6.HoldTicket>[],
      ) as List<_i6.HoldTicket>);

  @override
  Map<_i7.PaymentMethod, double> get sessionExpected => (super.noSuchMethod(
        Invocation.getter(#sessionExpected),
        returnValue: <_i7.PaymentMethod, double>{},
      ) as Map<_i7.PaymentMethod, double>);

  @override
  bool get isGlobalTaxExempt => (super.noSuchMethod(
        Invocation.getter(#isGlobalTaxExempt),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get canManageCashDrawer => (super.noSuchMethod(
        Invocation.getter(#canManageCashDrawer),
        returnValue: false,
      ) as bool);

  @override
  bool get canVoidInvoice => (super.noSuchMethod(
        Invocation.getter(#canVoidInvoice),
        returnValue: false,
      ) as bool);

  @override
  bool get isSupervisorOverrideActive => (super.noSuchMethod(
        Invocation.getter(#isSupervisorOverrideActive),
        returnValue: false,
      ) as bool);

  @override
  double get subtotal => (super.noSuchMethod(
        Invocation.getter(#subtotal),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalDiscounts => (super.noSuchMethod(
        Invocation.getter(#totalDiscounts),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalTax => (super.noSuchMethod(
        Invocation.getter(#totalTax),
        returnValue: 0.0,
      ) as double);

  @override
  double get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i4.Product> get filteredProducts => (super.noSuchMethod(
        Invocation.getter(#filteredProducts),
        returnValue: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> loadExchangeRates() => (super.noSuchMethod(
        Invocation.method(
          #loadExchangeRates,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void grantSupervisorOverride() => super.noSuchMethod(
        Invocation.method(
          #grantSupervisorOverride,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyManualDiscount(double? discountAmount) => super.noSuchMethod(
        Invocation.method(
          #applyManualDiscount,
          [discountAmount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> loadPromotions() => (super.noSuchMethod(
        Invocation.method(
          #loadPromotions,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> searchAndAddToCart(String? code) => (super.noSuchMethod(
        Invocation.method(
          #searchAndAddToCart,
          [code],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> loadHoldTickets() => (super.noSuchMethod(
        Invocation.method(
          #loadHoldTickets,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> holdCurrentTicket(
    String? name, {
    String? tableId,
    String? areaId,
    String? waiterId,
    String? waiterName,
    int? guestCount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #holdCurrentTicket,
          [name],
          {
            #tableId: tableId,
            #areaId: areaId,
            #waiterId: waiterId,
            #waiterName: waiterName,
            #guestCount: guestCount,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> recallTicket(_i6.HoldTicket? ticket) => (super.noSuchMethod(
        Invocation.method(
          #recallTicket,
          [ticket],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void cancelLoadedHoldTicket() => super.noSuchMethod(
        Invocation.method(
          #cancelLoadedHoldTicket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> checkActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #checkActiveSession,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openSession(
    double? balance, {
    _i10.CashSessionModel? tipoModelo = _i10.CashSessionModel.cajaCentral,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSession,
          [balance],
          {#tipoModelo: tipoModelo},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> closeSession(double? closingBalance) => (super.noSuchMethod(
        Invocation.method(
          #closeSession,
          [closingBalance],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addToCart(
    _i4.Product? product, {
    double? quantity = 1.0,
    String? variantId,
    List<_i4.Modifier>? modifiers = const [],
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [product],
          {
            #quantity: quantity,
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCart(
    String? productId, {
    String? variantId,
    List<_i4.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeFromCart,
          [productId],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateQuantity(
    String? productId,
    double? quantity, {
    String? variantId,
    List<_i4.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            productId,
            quantity,
          ],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleGlobalTaxExempt() => super.noSuchMethod(
        Invocation.method(
          #toggleGlobalTaxExempt,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCart() => super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> finalizeSale(List<_i7.PaymentMethod>? methods) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeSale,
          [methods],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> processSale(
    List<_i7.PaymentMethod>? methods, {
    List<_i7.Payment>? customPayments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSale,
          [methods],
          {#customPayments: customPayments},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> processReturn(
    String? invoiceNumber,
    String? reason, {
    _i11.RefundReasonPolicy? refundReasonPolicy =
        _i11.RefundReasonPolicy.restockOriginalBom,
    List<_i11.CreditNoteRefundLine>? lines,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processReturn,
          [
            invoiceNumber,
            reason,
          ],
          {
            #refundReasonPolicy: refundReasonPolicy,
            #lines: lines,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> voidInvoice(
    String? invoiceId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reason,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
