// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/ui/features/sales/sale_view_security_flows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pos_app/data/services/sync_service.dart' as _i18;
import 'package:pos_app/domain/models/audit_log.dart' as _i17;
import 'package:pos_app/domain/models/config/tenant_operation_mode.dart' as _i3;
import 'package:pos_app/domain/models/inventory/product.dart' as _i5;
import 'package:pos_app/domain/models/sales/cart_item.dart' as _i4;
import 'package:pos_app/domain/models/sales/cashier_session.dart' as _i11;
import 'package:pos_app/domain/models/sales/hold_ticket.dart' as _i7;
import 'package:pos_app/domain/models/sales/payment.dart' as _i8;
import 'package:pos_app/domain/models/sales/promotion.dart' as _i6;
import 'package:pos_app/domain/models/user.dart' as _i15;
import 'package:pos_app/domain/repositories/audit_repository.dart' as _i16;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i14;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart'
    as _i12;
import 'package:pos_app/presentation/features/sales/view_models/sale_view_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaleViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaleViewModel extends _i1.Mock implements _i2.SaleViewModel {
  @override
  _i3.TenantOperationMode get operationMode => (super.noSuchMethod(
        Invocation.getter(#operationMode),
        returnValue: _i3.TenantOperationMode.foodparkQsr,
        returnValueForMissingStub: _i3.TenantOperationMode.foodparkQsr,
      ) as _i3.TenantOperationMode);

  @override
  bool get isFoodParkQsr => (super.noSuchMethod(
        Invocation.getter(#isFoodParkQsr),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get supportsTables => (super.noSuchMethod(
        Invocation.getter(#supportsTables),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get supportsBuzzerPager => (super.noSuchMethod(
        Invocation.getter(#supportsBuzzerPager),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get commercialRate => (super.noSuchMethod(
        Invocation.getter(#commercialRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get bcnOfficialRate => (super.noSuchMethod(
        Invocation.getter(#bcnOfficialRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  List<_i4.CartItem> get cart => (super.noSuchMethod(
        Invocation.getter(#cart),
        returnValue: <_i4.CartItem>[],
        returnValueForMissingStub: <_i4.CartItem>[],
      ) as List<_i4.CartItem>);

  @override
  List<_i5.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i5.Product>[],
        returnValueForMissingStub: <_i5.Product>[],
      ) as List<_i5.Product>);

  @override
  List<_i6.Promotion> get promotions => (super.noSuchMethod(
        Invocation.getter(#promotions),
        returnValue: <_i6.Promotion>[],
        returnValueForMissingStub: <_i6.Promotion>[],
      ) as List<_i6.Promotion>);

  @override
  List<_i7.HoldTicket> get holdTickets => (super.noSuchMethod(
        Invocation.getter(#holdTickets),
        returnValue: <_i7.HoldTicket>[],
        returnValueForMissingStub: <_i7.HoldTicket>[],
      ) as List<_i7.HoldTicket>);

  @override
  Map<_i8.PaymentMethod, double> get sessionExpected => (super.noSuchMethod(
        Invocation.getter(#sessionExpected),
        returnValue: <_i8.PaymentMethod, double>{},
        returnValueForMissingStub: <_i8.PaymentMethod, double>{},
      ) as Map<_i8.PaymentMethod, double>);

  @override
  bool get isGlobalTaxExempt => (super.noSuchMethod(
        Invocation.getter(#isGlobalTaxExempt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get canManageCashDrawer => (super.noSuchMethod(
        Invocation.getter(#canManageCashDrawer),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canVoidInvoice => (super.noSuchMethod(
        Invocation.getter(#canVoidInvoice),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSupervisorOverrideActive => (super.noSuchMethod(
        Invocation.getter(#isSupervisorOverrideActive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get subtotal => (super.noSuchMethod(
        Invocation.getter(#subtotal),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalDiscounts => (super.noSuchMethod(
        Invocation.getter(#totalDiscounts),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalTax => (super.noSuchMethod(
        Invocation.getter(#totalTax),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  List<_i5.Product> get filteredProducts => (super.noSuchMethod(
        Invocation.getter(#filteredProducts),
        returnValue: <_i5.Product>[],
        returnValueForMissingStub: <_i5.Product>[],
      ) as List<_i5.Product>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setBuzzerNumber(String? number) => super.noSuchMethod(
        Invocation.method(
          #setBuzzerNumber,
          [number],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCustomerName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setCustomerName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> loadTenantConfig() => (super.noSuchMethod(
        Invocation.method(
          #loadTenantConfig,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadExchangeRates() => (super.noSuchMethod(
        Invocation.method(
          #loadExchangeRates,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void grantSupervisorOverride() => super.noSuchMethod(
        Invocation.method(
          #grantSupervisorOverride,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyManualDiscount(double? discountAmount) => super.noSuchMethod(
        Invocation.method(
          #applyManualDiscount,
          [discountAmount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> loadPromotions() => (super.noSuchMethod(
        Invocation.method(
          #loadPromotions,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> searchAndAddToCart(String? code) => (super.noSuchMethod(
        Invocation.method(
          #searchAndAddToCart,
          [code],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadHoldTickets() => (super.noSuchMethod(
        Invocation.method(
          #loadHoldTickets,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> holdCurrentTicket(
    String? name, {
    String? tableId,
    String? areaId,
    String? waiterId,
    String? waiterName,
    int? guestCount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #holdCurrentTicket,
          [name],
          {
            #tableId: tableId,
            #areaId: areaId,
            #waiterId: waiterId,
            #waiterName: waiterName,
            #guestCount: guestCount,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> recallTicket(_i7.HoldTicket? ticket) => (super.noSuchMethod(
        Invocation.method(
          #recallTicket,
          [ticket],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void cancelLoadedHoldTicket() => super.noSuchMethod(
        Invocation.method(
          #cancelLoadedHoldTicket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> checkActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #checkActiveSession,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openSession(
    double? balance, {
    _i11.CashSessionModel? tipoModelo = _i11.CashSessionModel.cajaCentral,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSession,
          [balance],
          {#tipoModelo: tipoModelo},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> closeSession(double? closingBalance) => (super.noSuchMethod(
        Invocation.method(
          #closeSession,
          [closingBalance],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addToCart(
    _i5.Product? product, {
    double? quantity = 1.0,
    String? variantId,
    List<_i5.Modifier>? modifiers = const [],
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [product],
          {
            #quantity: quantity,
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCart(
    String? productId, {
    String? variantId,
    List<_i5.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeFromCart,
          [productId],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateQuantity(
    String? productId,
    double? quantity, {
    String? variantId,
    List<_i5.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            productId,
            quantity,
          ],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleGlobalTaxExempt() => super.noSuchMethod(
        Invocation.method(
          #toggleGlobalTaxExempt,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCart() => super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> finalizeSale(List<_i8.PaymentMethod>? methods) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeSale,
          [methods],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> processSale(
    List<_i8.PaymentMethod>? methods, {
    List<_i8.Payment>? customPayments,
    String? buzzerNumber,
    String? customerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSale,
          [methods],
          {
            #customPayments: customPayments,
            #buzzerNumber: buzzerNumber,
            #customerName: customerName,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> reprintLastInvoice() => (super.noSuchMethod(
        Invocation.method(
          #reprintLastInvoice,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> processReturn(
    String? invoiceNumber,
    String? reason, {
    _i12.RefundReasonPolicy? refundReasonPolicy =
        _i12.RefundReasonPolicy.restockOriginalBom,
    List<_i12.CreditNoteRefundLine>? lines,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processReturn,
          [
            invoiceNumber,
            reason,
          ],
          {
            #refundReasonPolicy: refundReasonPolicy,
            #lines: lines,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> voidInvoice(
    String? invoiceId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reason,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i14.AuthRepository {
  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<_i15.User?> loginOnline(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
        ),
        returnValue: _i10.Future<_i15.User?>.value(),
        returnValueForMissingStub: _i10.Future<_i15.User?>.value(),
      ) as _i10.Future<_i15.User?>);

  @override
  _i10.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i15.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i10.Future<_i15.User?>.value(),
        returnValueForMissingStub: _i10.Future<_i15.User?>.value(),
      ) as _i10.Future<_i15.User?>);

  @override
  _i10.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i15.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i10.Future<_i15.User?>.value(),
        returnValueForMissingStub: _i10.Future<_i15.User?>.value(),
      ) as _i10.Future<_i15.User?>);

  @override
  _i10.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i15.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i10.Future<List<_i15.User>>.value(<_i15.User>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i15.User>>.value(<_i15.User>[]),
      ) as _i10.Future<List<_i15.User>>);

  @override
  _i10.Future<void> saveUser(
    _i15.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AuditRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditRepository extends _i1.Mock implements _i16.AuditRepository {
  @override
  String get deviceId => (super.noSuchMethod(
        Invocation.getter(#deviceId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#deviceId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#deviceId),
        ),
      ) as String);

  @override
  _i10.Future<void> log(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #log,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i17.AuditLog?> prepareLog(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareLog,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i10.Future<_i17.AuditLog?>.value(),
        returnValueForMissingStub: _i10.Future<_i17.AuditLog?>.value(),
      ) as _i10.Future<_i17.AuditLog?>);

  @override
  _i10.Future<void> logForensic(
    String? action, {
    String? metadata,
    String? metodoAutorizacion,
    String? usuarioAutorizadorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logForensic,
          [action],
          {
            #metadata: metadata,
            #metodoAutorizacion: metodoAutorizacion,
            #usuarioAutorizadorId: usuarioAutorizadorId,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> syncLogs() => (super.noSuchMethod(
        Invocation.method(
          #syncLogs,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i17.AuditLog>> getLocalLogs({
    DateTime? start,
    DateTime? end,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalLogs,
          [],
          {
            #start: start,
            #end: end,
            #userId: userId,
          },
        ),
        returnValue: _i10.Future<List<_i17.AuditLog>>.value(<_i17.AuditLog>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i17.AuditLog>>.value(<_i17.AuditLog>[]),
      ) as _i10.Future<List<_i17.AuditLog>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i18.SyncService {
  @override
  _i10.Stream<_i18.InboundSyncResult> get onInboundSync => (super.noSuchMethod(
        Invocation.getter(#onInboundSync),
        returnValue: _i10.Stream<_i18.InboundSyncResult>.empty(),
        returnValueForMissingStub: _i10.Stream<_i18.InboundSyncResult>.empty(),
      ) as _i10.Stream<_i18.InboundSyncResult>);

  @override
  _i10.Stream<_i18.CloudSyncStatus> get onStatusChanged => (super.noSuchMethod(
        Invocation.getter(#onStatusChanged),
        returnValue: _i10.Stream<_i18.CloudSyncStatus>.empty(),
        returnValueForMissingStub: _i10.Stream<_i18.CloudSyncStatus>.empty(),
      ) as _i10.Stream<_i18.CloudSyncStatus>);

  @override
  _i18.CloudSyncStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i18.CloudSyncStatus.idle,
        returnValueForMissingStub: _i18.CloudSyncStatus.idle,
      ) as _i18.CloudSyncStatus);

  @override
  int get consecutiveFailures => (super.noSuchMethod(
        Invocation.getter(#consecutiveFailures),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration getNextBackoffDelay() => (super.noSuchMethod(
        Invocation.method(
          #getNextBackoffDelay,
          [],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getNextBackoffDelay,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.method(
            #getNextBackoffDelay,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i10.Future<int> getPendingOutboxCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingOutboxCount,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
        returnValueForMissingStub: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> triggerManualSync() => (super.noSuchMethod(
        Invocation.method(
          #triggerManualSync,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  Map<String, Object> buildOrderedBatchEnvelopeForTest(
          List<dynamic>? unsynced) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildOrderedBatchEnvelopeForTest,
          [unsynced],
        ),
        returnValue: <String, Object>{},
        returnValueForMissingStub: <String, Object>{},
      ) as Map<String, Object>);

  @override
  _i10.Future<_i18.InboundSyncResult?> pullInboundDeltas() =>
      (super.noSuchMethod(
        Invocation.method(
          #pullInboundDeltas,
          [],
        ),
        returnValue: _i10.Future<_i18.InboundSyncResult?>.value(),
        returnValueForMissingStub: _i10.Future<_i18.InboundSyncResult?>.value(),
      ) as _i10.Future<_i18.InboundSyncResult?>);
}
