// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/ui/features/sales/sales_history_void_action_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i54;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_app/data/daos/activation/activation_attempt_local_dao.dart'
    as _i45;
import 'package:pos_app/data/daos/activation/activation_check_result_local_dao.dart'
    as _i46;
import 'package:pos_app/data/daos/activation/activation_outbox_dao.dart'
    as _i49;
import 'package:pos_app/data/daos/activation/first_customer_sale_observation_dao.dart'
    as _i48;
import 'package:pos_app/data/daos/activation/first_successful_sale_claim_dao.dart'
    as _i47;
import 'package:pos_app/data/daos/audit_log_dao.dart' as _i7;
import 'package:pos_app/data/daos/catalog/catalog_value_dao.dart' as _i27;
import 'package:pos_app/data/daos/customer/customer_dao.dart' as _i40;
import 'package:pos_app/data/daos/customer/customer_point_transaction_dao.dart'
    as _i41;
import 'package:pos_app/data/daos/fiscal_config_local_dao.dart' as _i44;
import 'package:pos_app/data/daos/fulfillment/fulfillment_persistence_dao.dart'
    as _i52;
import 'package:pos_app/data/daos/fulfillment/fulfillment_topology_dao.dart'
    as _i51;
import 'package:pos_app/data/daos/human_authorization/ohac_delivery_dao.dart'
    as _i53;
import 'package:pos_app/data/daos/inventory/authority_projection_dao.dart'
    as _i50;
import 'package:pos_app/data/daos/inventory/batch_dao.dart' as _i26;
import 'package:pos_app/data/daos/inventory/count_line_dao.dart' as _i13;
import 'package:pos_app/data/daos/inventory/count_session_dao.dart' as _i12;
import 'package:pos_app/data/daos/inventory/forensic_alert_dao.dart' as _i14;
import 'package:pos_app/data/daos/inventory/insumo_dao.dart' as _i9;
import 'package:pos_app/data/daos/inventory/inventory_dao.dart' as _i19;
import 'package:pos_app/data/daos/inventory/kardex_correction_dao.dart' as _i18;
import 'package:pos_app/data/daos/inventory/kardex_recalculate_queue_dao.dart'
    as _i17;
import 'package:pos_app/data/daos/inventory/movement_dao.dart' as _i15;
import 'package:pos_app/data/daos/inventory/movement_sync_state_dao.dart'
    as _i16;
import 'package:pos_app/data/daos/inventory/production_order_document_dao.dart'
    as _i23;
import 'package:pos_app/data/daos/inventory/production_transaction_dao.dart'
    as _i24;
import 'package:pos_app/data/daos/inventory/purchase_dao.dart' as _i22;
import 'package:pos_app/data/daos/inventory/recipe_dao.dart' as _i10;
import 'package:pos_app/data/daos/inventory/recipe_version_document_dao.dart'
    as _i11;
import 'package:pos_app/data/daos/inventory/supplier_dao.dart' as _i20;
import 'package:pos_app/data/daos/inventory/uom_conversion_dao.dart' as _i25;
import 'package:pos_app/data/daos/inventory/warehouse_dao.dart' as _i21;
import 'package:pos_app/data/daos/kitchen/kitchen_order_dao.dart' as _i39;
import 'package:pos_app/data/daos/local_config_dao.dart' as _i8;
import 'package:pos_app/data/daos/loyalty/loyalty_program_dao.dart' as _i42;
import 'package:pos_app/data/daos/loyalty/loyalty_reward_dao.dart' as _i43;
import 'package:pos_app/data/daos/sales/cash_movement_dao.dart' as _i34;
import 'package:pos_app/data/daos/sales/cashier_session_dao.dart' as _i33;
import 'package:pos_app/data/daos/sales/hold_ticket_dao.dart' as _i35;
import 'package:pos_app/data/daos/sales/invoice_dao.dart' as _i28;
import 'package:pos_app/data/daos/sales/invoice_item_dao.dart' as _i29;
import 'package:pos_app/data/daos/sales/payment_dao.dart' as _i30;
import 'package:pos_app/data/daos/sales/promotion_dao.dart' as _i36;
import 'package:pos_app/data/daos/sales/restaurant_area_dao.dart' as _i37;
import 'package:pos_app/data/daos/sales/restaurant_table_dao.dart' as _i38;
import 'package:pos_app/data/daos/sales/sales_transaction_dao.dart' as _i32;
import 'package:pos_app/data/daos/sales/tax_config_dao.dart' as _i31;
import 'package:pos_app/data/daos/security_profile_dao.dart' as _i6;
import 'package:pos_app/data/daos/user_dao.dart' as _i5;
import 'package:pos_app/data/database/app_database.dart' as _i3;
import 'package:pos_app/data/models/inventory/kardex_correction_entity.dart'
    as _i77;
import 'package:pos_app/data/models/inventory/kardex_recalculate_queue_entity.dart'
    as _i78;
import 'package:pos_app/data/models/sales/cashier_session_entity.dart' as _i80;
import 'package:pos_app/data/models/sales/hold_ticket_entity.dart' as _i84;
import 'package:pos_app/data/models/sales/invoice_entity.dart' as _i81;
import 'package:pos_app/data/models/sales/invoice_item_entity.dart' as _i82;
import 'package:pos_app/data/models/sales/payment_entity.dart' as _i83;
import 'package:pos_app/data/models/sales/promotion_entity.dart' as _i85;
import 'package:pos_app/domain/models/auth/terminal_linking.dart' as _i4;
import 'package:pos_app/domain/models/catalog/catalog_type.dart' as _i73;
import 'package:pos_app/domain/models/catalog/catalog_value.dart' as _i72;
import 'package:pos_app/domain/models/fulfillment/fulfillment_checkout_context.dart'
    as _i59;
import 'package:pos_app/domain/models/inventory/batch.dart' as _i70;
import 'package:pos_app/domain/models/inventory/count_session_document.dart'
    as _i66;
import 'package:pos_app/domain/models/inventory/forensic_alert.dart' as _i75;
import 'package:pos_app/domain/models/inventory/insumo.dart' as _i62;
import 'package:pos_app/domain/models/inventory/inventory_movement.dart'
    as _i67;
import 'package:pos_app/domain/models/inventory/product.dart' as _i63;
import 'package:pos_app/domain/models/inventory/production_order_document.dart'
    as _i76;
import 'package:pos_app/domain/models/inventory/purchase.dart' as _i74;
import 'package:pos_app/domain/models/inventory/recipe.dart' as _i64;
import 'package:pos_app/domain/models/inventory/recipe_version_document.dart'
    as _i65;
import 'package:pos_app/domain/models/inventory/supplier.dart' as _i68;
import 'package:pos_app/domain/models/inventory/uom_conversion.dart' as _i71;
import 'package:pos_app/domain/models/inventory/warehouse.dart' as _i69;
import 'package:pos_app/domain/models/sales/invoice.dart' as _i56;
import 'package:pos_app/domain/models/sales/invoice_item.dart' as _i57;
import 'package:pos_app/domain/models/sales/payment.dart' as _i58;
import 'package:pos_app/domain/models/user.dart' as _i60;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i79;
import 'package:pos_app/domain/repositories/inventory/inventory_repository.dart'
    as _i61;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart' as _i2;
import 'package:sqflite/sqflite.dart' as _i55;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReprintPreparation_0 extends _i1.SmartFake
    implements _i2.ReprintPreparation {
  _FakeReprintPreparation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDatabase_1 extends _i1.SmartFake implements _i3.AppDatabase {
  _FakeAppDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTerminalLinking_2 extends _i1.SmartFake
    implements _i4.TerminalLinking {
  _FakeTerminalLinking_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDao_3 extends _i1.SmartFake implements _i5.UserDao {
  _FakeUserDao_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityProfileDao_4 extends _i1.SmartFake
    implements _i6.SecurityProfileDao {
  _FakeSecurityProfileDao_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditDao_5 extends _i1.SmartFake implements _i7.AuditDao {
  _FakeAuditDao_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalConfigDao_6 extends _i1.SmartFake
    implements _i8.LocalConfigDao {
  _FakeLocalConfigDao_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsumoDao_7 extends _i1.SmartFake implements _i9.InsumoDao {
  _FakeInsumoDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductDao_8 extends _i1.SmartFake implements _i10.ProductDao {
  _FakeProductDao_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeDao_9 extends _i1.SmartFake implements _i10.RecipeDao {
  _FakeRecipeDao_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeVersionDocumentDao_10 extends _i1.SmartFake
    implements _i11.RecipeVersionDocumentDao {
  _FakeRecipeVersionDocumentDao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountSessionDao_11 extends _i1.SmartFake
    implements _i12.CountSessionDao {
  _FakeCountSessionDao_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountLineDao_12 extends _i1.SmartFake implements _i13.CountLineDao {
  _FakeCountLineDao_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForensicAlertDao_13 extends _i1.SmartFake
    implements _i14.ForensicAlertDao {
  _FakeForensicAlertDao_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementDao_14 extends _i1.SmartFake implements _i15.MovementDao {
  _FakeMovementDao_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovementSyncStateDao_15 extends _i1.SmartFake
    implements _i16.MovementSyncStateDao {
  _FakeMovementSyncStateDao_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKardexRecalculateQueueDao_16 extends _i1.SmartFake
    implements _i17.KardexRecalculateQueueDao {
  _FakeKardexRecalculateQueueDao_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKardexCorrectionDao_17 extends _i1.SmartFake
    implements _i18.KardexCorrectionDao {
  _FakeKardexCorrectionDao_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventoryDao_18 extends _i1.SmartFake implements _i19.InventoryDao {
  _FakeInventoryDao_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplierDao_19 extends _i1.SmartFake implements _i20.SupplierDao {
  _FakeSupplierDao_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWarehouseDao_20 extends _i1.SmartFake implements _i21.WarehouseDao {
  _FakeWarehouseDao_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchaseDao_21 extends _i1.SmartFake implements _i22.PurchaseDao {
  _FakePurchaseDao_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionOrderDocumentDao_22 extends _i1.SmartFake
    implements _i23.ProductionOrderDocumentDao {
  _FakeProductionOrderDocumentDao_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionTransactionDao_23 extends _i1.SmartFake
    implements _i24.ProductionTransactionDao {
  _FakeProductionTransactionDao_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUomConversionDao_24 extends _i1.SmartFake
    implements _i25.UomConversionDao {
  _FakeUomConversionDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchDao_25 extends _i1.SmartFake implements _i26.BatchDao {
  _FakeBatchDao_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalogValueDao_26 extends _i1.SmartFake
    implements _i27.CatalogValueDao {
  _FakeCatalogValueDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDao_27 extends _i1.SmartFake implements _i28.InvoiceDao {
  _FakeInvoiceDao_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceItemDao_28 extends _i1.SmartFake
    implements _i29.InvoiceItemDao {
  _FakeInvoiceItemDao_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentDao_29 extends _i1.SmartFake implements _i30.PaymentDao {
  _FakePaymentDao_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaxConfigDao_30 extends _i1.SmartFake implements _i31.TaxConfigDao {
  _FakeTaxConfigDao_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesTransactionDao_31 extends _i1.SmartFake
    implements _i32.SalesTransactionDao {
  _FakeSalesTransactionDao_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashierSessionDao_32 extends _i1.SmartFake
    implements _i33.CashierSessionDao {
  _FakeCashierSessionDao_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashMovementDao_33 extends _i1.SmartFake
    implements _i34.CashMovementDao {
  _FakeCashMovementDao_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHoldTicketDao_34 extends _i1.SmartFake
    implements _i35.HoldTicketDao {
  _FakeHoldTicketDao_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromotionDao_35 extends _i1.SmartFake implements _i36.PromotionDao {
  _FakePromotionDao_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantAreaDao_36 extends _i1.SmartFake
    implements _i37.RestaurantAreaDao {
  _FakeRestaurantAreaDao_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantTableDao_37 extends _i1.SmartFake
    implements _i38.RestaurantTableDao {
  _FakeRestaurantTableDao_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenOrderDao_38 extends _i1.SmartFake
    implements _i39.KitchenOrderDao {
  _FakeKitchenOrderDao_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerDao_39 extends _i1.SmartFake implements _i40.CustomerDao {
  _FakeCustomerDao_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerPointTransactionDao_40 extends _i1.SmartFake
    implements _i41.CustomerPointTransactionDao {
  _FakeCustomerPointTransactionDao_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoyaltyProgramDao_41 extends _i1.SmartFake
    implements _i42.LoyaltyProgramDao {
  _FakeLoyaltyProgramDao_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoyaltyRewardDao_42 extends _i1.SmartFake
    implements _i43.LoyaltyRewardDao {
  _FakeLoyaltyRewardDao_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFiscalConfigLocalDao_43 extends _i1.SmartFake
    implements _i44.FiscalConfigLocalDao {
  _FakeFiscalConfigLocalDao_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivationAttemptLocalDao_44 extends _i1.SmartFake
    implements _i45.ActivationAttemptLocalDao {
  _FakeActivationAttemptLocalDao_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivationCheckResultLocalDao_45 extends _i1.SmartFake
    implements _i46.ActivationCheckResultLocalDao {
  _FakeActivationCheckResultLocalDao_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirstSuccessfulSaleClaimDao_46 extends _i1.SmartFake
    implements _i47.FirstSuccessfulSaleClaimDao {
  _FakeFirstSuccessfulSaleClaimDao_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirstCustomerSaleObservationDao_47 extends _i1.SmartFake
    implements _i48.FirstCustomerSaleObservationDao {
  _FakeFirstCustomerSaleObservationDao_47(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivationOutboxDao_48 extends _i1.SmartFake
    implements _i49.ActivationOutboxDao {
  _FakeActivationOutboxDao_48(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthorityProjectionDao_49 extends _i1.SmartFake
    implements _i50.AuthorityProjectionDao {
  _FakeAuthorityProjectionDao_49(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFulfillmentTopologyDao_50 extends _i1.SmartFake
    implements _i51.FulfillmentTopologyDao {
  _FakeFulfillmentTopologyDao_50(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFulfillmentPersistenceDao_51 extends _i1.SmartFake
    implements _i52.FulfillmentPersistenceDao {
  _FakeFulfillmentPersistenceDao_51(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOhacDeliveryDao_52 extends _i1.SmartFake
    implements _i53.OhacDeliveryDao {
  _FakeOhacDeliveryDao_52(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_53<T> extends _i1.SmartFake
    implements _i54.StreamController<T> {
  _FakeStreamController_53(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseExecutor_54 extends _i1.SmartFake
    implements _i55.DatabaseExecutor {
  _FakeDatabaseExecutor_54(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SalesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesRepository extends _i1.Mock implements _i2.SalesRepository {
  MockSalesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<void> saveSale({
    required _i56.Invoice? invoice,
    required List<_i57.InvoiceItem>? items,
    required List<_i58.Payment>? payments,
    _i59.FulfillmentCheckoutContext? fulfillmentContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSale,
          [],
          {
            #invoice: invoice,
            #items: items,
            #payments: payments,
            #fulfillmentContext: fulfillmentContext,
          },
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<_i56.Invoice?> getInvoiceById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i54.Future<_i56.Invoice?>.value(),
      ) as _i54.Future<_i56.Invoice?>);

  @override
  _i54.Future<_i56.Invoice?> getInvoiceByNumber(String? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceByNumber,
          [number],
        ),
        returnValue: _i54.Future<_i56.Invoice?>.value(),
      ) as _i54.Future<_i56.Invoice?>);

  @override
  _i54.Future<List<_i56.Invoice>> getUnsyncedInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedInvoices,
          [],
        ),
        returnValue: _i54.Future<List<_i56.Invoice>>.value(<_i56.Invoice>[]),
      ) as _i54.Future<List<_i56.Invoice>>);

  @override
  _i54.Future<List<Map<String, dynamic>>> getUnsyncedAggregates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedAggregates,
          [],
        ),
        returnValue: _i54.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i54.Future<List<Map<String, dynamic>>>);

  @override
  _i54.Future<void> markAsSynced(List<String>? invoiceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [invoiceIds],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> acknowledgeSaleSync({
    required String? invoiceId,
    required String? outcome,
    required List<String>? acknowledgedCorrelationIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acknowledgeSaleSync,
          [],
          {
            #invoiceId: invoiceId,
            #outcome: outcome,
            #acknowledgedCorrelationIds: acknowledgedCorrelationIds,
          },
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<int> getInventoryEnrichmentPendingCount() => (super.noSuchMethod(
        Invocation.method(
          #getInventoryEnrichmentPendingCount,
          [],
        ),
        returnValue: _i54.Future<int>.value(0),
      ) as _i54.Future<int>);

  @override
  _i54.Future<_i2.ReprintPreparation> prepareReprintInvoice(
    String? invoiceId,
    String? reasonCode, {
    String? reasonDetail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareReprintInvoice,
          [
            invoiceId,
            reasonCode,
          ],
          {#reasonDetail: reasonDetail},
        ),
        returnValue:
            _i54.Future<_i2.ReprintPreparation>.value(_FakeReprintPreparation_0(
          this,
          Invocation.method(
            #prepareReprintInvoice,
            [
              invoiceId,
              reasonCode,
            ],
            {#reasonDetail: reasonDetail},
          ),
        )),
      ) as _i54.Future<_i2.ReprintPreparation>);

  @override
  _i54.Future<void> voidInvoice(
    String? invoiceId,
    String? reasonCode, {
    String? reasonDetail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reasonCode,
          ],
          {#reasonDetail: reasonDetail},
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> createCreditNote({
    required String? originalInvoiceId,
    required String? reason,
    required String? authorizedByUserId,
    required _i60.UserRole? authorizedByRole,
    _i2.RefundReasonPolicy? refundReasonPolicy =
        _i2.RefundReasonPolicy.restockOriginalBom,
    List<_i2.CreditNoteRefundLine>? lines,
    String? terminalId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCreditNote,
          [],
          {
            #originalInvoiceId: originalInvoiceId,
            #reason: reason,
            #authorizedByUserId: authorizedByUserId,
            #authorizedByRole: authorizedByRole,
            #refundReasonPolicy: refundReasonPolicy,
            #lines: lines,
            #terminalId: terminalId,
          },
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i56.Invoice>> getInvoicesBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesBySessionId,
          [sessionId],
        ),
        returnValue: _i54.Future<List<_i56.Invoice>>.value(<_i56.Invoice>[]),
      ) as _i54.Future<List<_i56.Invoice>>);

  @override
  _i54.Future<List<_i58.Payment>> getPaymentsBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsBySessionId,
          [sessionId],
        ),
        returnValue: _i54.Future<List<_i58.Payment>>.value(<_i58.Payment>[]),
      ) as _i54.Future<List<_i58.Payment>>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i61.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_1(
          this,
          Invocation.getter(#database),
        ),
      ) as _i3.AppDatabase);

  @override
  _i54.Future<List<_i62.Insumo>> getActiveInsumos() => (super.noSuchMethod(
        Invocation.method(
          #getActiveInsumos,
          [],
        ),
        returnValue: _i54.Future<List<_i62.Insumo>>.value(<_i62.Insumo>[]),
      ) as _i54.Future<List<_i62.Insumo>>);

  @override
  _i54.Future<_i62.Insumo?> getInsumoById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsumoById,
          [id],
        ),
        returnValue: _i54.Future<_i62.Insumo?>.value(),
      ) as _i54.Future<_i62.Insumo?>);

  @override
  _i54.Future<List<_i62.Insumo>> getInsumosByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsumosByIds,
          [ids],
        ),
        returnValue: _i54.Future<List<_i62.Insumo>>.value(<_i62.Insumo>[]),
      ) as _i54.Future<List<_i62.Insumo>>);

  @override
  _i54.Future<void> updateInsumoStock(
    String? id,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoStock,
          [
            id,
            newStock,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> updateInsumoCost(
    String? id,
    double? newCost,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsumoCost,
          [
            id,
            newCost,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> saveInsumo(_i62.Insumo? insumo) => (super.noSuchMethod(
        Invocation.method(
          #saveInsumo,
          [insumo],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i63.Product>> getActiveProducts() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProducts,
          [],
        ),
        returnValue: _i54.Future<List<_i63.Product>>.value(<_i63.Product>[]),
      ) as _i54.Future<List<_i63.Product>>);

  @override
  _i54.Future<_i63.Product?> getProductById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i54.Future<_i63.Product?>.value(),
      ) as _i54.Future<_i63.Product?>);

  @override
  _i54.Future<void> saveProduct(_i63.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #saveProduct,
          [product],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> saveProductOptions({
    required String? productId,
    required List<_i63.ProductVariant>? variants,
    required List<_i63.Modifier>? modifiers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductOptions,
          [],
          {
            #productId: productId,
            #variants: variants,
            #modifiers: modifiers,
          },
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i64.Recipe>> getRecipeByProductId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeByProductId,
          [productId],
        ),
        returnValue: _i54.Future<List<_i64.Recipe>>.value(<_i64.Recipe>[]),
      ) as _i54.Future<List<_i64.Recipe>>);

  @override
  _i54.Future<void> saveRecipe(_i64.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [recipe],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> replaceRecipesForProduct(
    String? productId,
    List<_i64.Recipe>? recipes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceRecipesForProduct,
          [
            productId,
            recipes,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i65.RecipeVersionDocument>> getRecipeVersionDocuments(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocuments,
          [productId],
        ),
        returnValue: _i54.Future<List<_i65.RecipeVersionDocument>>.value(
            <_i65.RecipeVersionDocument>[]),
      ) as _i54.Future<List<_i65.RecipeVersionDocument>>);

  @override
  _i54.Future<String?> getActiveRecipeVersionId(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecipeVersionId,
          [productId],
        ),
        returnValue: _i54.Future<String?>.value(),
      ) as _i54.Future<String?>);

  @override
  _i54.Future<_i65.RecipeVersionDocument?> getRecipeVersionDocumentById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeVersionDocumentById,
          [id],
        ),
        returnValue: _i54.Future<_i65.RecipeVersionDocument?>.value(),
      ) as _i54.Future<_i65.RecipeVersionDocument?>);

  @override
  _i54.Future<void> saveRecipeVersionDocument(
          _i65.RecipeVersionDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipeVersionDocument,
          [document],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i65.RecipeVersionDocument>>
      getUnsyncedRecipeVersionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedRecipeVersionDocuments,
              [],
            ),
            returnValue: _i54.Future<List<_i65.RecipeVersionDocument>>.value(
                <_i65.RecipeVersionDocument>[]),
          ) as _i54.Future<List<_i65.RecipeVersionDocument>>);

  @override
  _i54.Future<void> markRecipeVersionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecipeVersionDocumentAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i66.CountSessionDocument>> getCountSessionDocuments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountSessionDocuments,
          [],
        ),
        returnValue: _i54.Future<List<_i66.CountSessionDocument>>.value(
            <_i66.CountSessionDocument>[]),
      ) as _i54.Future<List<_i66.CountSessionDocument>>);

  @override
  _i54.Future<void> saveCountSessionDocument(
          _i66.CountSessionDocument? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCountSessionDocument,
          [session],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i66.CountSessionDocument>>
      getUnsyncedCountSessionDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedCountSessionDocuments,
              [],
            ),
            returnValue: _i54.Future<List<_i66.CountSessionDocument>>.value(
                <_i66.CountSessionDocument>[]),
          ) as _i54.Future<List<_i66.CountSessionDocument>>);

  @override
  _i54.Future<void> markCountSessionDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markCountSessionDocumentAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> saveMovement(_i67.InventoryMovement? movement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMovement,
          [movement],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i67.InventoryMovement>> getAllMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMovements,
          [],
        ),
        returnValue: _i54.Future<List<_i67.InventoryMovement>>.value(
            <_i67.InventoryMovement>[]),
      ) as _i54.Future<List<_i67.InventoryMovement>>);

  @override
  _i54.Future<List<_i67.InventoryMovement>> getUnsyncedMovements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedMovements,
          [],
        ),
        returnValue: _i54.Future<List<_i67.InventoryMovement>>.value(
            <_i67.InventoryMovement>[]),
      ) as _i54.Future<List<_i67.InventoryMovement>>);

  @override
  _i54.Future<void> markMovementAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markMovementAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> markMovementAsFailed(
    String? id, {
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMovementAsFailed,
          [id],
          {#error: error},
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i68.Supplier>> getActiveSuppliers() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSuppliers,
          [],
        ),
        returnValue: _i54.Future<List<_i68.Supplier>>.value(<_i68.Supplier>[]),
      ) as _i54.Future<List<_i68.Supplier>>);

  @override
  _i54.Future<void> saveSupplier(_i68.Supplier? supplier) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSupplier,
          [supplier],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i69.Warehouse>> getActiveWarehouses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWarehouses,
          [],
        ),
        returnValue:
            _i54.Future<List<_i69.Warehouse>>.value(<_i69.Warehouse>[]),
      ) as _i54.Future<List<_i69.Warehouse>>);

  @override
  _i54.Future<void> saveWarehouse(_i69.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWarehouse,
          [warehouse],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i70.Batch>> getBatchesByInsumoId(String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchesByInsumoId,
          [insumoId],
        ),
        returnValue: _i54.Future<List<_i70.Batch>>.value(<_i70.Batch>[]),
      ) as _i54.Future<List<_i70.Batch>>);

  @override
  _i54.Future<void> saveBatch(_i70.Batch? batch) => (super.noSuchMethod(
        Invocation.method(
          #saveBatch,
          [batch],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i71.UomConversion>> getConversionsByInsumoId(
          String? insumoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversionsByInsumoId,
          [insumoId],
        ),
        returnValue:
            _i54.Future<List<_i71.UomConversion>>.value(<_i71.UomConversion>[]),
      ) as _i54.Future<List<_i71.UomConversion>>);

  @override
  _i54.Future<void> saveConversion(_i71.UomConversion? conversion) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversion,
          [conversion],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> deleteConversion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConversion,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i72.CatalogValue>> getActiveCatalog(
          _i73.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCatalog,
          [type],
        ),
        returnValue:
            _i54.Future<List<_i72.CatalogValue>>.value(<_i72.CatalogValue>[]),
      ) as _i54.Future<List<_i72.CatalogValue>>);

  @override
  _i54.Future<List<_i72.CatalogValue>> getAllCatalog(_i73.CatalogType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCatalog,
          [type],
        ),
        returnValue:
            _i54.Future<List<_i72.CatalogValue>>.value(<_i72.CatalogValue>[]),
      ) as _i54.Future<List<_i72.CatalogValue>>);

  @override
  _i54.Future<_i72.CatalogValue?> findCatalogByCode(
    _i73.CatalogType? type,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCatalogByCode,
          [
            type,
            code,
          ],
        ),
        returnValue: _i54.Future<_i72.CatalogValue?>.value(),
      ) as _i54.Future<_i72.CatalogValue?>);

  @override
  _i54.Future<void> upsertCatalogValues(List<_i72.CatalogValue>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertCatalogValues,
          [values],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> setCatalogActive(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCatalogActive,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<int> countCatalogValues() => (super.noSuchMethod(
        Invocation.method(
          #countCatalogValues,
          [],
        ),
        returnValue: _i54.Future<int>.value(0),
      ) as _i54.Future<int>);

  @override
  _i54.Future<void> savePurchase(_i74.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePurchase,
          [purchase],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> queuePurchaseSync(_i74.Purchase? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #queuePurchaseSync,
          [purchase],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i74.Purchase>> getPurchaseHistory() => (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
        ),
        returnValue: _i54.Future<List<_i74.Purchase>>.value(<_i74.Purchase>[]),
      ) as _i54.Future<List<_i74.Purchase>>);

  @override
  _i54.Future<List<_i74.Purchase>> getUnsyncedPurchases() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPurchases,
          [],
        ),
        returnValue: _i54.Future<List<_i74.Purchase>>.value(<_i74.Purchase>[]),
      ) as _i54.Future<List<_i74.Purchase>>);

  @override
  _i54.Future<void> markPurchaseAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markPurchaseAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<double> fetchOfficialBcnRateByInvoiceDate(
          DateTime? invoiceDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOfficialBcnRateByInvoiceDate,
          [invoiceDate],
        ),
        returnValue: _i54.Future<double>.value(0.0),
      ) as _i54.Future<double>);

  @override
  _i54.Future<double> getCachedOfficialBcnRate() => (super.noSuchMethod(
        Invocation.method(
          #getCachedOfficialBcnRate,
          [],
        ),
        returnValue: _i54.Future<double>.value(0.0),
      ) as _i54.Future<double>);

  @override
  _i54.Future<List<_i75.ForensicAlert>> getForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getForensicAlerts,
          [],
        ),
        returnValue:
            _i54.Future<List<_i75.ForensicAlert>>.value(<_i75.ForensicAlert>[]),
      ) as _i54.Future<List<_i75.ForensicAlert>>);

  @override
  _i54.Future<void> saveForensicAlert(_i75.ForensicAlert? alert) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveForensicAlert,
          [alert],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i75.ForensicAlert>> getUnsyncedForensicAlerts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedForensicAlerts,
          [],
        ),
        returnValue:
            _i54.Future<List<_i75.ForensicAlert>>.value(<_i75.ForensicAlert>[]),
      ) as _i54.Future<List<_i75.ForensicAlert>>);

  @override
  _i54.Future<void> markForensicAlertAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markForensicAlertAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i76.ProductionOrderDocument>>
      getProductionOrderDocuments() => (super.noSuchMethod(
            Invocation.method(
              #getProductionOrderDocuments,
              [],
            ),
            returnValue: _i54.Future<List<_i76.ProductionOrderDocument>>.value(
                <_i76.ProductionOrderDocument>[]),
          ) as _i54.Future<List<_i76.ProductionOrderDocument>>);

  @override
  _i54.Future<int> reserveProductionSourceSequence(String? terminalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reserveProductionSourceSequence,
          [terminalId],
        ),
        returnValue: _i54.Future<int>.value(0),
      ) as _i54.Future<int>);

  @override
  _i54.Future<void> saveProductionOrderDocument(
          _i76.ProductionOrderDocument? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionOrderDocument,
          [document],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> saveProductionCloseTransaction(
    _i76.ProductionOrderDocument? document,
    List<_i67.InventoryMovement>? movements, {
    bool? debugFailAfterWrites = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProductionCloseTransaction,
          [
            document,
            movements,
          ],
          {#debugFailAfterWrites: debugFailAfterWrites},
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i76.ProductionOrderDocument>>
      getUnsyncedProductionOrders() => (super.noSuchMethod(
            Invocation.method(
              #getUnsyncedProductionOrders,
              [],
            ),
            returnValue: _i54.Future<List<_i76.ProductionOrderDocument>>.value(
                <_i76.ProductionOrderDocument>[]),
          ) as _i54.Future<List<_i76.ProductionOrderDocument>>);

  @override
  _i54.Future<void> markProductionOrderDocumentAsSynced(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markProductionOrderDocumentAsSynced,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i77.KardexCorrectionEntity>> getKardexCorrections() =>
      (super.noSuchMethod(
        Invocation.method(
          #getKardexCorrections,
          [],
        ),
        returnValue: _i54.Future<List<_i77.KardexCorrectionEntity>>.value(
            <_i77.KardexCorrectionEntity>[]),
      ) as _i54.Future<List<_i77.KardexCorrectionEntity>>);

  @override
  _i54.Future<List<_i78.KardexRecalculateQueueEntity>>
      getPendingKardexQueue() => (super.noSuchMethod(
            Invocation.method(
              #getPendingKardexQueue,
              [],
            ),
            returnValue:
                _i54.Future<List<_i78.KardexRecalculateQueueEntity>>.value(
                    <_i78.KardexRecalculateQueueEntity>[]),
          ) as _i54.Future<List<_i78.KardexRecalculateQueueEntity>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i79.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
      ) as bool);

  @override
  _i54.Future<_i60.User?> loginOnline(
    String? email,
    String? password, {
    String? tenantSlug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
          {#tenantSlug: tenantSlug},
        ),
        returnValue: _i54.Future<_i60.User?>.value(),
      ) as _i54.Future<_i60.User?>);

  @override
  _i54.Future<_i4.TerminalLinking> claimLinkingCode(
    String? code,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimLinkingCode,
          [
            code,
            deviceId,
          ],
        ),
        returnValue:
            _i54.Future<_i4.TerminalLinking>.value(_FakeTerminalLinking_2(
          this,
          Invocation.method(
            #claimLinkingCode,
            [
              code,
              deviceId,
            ],
          ),
        )),
      ) as _i54.Future<_i4.TerminalLinking>);

  @override
  _i54.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<_i60.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i54.Future<_i60.User?>.value(),
      ) as _i54.Future<_i60.User?>);

  @override
  _i54.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i54.Future<bool>.value(false),
      ) as _i54.Future<bool>);

  @override
  _i54.Future<_i60.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i54.Future<_i60.User?>.value(),
      ) as _i54.Future<_i60.User?>);

  @override
  _i54.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i54.Future<String?>.value(),
      ) as _i54.Future<String?>);

  @override
  _i54.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i60.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i54.Future<List<_i60.User>>.value(<_i60.User>[]),
      ) as _i54.Future<List<_i60.User>>);

  @override
  _i54.Future<void> saveUser(
    _i60.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.UserDao get userDao => (super.noSuchMethod(
        Invocation.getter(#userDao),
        returnValue: _FakeUserDao_3(
          this,
          Invocation.getter(#userDao),
        ),
      ) as _i5.UserDao);

  @override
  _i6.SecurityProfileDao get securityProfileDao => (super.noSuchMethod(
        Invocation.getter(#securityProfileDao),
        returnValue: _FakeSecurityProfileDao_4(
          this,
          Invocation.getter(#securityProfileDao),
        ),
      ) as _i6.SecurityProfileDao);

  @override
  _i7.AuditDao get auditDao => (super.noSuchMethod(
        Invocation.getter(#auditDao),
        returnValue: _FakeAuditDao_5(
          this,
          Invocation.getter(#auditDao),
        ),
      ) as _i7.AuditDao);

  @override
  _i8.LocalConfigDao get localConfigDao => (super.noSuchMethod(
        Invocation.getter(#localConfigDao),
        returnValue: _FakeLocalConfigDao_6(
          this,
          Invocation.getter(#localConfigDao),
        ),
      ) as _i8.LocalConfigDao);

  @override
  _i9.InsumoDao get insumoDao => (super.noSuchMethod(
        Invocation.getter(#insumoDao),
        returnValue: _FakeInsumoDao_7(
          this,
          Invocation.getter(#insumoDao),
        ),
      ) as _i9.InsumoDao);

  @override
  _i10.ProductDao get productDao => (super.noSuchMethod(
        Invocation.getter(#productDao),
        returnValue: _FakeProductDao_8(
          this,
          Invocation.getter(#productDao),
        ),
      ) as _i10.ProductDao);

  @override
  _i10.RecipeDao get recipeDao => (super.noSuchMethod(
        Invocation.getter(#recipeDao),
        returnValue: _FakeRecipeDao_9(
          this,
          Invocation.getter(#recipeDao),
        ),
      ) as _i10.RecipeDao);

  @override
  _i11.RecipeVersionDocumentDao get recipeVersionDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#recipeVersionDocumentDao),
        returnValue: _FakeRecipeVersionDocumentDao_10(
          this,
          Invocation.getter(#recipeVersionDocumentDao),
        ),
      ) as _i11.RecipeVersionDocumentDao);

  @override
  _i12.CountSessionDao get countSessionDao => (super.noSuchMethod(
        Invocation.getter(#countSessionDao),
        returnValue: _FakeCountSessionDao_11(
          this,
          Invocation.getter(#countSessionDao),
        ),
      ) as _i12.CountSessionDao);

  @override
  _i13.CountLineDao get countLineDao => (super.noSuchMethod(
        Invocation.getter(#countLineDao),
        returnValue: _FakeCountLineDao_12(
          this,
          Invocation.getter(#countLineDao),
        ),
      ) as _i13.CountLineDao);

  @override
  _i14.ForensicAlertDao get forensicAlertDao => (super.noSuchMethod(
        Invocation.getter(#forensicAlertDao),
        returnValue: _FakeForensicAlertDao_13(
          this,
          Invocation.getter(#forensicAlertDao),
        ),
      ) as _i14.ForensicAlertDao);

  @override
  _i15.MovementDao get movementDao => (super.noSuchMethod(
        Invocation.getter(#movementDao),
        returnValue: _FakeMovementDao_14(
          this,
          Invocation.getter(#movementDao),
        ),
      ) as _i15.MovementDao);

  @override
  _i16.MovementSyncStateDao get movementSyncStateDao => (super.noSuchMethod(
        Invocation.getter(#movementSyncStateDao),
        returnValue: _FakeMovementSyncStateDao_15(
          this,
          Invocation.getter(#movementSyncStateDao),
        ),
      ) as _i16.MovementSyncStateDao);

  @override
  _i17.KardexRecalculateQueueDao get kardexRecalculateQueueDao =>
      (super.noSuchMethod(
        Invocation.getter(#kardexRecalculateQueueDao),
        returnValue: _FakeKardexRecalculateQueueDao_16(
          this,
          Invocation.getter(#kardexRecalculateQueueDao),
        ),
      ) as _i17.KardexRecalculateQueueDao);

  @override
  _i18.KardexCorrectionDao get kardexCorrectionDao => (super.noSuchMethod(
        Invocation.getter(#kardexCorrectionDao),
        returnValue: _FakeKardexCorrectionDao_17(
          this,
          Invocation.getter(#kardexCorrectionDao),
        ),
      ) as _i18.KardexCorrectionDao);

  @override
  _i19.InventoryDao get inventoryDao => (super.noSuchMethod(
        Invocation.getter(#inventoryDao),
        returnValue: _FakeInventoryDao_18(
          this,
          Invocation.getter(#inventoryDao),
        ),
      ) as _i19.InventoryDao);

  @override
  _i20.SupplierDao get supplierDao => (super.noSuchMethod(
        Invocation.getter(#supplierDao),
        returnValue: _FakeSupplierDao_19(
          this,
          Invocation.getter(#supplierDao),
        ),
      ) as _i20.SupplierDao);

  @override
  _i21.WarehouseDao get warehouseDao => (super.noSuchMethod(
        Invocation.getter(#warehouseDao),
        returnValue: _FakeWarehouseDao_20(
          this,
          Invocation.getter(#warehouseDao),
        ),
      ) as _i21.WarehouseDao);

  @override
  _i22.PurchaseDao get purchaseDao => (super.noSuchMethod(
        Invocation.getter(#purchaseDao),
        returnValue: _FakePurchaseDao_21(
          this,
          Invocation.getter(#purchaseDao),
        ),
      ) as _i22.PurchaseDao);

  @override
  _i23.ProductionOrderDocumentDao get productionOrderDocumentDao =>
      (super.noSuchMethod(
        Invocation.getter(#productionOrderDocumentDao),
        returnValue: _FakeProductionOrderDocumentDao_22(
          this,
          Invocation.getter(#productionOrderDocumentDao),
        ),
      ) as _i23.ProductionOrderDocumentDao);

  @override
  _i24.ProductionTransactionDao get productionTransactionDao =>
      (super.noSuchMethod(
        Invocation.getter(#productionTransactionDao),
        returnValue: _FakeProductionTransactionDao_23(
          this,
          Invocation.getter(#productionTransactionDao),
        ),
      ) as _i24.ProductionTransactionDao);

  @override
  _i25.UomConversionDao get uomConversionDao => (super.noSuchMethod(
        Invocation.getter(#uomConversionDao),
        returnValue: _FakeUomConversionDao_24(
          this,
          Invocation.getter(#uomConversionDao),
        ),
      ) as _i25.UomConversionDao);

  @override
  _i26.BatchDao get batchDao => (super.noSuchMethod(
        Invocation.getter(#batchDao),
        returnValue: _FakeBatchDao_25(
          this,
          Invocation.getter(#batchDao),
        ),
      ) as _i26.BatchDao);

  @override
  _i27.CatalogValueDao get catalogValueDao => (super.noSuchMethod(
        Invocation.getter(#catalogValueDao),
        returnValue: _FakeCatalogValueDao_26(
          this,
          Invocation.getter(#catalogValueDao),
        ),
      ) as _i27.CatalogValueDao);

  @override
  _i28.InvoiceDao get invoiceDao => (super.noSuchMethod(
        Invocation.getter(#invoiceDao),
        returnValue: _FakeInvoiceDao_27(
          this,
          Invocation.getter(#invoiceDao),
        ),
      ) as _i28.InvoiceDao);

  @override
  _i29.InvoiceItemDao get invoiceItemDao => (super.noSuchMethod(
        Invocation.getter(#invoiceItemDao),
        returnValue: _FakeInvoiceItemDao_28(
          this,
          Invocation.getter(#invoiceItemDao),
        ),
      ) as _i29.InvoiceItemDao);

  @override
  _i30.PaymentDao get paymentDao => (super.noSuchMethod(
        Invocation.getter(#paymentDao),
        returnValue: _FakePaymentDao_29(
          this,
          Invocation.getter(#paymentDao),
        ),
      ) as _i30.PaymentDao);

  @override
  _i31.TaxConfigDao get taxConfigDao => (super.noSuchMethod(
        Invocation.getter(#taxConfigDao),
        returnValue: _FakeTaxConfigDao_30(
          this,
          Invocation.getter(#taxConfigDao),
        ),
      ) as _i31.TaxConfigDao);

  @override
  _i32.SalesTransactionDao get salesTransactionDao => (super.noSuchMethod(
        Invocation.getter(#salesTransactionDao),
        returnValue: _FakeSalesTransactionDao_31(
          this,
          Invocation.getter(#salesTransactionDao),
        ),
      ) as _i32.SalesTransactionDao);

  @override
  _i33.CashierSessionDao get cashierSessionDao => (super.noSuchMethod(
        Invocation.getter(#cashierSessionDao),
        returnValue: _FakeCashierSessionDao_32(
          this,
          Invocation.getter(#cashierSessionDao),
        ),
      ) as _i33.CashierSessionDao);

  @override
  _i34.CashMovementDao get cashMovementDao => (super.noSuchMethod(
        Invocation.getter(#cashMovementDao),
        returnValue: _FakeCashMovementDao_33(
          this,
          Invocation.getter(#cashMovementDao),
        ),
      ) as _i34.CashMovementDao);

  @override
  _i35.HoldTicketDao get holdTicketDao => (super.noSuchMethod(
        Invocation.getter(#holdTicketDao),
        returnValue: _FakeHoldTicketDao_34(
          this,
          Invocation.getter(#holdTicketDao),
        ),
      ) as _i35.HoldTicketDao);

  @override
  _i36.PromotionDao get promotionDao => (super.noSuchMethod(
        Invocation.getter(#promotionDao),
        returnValue: _FakePromotionDao_35(
          this,
          Invocation.getter(#promotionDao),
        ),
      ) as _i36.PromotionDao);

  @override
  _i37.RestaurantAreaDao get restaurantAreaDao => (super.noSuchMethod(
        Invocation.getter(#restaurantAreaDao),
        returnValue: _FakeRestaurantAreaDao_36(
          this,
          Invocation.getter(#restaurantAreaDao),
        ),
      ) as _i37.RestaurantAreaDao);

  @override
  _i38.RestaurantTableDao get restaurantTableDao => (super.noSuchMethod(
        Invocation.getter(#restaurantTableDao),
        returnValue: _FakeRestaurantTableDao_37(
          this,
          Invocation.getter(#restaurantTableDao),
        ),
      ) as _i38.RestaurantTableDao);

  @override
  _i39.KitchenOrderDao get kitchenOrderDao => (super.noSuchMethod(
        Invocation.getter(#kitchenOrderDao),
        returnValue: _FakeKitchenOrderDao_38(
          this,
          Invocation.getter(#kitchenOrderDao),
        ),
      ) as _i39.KitchenOrderDao);

  @override
  _i40.CustomerDao get customerDao => (super.noSuchMethod(
        Invocation.getter(#customerDao),
        returnValue: _FakeCustomerDao_39(
          this,
          Invocation.getter(#customerDao),
        ),
      ) as _i40.CustomerDao);

  @override
  _i41.CustomerPointTransactionDao get customerPointTransactionDao =>
      (super.noSuchMethod(
        Invocation.getter(#customerPointTransactionDao),
        returnValue: _FakeCustomerPointTransactionDao_40(
          this,
          Invocation.getter(#customerPointTransactionDao),
        ),
      ) as _i41.CustomerPointTransactionDao);

  @override
  _i42.LoyaltyProgramDao get loyaltyProgramDao => (super.noSuchMethod(
        Invocation.getter(#loyaltyProgramDao),
        returnValue: _FakeLoyaltyProgramDao_41(
          this,
          Invocation.getter(#loyaltyProgramDao),
        ),
      ) as _i42.LoyaltyProgramDao);

  @override
  _i43.LoyaltyRewardDao get loyaltyRewardDao => (super.noSuchMethod(
        Invocation.getter(#loyaltyRewardDao),
        returnValue: _FakeLoyaltyRewardDao_42(
          this,
          Invocation.getter(#loyaltyRewardDao),
        ),
      ) as _i43.LoyaltyRewardDao);

  @override
  _i44.FiscalConfigLocalDao get fiscalConfigLocalDao => (super.noSuchMethod(
        Invocation.getter(#fiscalConfigLocalDao),
        returnValue: _FakeFiscalConfigLocalDao_43(
          this,
          Invocation.getter(#fiscalConfigLocalDao),
        ),
      ) as _i44.FiscalConfigLocalDao);

  @override
  _i45.ActivationAttemptLocalDao get activationAttemptLocalDao =>
      (super.noSuchMethod(
        Invocation.getter(#activationAttemptLocalDao),
        returnValue: _FakeActivationAttemptLocalDao_44(
          this,
          Invocation.getter(#activationAttemptLocalDao),
        ),
      ) as _i45.ActivationAttemptLocalDao);

  @override
  _i46.ActivationCheckResultLocalDao get activationCheckResultLocalDao =>
      (super.noSuchMethod(
        Invocation.getter(#activationCheckResultLocalDao),
        returnValue: _FakeActivationCheckResultLocalDao_45(
          this,
          Invocation.getter(#activationCheckResultLocalDao),
        ),
      ) as _i46.ActivationCheckResultLocalDao);

  @override
  _i47.FirstSuccessfulSaleClaimDao get firstSuccessfulSaleClaimDao =>
      (super.noSuchMethod(
        Invocation.getter(#firstSuccessfulSaleClaimDao),
        returnValue: _FakeFirstSuccessfulSaleClaimDao_46(
          this,
          Invocation.getter(#firstSuccessfulSaleClaimDao),
        ),
      ) as _i47.FirstSuccessfulSaleClaimDao);

  @override
  _i48.FirstCustomerSaleObservationDao get firstCustomerSaleObservationDao =>
      (super.noSuchMethod(
        Invocation.getter(#firstCustomerSaleObservationDao),
        returnValue: _FakeFirstCustomerSaleObservationDao_47(
          this,
          Invocation.getter(#firstCustomerSaleObservationDao),
        ),
      ) as _i48.FirstCustomerSaleObservationDao);

  @override
  _i49.ActivationOutboxDao get activationOutboxDao => (super.noSuchMethod(
        Invocation.getter(#activationOutboxDao),
        returnValue: _FakeActivationOutboxDao_48(
          this,
          Invocation.getter(#activationOutboxDao),
        ),
      ) as _i49.ActivationOutboxDao);

  @override
  _i50.AuthorityProjectionDao get authorityProjectionDao => (super.noSuchMethod(
        Invocation.getter(#authorityProjectionDao),
        returnValue: _FakeAuthorityProjectionDao_49(
          this,
          Invocation.getter(#authorityProjectionDao),
        ),
      ) as _i50.AuthorityProjectionDao);

  @override
  _i51.FulfillmentTopologyDao get fulfillmentTopologyDao => (super.noSuchMethod(
        Invocation.getter(#fulfillmentTopologyDao),
        returnValue: _FakeFulfillmentTopologyDao_50(
          this,
          Invocation.getter(#fulfillmentTopologyDao),
        ),
      ) as _i51.FulfillmentTopologyDao);

  @override
  _i52.FulfillmentPersistenceDao get fulfillmentPersistenceDao =>
      (super.noSuchMethod(
        Invocation.getter(#fulfillmentPersistenceDao),
        returnValue: _FakeFulfillmentPersistenceDao_51(
          this,
          Invocation.getter(#fulfillmentPersistenceDao),
        ),
      ) as _i52.FulfillmentPersistenceDao);

  @override
  _i53.OhacDeliveryDao get ohacDeliveryDao => (super.noSuchMethod(
        Invocation.getter(#ohacDeliveryDao),
        returnValue: _FakeOhacDeliveryDao_52(
          this,
          Invocation.getter(#ohacDeliveryDao),
        ),
      ) as _i53.OhacDeliveryDao);

  @override
  _i54.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_53<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i54.StreamController<String>);

  @override
  set changeListener(_i54.StreamController<String>? _changeListener) =>
      super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          _changeListener,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i55.DatabaseExecutor get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseExecutor_54(
          this,
          Invocation.getter(#database),
        ),
      ) as _i55.DatabaseExecutor);

  @override
  set database(_i55.DatabaseExecutor? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i54.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}

/// A class which mocks [CashierSessionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashierSessionDao extends _i1.Mock implements _i33.CashierSessionDao {
  MockCashierSessionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<_i80.CashierSessionEntity?> getSessionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [id],
        ),
        returnValue: _i54.Future<_i80.CashierSessionEntity?>.value(),
      ) as _i54.Future<_i80.CashierSessionEntity?>);

  @override
  _i54.Future<_i80.CashierSessionEntity?> getActiveSession() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i54.Future<_i80.CashierSessionEntity?>.value(),
      ) as _i54.Future<_i80.CashierSessionEntity?>);

  @override
  _i54.Future<_i80.CashierSessionEntity?> getActiveSessionForUserAndTerminal(
    String? userId,
    String? terminalId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSessionForUserAndTerminal,
          [
            userId,
            terminalId,
          ],
        ),
        returnValue: _i54.Future<_i80.CashierSessionEntity?>.value(),
      ) as _i54.Future<_i80.CashierSessionEntity?>);

  @override
  _i54.Future<void> insertSession(_i80.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSession,
          [session],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> updateSession(_i80.CashierSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [session],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i80.CashierSessionEntity>> getAllSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue: _i54.Future<List<_i80.CashierSessionEntity>>.value(
            <_i80.CashierSessionEntity>[]),
      ) as _i54.Future<List<_i80.CashierSessionEntity>>);

  @override
  _i54.Future<int?> countClosedSessions() => (super.noSuchMethod(
        Invocation.method(
          #countClosedSessions,
          [],
        ),
        returnValue: _i54.Future<int?>.value(),
      ) as _i54.Future<int?>);
}

/// A class which mocks [InvoiceDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceDao extends _i1.Mock implements _i28.InvoiceDao {
  MockInvoiceDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<_i81.InvoiceEntity?> getInvoiceById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i54.Future<_i81.InvoiceEntity?>.value(),
      ) as _i54.Future<_i81.InvoiceEntity?>);

  @override
  _i54.Future<_i81.InvoiceEntity?> getInvoiceByNumber(String? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceByNumber,
          [number],
        ),
        returnValue: _i54.Future<_i81.InvoiceEntity?>.value(),
      ) as _i54.Future<_i81.InvoiceEntity?>);

  @override
  _i54.Future<List<_i81.InvoiceEntity>> getAllInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getAllInvoices,
          [],
        ),
        returnValue:
            _i54.Future<List<_i81.InvoiceEntity>>.value(<_i81.InvoiceEntity>[]),
      ) as _i54.Future<List<_i81.InvoiceEntity>>);

  @override
  _i54.Future<List<_i81.InvoiceEntity>> getInvoicesBySyncStatus(
          String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesBySyncStatus,
          [status],
        ),
        returnValue:
            _i54.Future<List<_i81.InvoiceEntity>>.value(<_i81.InvoiceEntity>[]),
      ) as _i54.Future<List<_i81.InvoiceEntity>>);

  @override
  _i54.Future<List<_i81.InvoiceEntity>> getInvoicesByTimeRange(
    int? startTime,
    int? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesByTimeRange,
          [
            startTime,
            endTime,
          ],
        ),
        returnValue:
            _i54.Future<List<_i81.InvoiceEntity>>.value(<_i81.InvoiceEntity>[]),
      ) as _i54.Future<List<_i81.InvoiceEntity>>);

  @override
  _i54.Future<List<_i81.InvoiceEntity>> getInvoicesByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesByUserId,
          [userId],
        ),
        returnValue:
            _i54.Future<List<_i81.InvoiceEntity>>.value(<_i81.InvoiceEntity>[]),
      ) as _i54.Future<List<_i81.InvoiceEntity>>);

  @override
  _i54.Future<void> insertInvoice(_i81.InvoiceEntity? invoice) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertInvoice,
          [invoice],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> updateInvoice(_i81.InvoiceEntity? invoice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInvoice,
          [invoice],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<String?> getLastInvoiceNumber() => (super.noSuchMethod(
        Invocation.method(
          #getLastInvoiceNumber,
          [],
        ),
        returnValue: _i54.Future<String?>.value(),
      ) as _i54.Future<String?>);

  @override
  _i54.Future<_i81.InvoiceEntity?> getLastInvoice() => (super.noSuchMethod(
        Invocation.method(
          #getLastInvoice,
          [],
        ),
        returnValue: _i54.Future<_i81.InvoiceEntity?>.value(),
      ) as _i54.Future<_i81.InvoiceEntity?>);

  @override
  _i54.Future<void> updateSyncStatusForIds(
    List<String>? ids,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSyncStatusForIds,
          [
            ids,
            status,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<_i81.InvoiceEntity?> getInvoiceByIdempotencyKey(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceByIdempotencyKey,
          [key],
        ),
        returnValue: _i54.Future<_i81.InvoiceEntity?>.value(),
      ) as _i54.Future<_i81.InvoiceEntity?>);

  @override
  _i54.Future<int?> getInventoryEnrichmentPendingCount() => (super.noSuchMethod(
        Invocation.method(
          #getInventoryEnrichmentPendingCount,
          [],
        ),
        returnValue: _i54.Future<int?>.value(),
      ) as _i54.Future<int?>);
}

/// A class which mocks [InvoiceItemDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceItemDao extends _i1.Mock implements _i29.InvoiceItemDao {
  MockInvoiceItemDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<List<_i82.InvoiceItemEntity>> getItemsByInvoiceId(
          String? invoiceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByInvoiceId,
          [invoiceId],
        ),
        returnValue: _i54.Future<List<_i82.InvoiceItemEntity>>.value(
            <_i82.InvoiceItemEntity>[]),
      ) as _i54.Future<List<_i82.InvoiceItemEntity>>);

  @override
  _i54.Future<void> insertItems(List<_i82.InvoiceItemEntity>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertItems,
          [items],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}

/// A class which mocks [PaymentDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentDao extends _i1.Mock implements _i30.PaymentDao {
  MockPaymentDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<List<_i83.PaymentEntity>> getPaymentsByInvoiceId(
          String? invoiceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByInvoiceId,
          [invoiceId],
        ),
        returnValue:
            _i54.Future<List<_i83.PaymentEntity>>.value(<_i83.PaymentEntity>[]),
      ) as _i54.Future<List<_i83.PaymentEntity>>);

  @override
  _i54.Future<List<_i83.PaymentEntity>> getPaymentsByTimeRange(
    int? startTime,
    int? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByTimeRange,
          [
            startTime,
            endTime,
          ],
        ),
        returnValue:
            _i54.Future<List<_i83.PaymentEntity>>.value(<_i83.PaymentEntity>[]),
      ) as _i54.Future<List<_i83.PaymentEntity>>);

  @override
  _i54.Future<List<_i83.PaymentEntity>> getPendingCardPayments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingCardPayments,
          [],
        ),
        returnValue:
            _i54.Future<List<_i83.PaymentEntity>>.value(<_i83.PaymentEntity>[]),
      ) as _i54.Future<List<_i83.PaymentEntity>>);

  @override
  _i54.Future<int?> countPendingCardPayments() => (super.noSuchMethod(
        Invocation.method(
          #countPendingCardPayments,
          [],
        ),
        returnValue: _i54.Future<int?>.value(),
      ) as _i54.Future<int?>);

  @override
  _i54.Future<void> updatePayment(_i83.PaymentEntity? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePayment,
          [payment],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> insertPayments(List<_i83.PaymentEntity>? payments) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPayments,
          [payments],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}

/// A class which mocks [HoldTicketDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockHoldTicketDao extends _i1.Mock implements _i35.HoldTicketDao {
  MockHoldTicketDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<List<_i84.HoldTicketEntity>> getAllHoldTickets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHoldTickets,
          [],
        ),
        returnValue: _i54.Future<List<_i84.HoldTicketEntity>>.value(
            <_i84.HoldTicketEntity>[]),
      ) as _i54.Future<List<_i84.HoldTicketEntity>>);

  @override
  _i54.Future<_i84.HoldTicketEntity?> getHoldTicketById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHoldTicketById,
          [id],
        ),
        returnValue: _i54.Future<_i84.HoldTicketEntity?>.value(),
      ) as _i54.Future<_i84.HoldTicketEntity?>);

  @override
  _i54.Future<_i84.HoldTicketEntity?> getHoldTicketByTableId(String? tableId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHoldTicketByTableId,
          [tableId],
        ),
        returnValue: _i54.Future<_i84.HoldTicketEntity?>.value(),
      ) as _i54.Future<_i84.HoldTicketEntity?>);

  @override
  _i54.Future<List<_i84.HoldTicketItemEntity>> getItemsByHoldTicketId(
          String? holdTicketId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByHoldTicketId,
          [holdTicketId],
        ),
        returnValue: _i54.Future<List<_i84.HoldTicketItemEntity>>.value(
            <_i84.HoldTicketItemEntity>[]),
      ) as _i54.Future<List<_i84.HoldTicketItemEntity>>);

  @override
  _i54.Future<void> insertHoldTicket(_i84.HoldTicketEntity? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicket,
          [ticket],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> insertHoldTicketItems(
          List<_i84.HoldTicketItemEntity>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHoldTicketItems,
          [items],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<int> updateHoldTicket(_i84.HoldTicketEntity? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHoldTicket,
          [ticket],
        ),
        returnValue: _i54.Future<int>.value(0),
      ) as _i54.Future<int>);

  @override
  _i54.Future<void> deleteHoldTicketItems(String? holdTicketId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicketItems,
          [holdTicketId],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> deleteHoldTicket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicket,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> saveHoldTicket(
    _i84.HoldTicketEntity? ticket,
    List<_i84.HoldTicketItemEntity>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHoldTicket,
          [
            ticket,
            items,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> deleteHoldTicketWithItems(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHoldTicketWithItems,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}

/// A class which mocks [PromotionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromotionDao extends _i1.Mock implements _i36.PromotionDao {
  MockPromotionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i54.Future<List<_i85.PromotionEntity>> getActivePromotions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePromotions,
          [],
        ),
        returnValue: _i54.Future<List<_i85.PromotionEntity>>.value(
            <_i85.PromotionEntity>[]),
      ) as _i54.Future<List<_i85.PromotionEntity>>);

  @override
  _i54.Future<List<_i85.PromotionEntity>> getAllPromotions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPromotions,
          [],
        ),
        returnValue: _i54.Future<List<_i85.PromotionEntity>>.value(
            <_i85.PromotionEntity>[]),
      ) as _i54.Future<List<_i85.PromotionEntity>>);

  @override
  _i54.Future<void> setPromotionActive(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPromotionActive,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> savePromotion(_i85.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePromotion,
          [promotion],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> savePromotions(List<_i85.PromotionEntity>? promotions) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePromotions,
          [promotions],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<void> updatePromotion(_i85.PromotionEntity? promotion) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePromotion,
          [promotion],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);

  @override
  _i54.Future<List<_i85.PromotionEntity>> getPromotionsByProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromotionsByProduct,
          [productId],
        ),
        returnValue: _i54.Future<List<_i85.PromotionEntity>>.value(
            <_i85.PromotionEntity>[]),
      ) as _i54.Future<List<_i85.PromotionEntity>>);

  @override
  _i54.Future<List<_i85.PromotionEntity>> getPromotionsByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromotionsByCategory,
          [categoryId],
        ),
        returnValue: _i54.Future<List<_i85.PromotionEntity>>.value(
            <_i85.PromotionEntity>[]),
      ) as _i54.Future<List<_i85.PromotionEntity>>);

  @override
  _i54.Future<void> deletePromotionById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePromotionById,
          [id],
        ),
        returnValue: _i54.Future<void>.value(),
        returnValueForMissingStub: _i54.Future<void>.value(),
      ) as _i54.Future<void>);
}
