// Mocks generated by Mockito 5.4.4 from annotations
// in pos_app/test/ui/features/sales/sale_view_security_flows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:ui' as _i23;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:pos_app/data/services/sync_service.dart' as _i10;
import 'package:pos_app/domain/models/audit_log.dart' as _i26;
import 'package:pos_app/domain/models/auth/terminal_linking.dart' as _i8;
import 'package:pos_app/domain/models/config/tax_regime.dart' as _i20;
import 'package:pos_app/domain/models/config/tenant_operation_mode.dart'
    as _i12;
import 'package:pos_app/domain/models/customer/customer.dart' as _i6;
import 'package:pos_app/domain/models/inventory/product.dart' as _i15;
import 'package:pos_app/domain/models/sales/cart_item.dart' as _i14;
import 'package:pos_app/domain/models/sales/cashier_session.dart' as _i21;
import 'package:pos_app/domain/models/sales/hold_ticket.dart' as _i17;
import 'package:pos_app/domain/models/sales/payment.dart' as _i18;
import 'package:pos_app/domain/models/sales/promotion.dart' as _i16;
import 'package:pos_app/domain/models/user.dart' as _i25;
import 'package:pos_app/domain/repositories/audit_repository.dart' as _i9;
import 'package:pos_app/domain/repositories/auth_repository.dart' as _i24;
import 'package:pos_app/domain/repositories/sales/sales_repository.dart'
    as _i22;
import 'package:pos_app/domain/services/config/business_mode_evaluator.dart'
    as _i3;
import 'package:pos_app/domain/services/sales/invoice_fiscal_calculator.dart'
    as _i2;
import 'package:pos_app/domain/services/sales/loyalty_service.dart' as _i5;
import 'package:pos_app/domain/services/sales/split_bill_engine.dart' as _i7;
import 'package:pos_app/domain/services/sales/tip_engine.dart' as _i4;
import 'package:pos_app/presentation/features/sales/view_models/sale_view_model.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFiscalCalculationResult_0 extends _i1.SmartFake
    implements _i2.FiscalCalculationResult {
  _FakeFiscalCalculationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessModeEvaluator_1 extends _i1.SmartFake
    implements _i3.BusinessModeEvaluator {
  _FakeBusinessModeEvaluator_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTipCalculation_2 extends _i1.SmartFake
    implements _i4.TipCalculation {
  _FakeTipCalculation_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRedemptionValidationResult_3 extends _i1.SmartFake
    implements _i5.RedemptionValidationResult {
  _FakeRedemptionValidationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomer_4 extends _i1.SmartFake implements _i6.Customer {
  _FakeCustomer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSplitBillResult_5 extends _i1.SmartFake
    implements _i7.SplitBillResult {
  _FakeSplitBillResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTerminalLinking_6 extends _i1.SmartFake
    implements _i8.TerminalLinking {
  _FakeTerminalLinking_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditSyncOutcome_7 extends _i1.SmartFake
    implements _i9.AuditSyncOutcome {
  _FakeAuditSyncOutcome_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_8 extends _i1.SmartFake implements Duration {
  _FakeDuration_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncRunOutcome_9 extends _i1.SmartFake
    implements _i10.SyncRunOutcome {
  _FakeSyncRunOutcome_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaleViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaleViewModel extends _i1.Mock implements _i11.SaleViewModel {
  @override
  bool get lastVoidPrintSucceeded => (super.noSuchMethod(
        Invocation.getter(#lastVoidPrintSucceeded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get lastReprintPrintSucceeded => (super.noSuchMethod(
        Invocation.getter(#lastReprintPrintSucceeded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.TenantOperationMode get operationMode => (super.noSuchMethod(
        Invocation.getter(#operationMode),
        returnValue: _i12.TenantOperationMode.foodparkQsr,
        returnValueForMissingStub: _i12.TenantOperationMode.foodparkQsr,
      ) as _i12.TenantOperationMode);

  @override
  bool get isFoodParkQsr => (super.noSuchMethod(
        Invocation.getter(#isFoodParkQsr),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get supportsTables => (super.noSuchMethod(
        Invocation.getter(#supportsTables),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get supportsBuzzerPager => (super.noSuchMethod(
        Invocation.getter(#supportsBuzzerPager),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get pointsToRedeem => (super.noSuchMethod(
        Invocation.getter(#pointsToRedeem),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get loyaltyDiscount => (super.noSuchMethod(
        Invocation.getter(#loyaltyDiscount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get promoDiscounts => (super.noSuchMethod(
        Invocation.getter(#promoDiscounts),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get commercialRate => (super.noSuchMethod(
        Invocation.getter(#commercialRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get bcnOfficialRate => (super.noSuchMethod(
        Invocation.getter(#bcnOfficialRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get checkoutFxMode => (super.noSuchMethod(
        Invocation.getter(#checkoutFxMode),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#checkoutFxMode),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#checkoutFxMode),
        ),
      ) as String);

  @override
  double get activeCheckoutRate => (super.noSuchMethod(
        Invocation.getter(#activeCheckoutRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get activeCheckoutRateLabel => (super.noSuchMethod(
        Invocation.getter(#activeCheckoutRateLabel),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#activeCheckoutRateLabel),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#activeCheckoutRateLabel),
        ),
      ) as String);

  @override
  List<_i14.CartItem> get cart => (super.noSuchMethod(
        Invocation.getter(#cart),
        returnValue: <_i14.CartItem>[],
        returnValueForMissingStub: <_i14.CartItem>[],
      ) as List<_i14.CartItem>);

  @override
  List<_i15.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i15.Product>[],
        returnValueForMissingStub: <_i15.Product>[],
      ) as List<_i15.Product>);

  @override
  List<_i16.Promotion> get promotions => (super.noSuchMethod(
        Invocation.getter(#promotions),
        returnValue: <_i16.Promotion>[],
        returnValueForMissingStub: <_i16.Promotion>[],
      ) as List<_i16.Promotion>);

  @override
  List<_i16.Promotion> get allPromotions => (super.noSuchMethod(
        Invocation.getter(#allPromotions),
        returnValue: <_i16.Promotion>[],
        returnValueForMissingStub: <_i16.Promotion>[],
      ) as List<_i16.Promotion>);

  @override
  List<_i17.HoldTicket> get holdTickets => (super.noSuchMethod(
        Invocation.getter(#holdTickets),
        returnValue: <_i17.HoldTicket>[],
        returnValueForMissingStub: <_i17.HoldTicket>[],
      ) as List<_i17.HoldTicket>);

  @override
  Map<_i18.PaymentMethod, double> get sessionExpected => (super.noSuchMethod(
        Invocation.getter(#sessionExpected),
        returnValue: <_i18.PaymentMethod, double>{},
        returnValueForMissingStub: <_i18.PaymentMethod, double>{},
      ) as Map<_i18.PaymentMethod, double>);

  @override
  bool get isGlobalTaxExempt => (super.noSuchMethod(
        Invocation.getter(#isGlobalTaxExempt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get canManageCashDrawer => (super.noSuchMethod(
        Invocation.getter(#canManageCashDrawer),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canVoidInvoice => (super.noSuchMethod(
        Invocation.getter(#canVoidInvoice),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canReprint => (super.noSuchMethod(
        Invocation.getter(#canReprint),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSupervisorOverrideActive => (super.noSuchMethod(
        Invocation.getter(#isSupervisorOverrideActive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.FiscalCalculationResult get currentFiscalCalculation =>
      (super.noSuchMethod(
        Invocation.getter(#currentFiscalCalculation),
        returnValue: _FakeFiscalCalculationResult_0(
          this,
          Invocation.getter(#currentFiscalCalculation),
        ),
        returnValueForMissingStub: _FakeFiscalCalculationResult_0(
          this,
          Invocation.getter(#currentFiscalCalculation),
        ),
      ) as _i2.FiscalCalculationResult);

  @override
  double get subtotal => (super.noSuchMethod(
        Invocation.getter(#subtotal),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get grossSubtotal => (super.noSuchMethod(
        Invocation.getter(#grossSubtotal),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalTax => (super.noSuchMethod(
        Invocation.getter(#totalTax),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get taxableSubtotal => (super.noSuchMethod(
        Invocation.getter(#taxableSubtotal),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get exemptSubtotal => (super.noSuchMethod(
        Invocation.getter(#exemptSubtotal),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalDiscounts => (super.noSuchMethod(
        Invocation.getter(#totalDiscounts),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.TipType get tipType => (super.noSuchMethod(
        Invocation.getter(#tipType),
        returnValue: _i4.TipType.suggestedTenPercent,
        returnValueForMissingStub: _i4.TipType.suggestedTenPercent,
      ) as _i4.TipType);

  @override
  double get customTipPercentage => (super.noSuchMethod(
        Invocation.getter(#customTipPercentage),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get fixedTipAmount => (super.noSuchMethod(
        Invocation.getter(#fixedTipAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i3.BusinessModeEvaluator get businessModeEvaluator => (super.noSuchMethod(
        Invocation.getter(#businessModeEvaluator),
        returnValue: _FakeBusinessModeEvaluator_1(
          this,
          Invocation.getter(#businessModeEvaluator),
        ),
        returnValueForMissingStub: _FakeBusinessModeEvaluator_1(
          this,
          Invocation.getter(#businessModeEvaluator),
        ),
      ) as _i3.BusinessModeEvaluator);

  @override
  _i4.TipCalculation get tipCalculation => (super.noSuchMethod(
        Invocation.getter(#tipCalculation),
        returnValue: _FakeTipCalculation_2(
          this,
          Invocation.getter(#tipCalculation),
        ),
        returnValueForMissingStub: _FakeTipCalculation_2(
          this,
          Invocation.getter(#tipCalculation),
        ),
      ) as _i4.TipCalculation);

  @override
  double get tipAmount => (super.noSuchMethod(
        Invocation.getter(#tipAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get grandTotalWithTip => (super.noSuchMethod(
        Invocation.getter(#grandTotalWithTip),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  List<_i15.Product> get filteredProducts => (super.noSuchMethod(
        Invocation.getter(#filteredProducts),
        returnValue: <_i15.Product>[],
        returnValueForMissingStub: <_i15.Product>[],
      ) as List<_i15.Product>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i19.Future<_i6.Customer?> identifyCustomer(String? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #identifyCustomer,
          [input],
        ),
        returnValue: _i19.Future<_i6.Customer?>.value(),
        returnValueForMissingStub: _i19.Future<_i6.Customer?>.value(),
      ) as _i19.Future<_i6.Customer?>);

  @override
  void selectReward(String? rewardId) => super.noSuchMethod(
        Invocation.method(
          #selectReward,
          [rewardId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearReward() => super.noSuchMethod(
        Invocation.method(
          #clearReward,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBuzzerNumber(String? number) => super.noSuchMethod(
        Invocation.method(
          #setBuzzerNumber,
          [number],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> selectCustomer(_i6.Customer? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectCustomer,
          [customer],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void clearCustomer() => super.noSuchMethod(
        Invocation.method(
          #clearCustomer,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.RedemptionValidationResult applyLoyaltyPoints(double? points) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyLoyaltyPoints,
          [points],
        ),
        returnValue: _FakeRedemptionValidationResult_3(
          this,
          Invocation.method(
            #applyLoyaltyPoints,
            [points],
          ),
        ),
        returnValueForMissingStub: _FakeRedemptionValidationResult_3(
          this,
          Invocation.method(
            #applyLoyaltyPoints,
            [points],
          ),
        ),
      ) as _i5.RedemptionValidationResult);

  @override
  void clearLoyaltyPoints() => super.noSuchMethod(
        Invocation.method(
          #clearLoyaltyPoints,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCustomerName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setCustomerName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<List<_i6.Customer>> searchCustomers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCustomers,
          [query],
        ),
        returnValue: _i19.Future<List<_i6.Customer>>.value(<_i6.Customer>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i6.Customer>>.value(<_i6.Customer>[]),
      ) as _i19.Future<List<_i6.Customer>>);

  @override
  _i19.Future<_i6.Customer> createExpressCustomer({
    required String? name,
    String? taxId,
    String? phone,
    String? email,
    String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpressCustomer,
          [],
          {
            #name: name,
            #taxId: taxId,
            #phone: phone,
            #email: email,
            #address: address,
          },
        ),
        returnValue: _i19.Future<_i6.Customer>.value(_FakeCustomer_4(
          this,
          Invocation.method(
            #createExpressCustomer,
            [],
            {
              #name: name,
              #taxId: taxId,
              #phone: phone,
              #email: email,
              #address: address,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Customer>.value(_FakeCustomer_4(
          this,
          Invocation.method(
            #createExpressCustomer,
            [],
            {
              #name: name,
              #taxId: taxId,
              #phone: phone,
              #email: email,
              #address: address,
            },
          ),
        )),
      ) as _i19.Future<_i6.Customer>);

  @override
  _i19.Future<void> loadTenantConfig() => (super.noSuchMethod(
        Invocation.method(
          #loadTenantConfig,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void setCompanyTaxRegime(_i20.TaxRegime? regime) => super.noSuchMethod(
        Invocation.method(
          #setCompanyTaxRegime,
          [regime],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> loadCompanyTaxRegime() => (super.noSuchMethod(
        Invocation.method(
          #loadCompanyTaxRegime,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> loadExchangeRates() => (super.noSuchMethod(
        Invocation.method(
          #loadExchangeRates,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void grantSupervisorOverride() => super.noSuchMethod(
        Invocation.method(
          #grantSupervisorOverride,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyManualDiscount(double? discountAmount) => super.noSuchMethod(
        Invocation.method(
          #applyManualDiscount,
          [discountAmount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getCartItemLineAmount(_i14.CartItem? item) => (super.noSuchMethod(
        Invocation.method(
          #getCartItemLineAmount,
          [item],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  void setTip({
    required _i4.TipType? tipType,
    double? customPercentage = 0.0,
    double? fixedAmount = 0.0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setTip,
          [],
          {
            #tipType: tipType,
            #customPercentage: customPercentage,
            #fixedAmount: fixedAmount,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearTip() => super.noSuchMethod(
        Invocation.method(
          #clearTip,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.SplitBillResult calculateEqualSplit(int? coverCount) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEqualSplit,
          [coverCount],
        ),
        returnValue: _FakeSplitBillResult_5(
          this,
          Invocation.method(
            #calculateEqualSplit,
            [coverCount],
          ),
        ),
        returnValueForMissingStub: _FakeSplitBillResult_5(
          this,
          Invocation.method(
            #calculateEqualSplit,
            [coverCount],
          ),
        ),
      ) as _i7.SplitBillResult);

  @override
  _i7.SplitBillResult calculateItemizedSplit(
          List<_i7.ItemizedShareInput>? shares) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateItemizedSplit,
          [shares],
        ),
        returnValue: _FakeSplitBillResult_5(
          this,
          Invocation.method(
            #calculateItemizedSplit,
            [shares],
          ),
        ),
        returnValueForMissingStub: _FakeSplitBillResult_5(
          this,
          Invocation.method(
            #calculateItemizedSplit,
            [shares],
          ),
        ),
      ) as _i7.SplitBillResult);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> loadPromotions() => (super.noSuchMethod(
        Invocation.method(
          #loadPromotions,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> togglePromotion(
    String? promoId,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePromotion,
          [
            promoId,
            isActive,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> searchAndAddToCart(String? code) => (super.noSuchMethod(
        Invocation.method(
          #searchAndAddToCart,
          [code],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> loadHoldTickets() => (super.noSuchMethod(
        Invocation.method(
          #loadHoldTickets,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> holdCurrentTicket(
    String? name, {
    String? tableId,
    String? areaId,
    String? waiterId,
    String? waiterName,
    int? guestCount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #holdCurrentTicket,
          [name],
          {
            #tableId: tableId,
            #areaId: areaId,
            #waiterId: waiterId,
            #waiterName: waiterName,
            #guestCount: guestCount,
          },
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> recallTicket(_i17.HoldTicket? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #recallTicket,
          [ticket],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void cancelLoadedHoldTicket() => super.noSuchMethod(
        Invocation.method(
          #cancelLoadedHoldTicket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> checkActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #checkActiveSession,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> openSession(
    double? balance, {
    _i21.CashSessionModel? tipoModelo = _i21.CashSessionModel.cajaCentral,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openSession,
          [balance],
          {#tipoModelo: tipoModelo},
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> closeSession(double? closingBalance) => (super.noSuchMethod(
        Invocation.method(
          #closeSession,
          [closingBalance],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void addToCart(
    _i15.Product? product, {
    double? quantity = 1.0,
    String? variantId,
    List<_i15.Modifier>? modifiers = const [],
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [product],
          {
            #quantity: quantity,
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCart(
    String? productId, {
    String? variantId,
    List<_i15.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeFromCart,
          [productId],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateQuantity(
    String? productId,
    double? quantity, {
    String? variantId,
    List<_i15.Modifier>? modifiers,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            productId,
            quantity,
          ],
          {
            #variantId: variantId,
            #modifiers: modifiers,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleGlobalTaxExempt() => super.noSuchMethod(
        Invocation.method(
          #toggleGlobalTaxExempt,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCart() => super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> finalizeSale(List<_i18.PaymentMethod>? methods) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeSale,
          [methods],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> processSale(
    List<_i18.PaymentMethod>? methods, {
    List<_i18.Payment>? customPayments,
    String? buzzerNumber,
    String? customerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSale,
          [methods],
          {
            #customPayments: customPayments,
            #buzzerNumber: buzzerNumber,
            #customerName: customerName,
          },
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<bool> reprintInvoice(
    String? invoiceId,
    String? reasonCode, {
    String? reasonDetail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reprintInvoice,
          [
            invoiceId,
            reasonCode,
          ],
          {#reasonDetail: reasonDetail},
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  _i19.Future<bool> processReturn(
    String? invoiceNumber,
    String? reason, {
    _i22.RefundReasonPolicy? refundReasonPolicy =
        _i22.RefundReasonPolicy.restockOriginalBom,
    List<_i22.CreditNoteRefundLine>? lines,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processReturn,
          [
            invoiceNumber,
            reason,
          ],
          {
            #refundReasonPolicy: refundReasonPolicy,
            #lines: lines,
          },
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  _i19.Future<bool> voidInvoice(
    String? invoiceId,
    String? reasonCode, {
    String? reasonDetail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidInvoice,
          [
            invoiceId,
            reasonCode,
          ],
          {#reasonDetail: reasonDetail},
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i24.AuthRepository {
  @override
  bool get isPendingSync => (super.noSuchMethod(
        Invocation.getter(#isPendingSync),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i19.Future<_i25.User?> loginOnline(
    String? email,
    String? password, {
    String? tenantSlug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOnline,
          [
            email,
            password,
          ],
          {#tenantSlug: tenantSlug},
        ),
        returnValue: _i19.Future<_i25.User?>.value(),
        returnValueForMissingStub: _i19.Future<_i25.User?>.value(),
      ) as _i19.Future<_i25.User?>);

  @override
  _i19.Future<_i8.TerminalLinking> claimLinkingCode(
    String? code,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimLinkingCode,
          [
            code,
            deviceId,
          ],
        ),
        returnValue:
            _i19.Future<_i8.TerminalLinking>.value(_FakeTerminalLinking_6(
          this,
          Invocation.method(
            #claimLinkingCode,
            [
              code,
              deviceId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i8.TerminalLinking>.value(_FakeTerminalLinking_6(
          this,
          Invocation.method(
            #claimLinkingCode,
            [
              code,
              deviceId,
            ],
          ),
        )),
      ) as _i19.Future<_i8.TerminalLinking>);

  @override
  _i19.Future<void> syncStaff() => (super.noSuchMethod(
        Invocation.method(
          #syncStaff,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i25.User?> loginOffline(
    String? userId,
    String? pin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginOffline,
          [
            userId,
            pin,
          ],
        ),
        returnValue: _i19.Future<_i25.User?>.value(),
        returnValueForMissingStub: _i19.Future<_i25.User?>.value(),
      ) as _i19.Future<_i25.User?>);

  @override
  _i19.Future<bool> authorizeOverride({
    required String? supervisorId,
    String? pin,
    String? totpCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeOverride,
          [],
          {
            #supervisorId: supervisorId,
            #pin: pin,
            #totpCode: totpCode,
          },
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  _i19.Future<_i25.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i19.Future<_i25.User?>.value(),
        returnValueForMissingStub: _i19.Future<_i25.User?>.value(),
      ) as _i19.Future<_i25.User?>);

  @override
  _i19.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i19.Future<String?>.value(),
        returnValueForMissingStub: _i19.Future<String?>.value(),
      ) as _i19.Future<String?>);

  @override
  _i19.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<List<_i25.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i19.Future<List<_i25.User>>.value(<_i25.User>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i25.User>>.value(<_i25.User>[]),
      ) as _i19.Future<List<_i25.User>>);

  @override
  _i19.Future<void> saveUser(
    _i25.User? user, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
          {#pin: pin},
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [AuditRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditRepository extends _i1.Mock implements _i9.AuditRepository {
  @override
  String get deviceId => (super.noSuchMethod(
        Invocation.getter(#deviceId),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#deviceId),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#deviceId),
        ),
      ) as String);

  @override
  _i19.Future<void> log(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #log,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i26.AuditLog?> prepareLog(
    String? action, {
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareLog,
          [action],
          {#metadata: metadata},
        ),
        returnValue: _i19.Future<_i26.AuditLog?>.value(),
        returnValueForMissingStub: _i19.Future<_i26.AuditLog?>.value(),
      ) as _i19.Future<_i26.AuditLog?>);

  @override
  _i19.Future<void> logForensic(
    String? action, {
    String? metadata,
    String? metodoAutorizacion,
    String? usuarioAutorizadorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logForensic,
          [action],
          {
            #metadata: metadata,
            #metodoAutorizacion: metodoAutorizacion,
            #usuarioAutorizadorId: usuarioAutorizadorId,
          },
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i9.AuditSyncOutcome> syncLogs() => (super.noSuchMethod(
        Invocation.method(
          #syncLogs,
          [],
        ),
        returnValue:
            _i19.Future<_i9.AuditSyncOutcome>.value(_FakeAuditSyncOutcome_7(
          this,
          Invocation.method(
            #syncLogs,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i9.AuditSyncOutcome>.value(_FakeAuditSyncOutcome_7(
          this,
          Invocation.method(
            #syncLogs,
            [],
          ),
        )),
      ) as _i19.Future<_i9.AuditSyncOutcome>);

  @override
  _i19.Future<List<_i26.AuditLog>> getLocalLogs({
    DateTime? start,
    DateTime? end,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalLogs,
          [],
          {
            #start: start,
            #end: end,
            #userId: userId,
          },
        ),
        returnValue: _i19.Future<List<_i26.AuditLog>>.value(<_i26.AuditLog>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i26.AuditLog>>.value(<_i26.AuditLog>[]),
      ) as _i19.Future<List<_i26.AuditLog>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i10.SyncService {
  @override
  _i19.Stream<_i10.InboundSyncResult> get onInboundSync => (super.noSuchMethod(
        Invocation.getter(#onInboundSync),
        returnValue: _i19.Stream<_i10.InboundSyncResult>.empty(),
        returnValueForMissingStub: _i19.Stream<_i10.InboundSyncResult>.empty(),
      ) as _i19.Stream<_i10.InboundSyncResult>);

  @override
  _i19.Stream<_i10.CloudSyncStatus> get onStatusChanged => (super.noSuchMethod(
        Invocation.getter(#onStatusChanged),
        returnValue: _i19.Stream<_i10.CloudSyncStatus>.empty(),
        returnValueForMissingStub: _i19.Stream<_i10.CloudSyncStatus>.empty(),
      ) as _i19.Stream<_i10.CloudSyncStatus>);

  @override
  _i19.Stream<_i10.SalesRecordRejection> get onSalesRecordRejected =>
      (super.noSuchMethod(
        Invocation.getter(#onSalesRecordRejected),
        returnValue: _i19.Stream<_i10.SalesRecordRejection>.empty(),
        returnValueForMissingStub:
            _i19.Stream<_i10.SalesRecordRejection>.empty(),
      ) as _i19.Stream<_i10.SalesRecordRejection>);

  @override
  _i10.CloudSyncStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i10.CloudSyncStatus.idle,
        returnValueForMissingStub: _i10.CloudSyncStatus.idle,
      ) as _i10.CloudSyncStatus);

  @override
  int get consecutiveFailures => (super.noSuchMethod(
        Invocation.getter(#consecutiveFailures),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isAuthBlocked => (super.noSuchMethod(
        Invocation.getter(#isAuthBlocked),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCloudAuthRequired => (super.noSuchMethod(
        Invocation.getter(#isCloudAuthRequired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration getNextBackoffDelay() => (super.noSuchMethod(
        Invocation.method(
          #getNextBackoffDelay,
          [],
        ),
        returnValue: _FakeDuration_8(
          this,
          Invocation.method(
            #getNextBackoffDelay,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDuration_8(
          this,
          Invocation.method(
            #getNextBackoffDelay,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i19.Future<int> getPendingOutboxCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingOutboxCount,
          [],
        ),
        returnValue: _i19.Future<int>.value(0),
        returnValueForMissingStub: _i19.Future<int>.value(0),
      ) as _i19.Future<int>);

  @override
  _i19.Future<_i10.SyncRunOutcome> triggerManualSync() => (super.noSuchMethod(
        Invocation.method(
          #triggerManualSync,
          [],
        ),
        returnValue:
            _i19.Future<_i10.SyncRunOutcome>.value(_FakeSyncRunOutcome_9(
          this,
          Invocation.method(
            #triggerManualSync,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i10.SyncRunOutcome>.value(_FakeSyncRunOutcome_9(
          this,
          Invocation.method(
            #triggerManualSync,
            [],
          ),
        )),
      ) as _i19.Future<_i10.SyncRunOutcome>);

  @override
  Map<String, Object> buildOrderedBatchEnvelopeForTest(
          List<dynamic>? unsynced) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildOrderedBatchEnvelopeForTest,
          [unsynced],
        ),
        returnValue: <String, Object>{},
        returnValueForMissingStub: <String, Object>{},
      ) as Map<String, Object>);

  @override
  _i19.Future<_i10.InboundSyncResult?> pullInboundDeltas() =>
      (super.noSuchMethod(
        Invocation.method(
          #pullInboundDeltas,
          [],
        ),
        returnValue: _i19.Future<_i10.InboundSyncResult?>.value(),
        returnValueForMissingStub: _i19.Future<_i10.InboundSyncResult?>.value(),
      ) as _i19.Future<_i10.InboundSyncResult?>);
}
